SIPNET: outputItems.h File Reference
outputItems.h File Reference
#include <stdio.h>
Data Structures
struct SingleOutputItemStruct
struct OutputItemsStruct
Macros
#define OUTPUT_ITEMS_MAXNAME 64
Typedefs
typedef struct SingleOutputItemStruct SingleOutputItem
typedef struct OutputItemsStruct OutputItems
Functions
OutputItems * newOutputItems (char *filenameBase, char separator)
void addOutputItem (OutputItems *outputItems, char *name, double *ptr)
void writeOutputItemLabels (OutputItems *outputItems, char *label)
void writeOutputItemValues (OutputItems *outputItems)
void terminateOutputItemLines (OutputItems *outputItems)
void deleteOutputItems (OutputItems *outputItems)
Macro Definition Documentation
OUTPUT_ITEMS_MAXNAME
#define OUTPUT_ITEMS_MAXNAME 64
Definition at line 8 of file outputItems.h.
Typedef Documentation
OutputItems
typedef struct OutputItemsStruct OutputItems
SingleOutputItem
typedef struct SingleOutputItemStruct SingleOutputItem
Function Documentation
addOutputItem()
void addOutputItem (OutputItems * outputItems, char * name, double * ptr)
Definition at line 98 of file outputItems.c.
References OutputItemsStruct::count, OutputItemsStruct::filenameBase, newSingleOutputItem(), SingleOutputItemStruct::nextItem, openOutputItemFile(), and OutputItemsStruct::tail.
Referenced by setupOutputItems().
deleteOutputItems()
void deleteOutputItems (OutputItems * outputItems)
Definition at line 152 of file outputItems.c.
References closeOutputItemFile(), SingleOutputItemStruct::f, OutputItemsStruct::filenameBase, OutputItemsStruct::head, and SingleOutputItemStruct::nextItem.
Referenced by main().
newOutputItems()
OutputItems * newOutputItems (char * filenameBase, char separator)
Definition at line 72 of file outputItems.c.
References OutputItemsStruct::count, OutputItemsStruct::filenameBase, OutputItemsStruct::head, newSingleOutputItem(), OutputItemsStruct::separator, and OutputItemsStruct::tail.
Referenced by main().
terminateOutputItemLines()
void terminateOutputItemLines (OutputItems * outputItems)
Definition at line 139 of file outputItems.c.
References SingleOutputItemStruct::f, OutputItemsStruct::head, and SingleOutputItemStruct::nextItem.
Referenced by runModelOutput().
writeOutputItemLabels()
void writeOutputItemLabels (OutputItems * outputItems, char * label)
Definition at line 114 of file outputItems.c.
References SingleOutputItemStruct::f, OutputItemsStruct::head, SingleOutputItemStruct::nextItem, and OutputItemsStruct::separator.
Referenced by runModelOutput(), and sensTest().
writeOutputItemValues()
void writeOutputItemValues (OutputItems * outputItems)
Definition at line 125 of file outputItems.c.
References SingleOutputItemStruct::f, OutputItemsStruct::head, SingleOutputItemStruct::nextItem, SingleOutputItemStruct::ptr, and OutputItemsStruct::separator.
Referenced by runModelOutput().