SIPNET: climdn.m File Reference
climdn.m File Reference
Functions
q (find(q >0))
q (end+1)
intervaldn (i)
tairdn (i)
vpddn (i)
vpdsoildn (i)
vpressdn (i)
wspddn (i)
pardn (i)
end tsoildn (i)
pptdn (i)
id ascii ()
Variables
tairfill =load('~/niwot/climate/tairfill')
vpdfill =load('~/niwot/climate/vpdfill')
vpdsoilfill =load('~/niwot/climate/vpdsoilfill')
parfill =load('~/niwot/climate/parfill')
tsoilfill =load('~/niwot/climate/tsoilfill')
vpressfill =load('~/niwot/climate/vpressfill')
wspdfill =load('~/niwot/climate/wspdfill')
time =load('~/niwot/climate/timeday')
potpar =load('~/niwot/climate/potpar')
nlight =load('~/niwot/climate/nlight')
pptday =load('data/pptday')
ppt = load('~/niwot/climate/precipfill')
for Niwot
q =diff(q)
w =find(q==1)
i0 =1
pptwanklist =[1 fix((1:(2*ndays+1))/2+.5)]
for i
end tairdn =tairdn'
vpddn =vpddn'
vpdsoildn =vpdsoildn'
pardn =pardn'
tsoildn =tsoildn'
vpressdn =vpressdn'
wspddn =wspddn'
pptdn =pptdn'
intervaldn =intervaldn'
Function Documentation
ascii()
id ascii () virtual
intervaldn()
intervaldn (i)
References length().
pardn()
pardn (i)
pptdn()
pptdn (i)
q() [1/2]
q (end+ 1)
q() [2/2]
q (find(q >0))
tairdn()
tairdn (i)
References mean().
tsoildn()
end tsoildn (i)
References mean().
vpddn()
vpddn (i)
References mean().
vpdsoildn()
vpdsoildn (i)
References mean().
vpressdn()
vpressdn (i)
References mean().
wspddn()
wspddn (i)
References mean().
Variable Documentation
i
for i
Initial value:
=1:(2*ndays+1)
    wdn=i0:w(i)
Definition at line 25 of file climdn.m.
i0
i0 =1
Definition at line 21 of file climdn.m.
intervaldn
intervaldn =intervaldn'
Definition at line 50 of file climdn.m.
Niwot
for Niwot
Definition at line 13 of file climdn.m.
nlight
nlight =load('~/niwot/climate/nlight')
Definition at line 11 of file climdn.m.
pardn
i pardn =pardn'
Definition at line 45 of file climdn.m.
parfill
parfill =load('~/niwot/climate/parfill')
Definition at line 5 of file climdn.m.
potpar
id potpar =load('~/niwot/climate/potpar')
Definition at line 10 of file climdn.m.
ppt
ppt = load('~/niwot/climate/precipfill')
Definition at line 13 of file climdn.m.
pptday
pptday =load('data/pptday')
Definition at line 12 of file climdn.m.
pptdn
pptdn =pptdn'
Definition at line 49 of file climdn.m.
pptwanklist
pptwanklist =[1 fix((1:(2*ndays+1))/2+.5)]
Definition at line 23 of file climdn.m.
q
q =diff(q)
Definition at line 17 of file climdn.m.
tairdn
end tairdn =tairdn'
Definition at line 42 of file climdn.m.
tairfill
tairfill =load('~/niwot/climate/tairfill')
Definition at line 2 of file climdn.m.
time
time =load('~/niwot/climate/timeday')
Definition at line 9 of file climdn.m.
Referenced by main(), outputState(), outputStatecsv(), readClimData(), and seedRand().
tsoildn
tsoildn =tsoildn'
Definition at line 46 of file climdn.m.
tsoilfill
tsoilfill =load('~/niwot/climate/tsoilfill')
Definition at line 6 of file climdn.m.
vpddn
vpddn =vpddn'
Definition at line 43 of file climdn.m.
vpdfill
vpdfill =load('~/niwot/climate/vpdfill')
Definition at line 3 of file climdn.m.
vpdsoildn
vpdsoildn =vpdsoildn'
Definition at line 44 of file climdn.m.
vpdsoilfill
vpdsoilfill =load('~/niwot/climate/vpdsoilfill')
Definition at line 4 of file climdn.m.
vpressdn
vpressdn =vpressdn'
Definition at line 47 of file climdn.m.
vpressfill
vpressfill =load('~/niwot/climate/vpressfill')
Definition at line 7 of file climdn.m.
w
w =find(q==1)
Definition at line 20 of file climdn.m.
wspddn
wspddn =wspddn'
Definition at line 48 of file climdn.m.
wspdfill
wspdfill =load('~/niwot/climate/wspdfill')
Definition at line 8 of file climdn.m.