SIPNET: context.h File Reference
context.h File Reference
#include <stdio.h>
#include "common/uthash.h"
Data Structures
struct context_metadata
struct Context
Macros
#define CONTEXT_CHAR_MAXLEN 256
#define FILENAME_MAXLEN CONTEXT_CHAR_MAXLEN
#define CREATE_INT_CONTEXT(name, printName, value, flag)
#define CREATE_CHAR_CONTEXT(name, printName, value)
Typedefs
typedef enum ContextSource context_source_t
typedef enum ContextType context_type_t
Enumerations
enum ContextSource {
CTX_DEFAULT = 0 , CTX_CONTEXT_FILE = 1 , CTX_COMMAND_LINE = 2 , CTX_CALCULATED = 3 ,
CTX_TEST = 4
}
enum ContextType { CTX_INT = 0 , CTX_CHAR = 1 }
Functions
void initContext (void)
struct context_metadata * getContextMetadata (const char *name)
void createContextMetadata (const char *name, const char *printName, context_source_t source, context_type_t type, void *value, int isFlag)
void updateIntContext (const char *name, int value, context_source_t source)
void updateCharContext (const char *name, const char *value, context_source_t source)
int hasSourcePrecedence (struct context_metadata *s, context_source_t newSource)
char * getContextSourceString (context_source_t src)
void validateFilename (void)
void validateContext (void)
void printConfig (FILE *outFile)
Variables
struct Context ctx
Macro Definition Documentation
CONTEXT_CHAR_MAXLEN
#define CONTEXT_CHAR_MAXLEN 256
Definition at line 8 of file context.h.
CREATE_CHAR_CONTEXT
#define CREATE_CHAR_CONTEXT (name, printName, value)
Value:
  do {                                                                         \
    strncpy(ctx.name, value, CONTEXT_CHAR_MAXLEN);                             \
    createContextMetadata(#name, printName, CTX_DEFAULT, CTX_CHAR, ctx.name,   \
                          0);                                                  \
  } while (0)
Definition at line 117 of file context.h.
CREATE_INT_CONTEXT
#define CREATE_INT_CONTEXT (name, printName, value, flag)
Value:
  do {                                                                         \
    ctx.name = value;                                                          \
    createContextMetadata(#name, printName, CTX_DEFAULT, CTX_INT, &ctx.name,   \
                          flag);                                               \
  } while (0)
Definition at line 110 of file context.h.
FILENAME_MAXLEN
#define FILENAME_MAXLEN CONTEXT_CHAR_MAXLEN
Definition at line 10 of file context.h.
Typedef Documentation
context_source_t
typedef enum ContextSource context_source_t
context_type_t
typedef enum ContextType context_type_t
Enumeration Type Documentation
ContextSource
enum ContextSource
Enumerator
CTX_DEFAULT
CTX_CONTEXT_FILE
CTX_COMMAND_LINE
CTX_CALCULATED
CTX_TEST
Definition at line 16 of file context.h.
ContextType
enum ContextType
Enumerator
CTX_INT
CTX_CHAR
Definition at line 26 of file context.h.
Function Documentation
createContextMetadata()
void createContextMetadata (const char * name, const char * printName, context_source_t source, context_type_t type, void * value, int isFlag)
Definition at line 87 of file context.c.
References ctx, EXIT_CODE_INTERNAL_ERROR, HASH_ADD_STR, HASH_FIND_STR, context_metadata::isFlag, keyName, context_metadata::keyName, Context::metaMap, nameToKey(), context_metadata::printName, context_metadata::source, context_metadata::type, and context_metadata::value.
getContextMetadata()
struct context_metadata * getContextMetadata (const char * name)
Definition at line 80 of file context.c.
References ctx, HASH_FIND_STR, keyName, Context::metaMap, and nameToKey().
Referenced by checkCLINameMap(), and readInputFile().
getContextSourceString()
char * getContextSourceString (context_source_t src)
Definition at line 144 of file context.c.
References CTX_CALCULATED, CTX_COMMAND_LINE, CTX_CONTEXT_FILE, CTX_DEFAULT, and CTX_TEST.
Referenced by printConfig().
hasSourcePrecedence()
int hasSourcePrecedence (struct context_metadata * s, context_source_t newSource)
Definition at line 137 of file context.c.
References context_metadata::source.
Referenced by updateCharContext(), and updateIntContext().
initContext()
void initContext (void)
Initialize the global context struct with default values
Definition at line 25 of file context.c.
References ARG_OFF, ARG_ON, Context::climFile, CREATE_CHAR_CONTEXT, CREATE_INT_CONTEXT, ctx, DEFAULT_FILE_NAME, DEFAULT_INPUT_FILE, Context::doMainOutput, Context::doSingleOutputs, Context::dumpConfig, events, Context::fileName, FLAG_YES, Context::gdd, Context::growthResp, Context::inputFile, Context::leafWater, Context::litterPool, Context::metaMap, Context::microbes, NO_DEFAULT_FILE, Context::outConfigFile, Context::outFile, Context::paramFile, Context::printHeader, Context::quiet, Context::snow, Context::soilPhenol, and Context::waterHResp.
Referenced by main().
printConfig()
void printConfig (FILE * outFile)
Definition at line 196 of file context.c.
References by_name(), ctx, CTX_CHAR, CTX_INT, EXIT_CODE_INTERNAL_ERROR, getContextSourceString(), HASH_SORT, context_metadata::hh, Context::metaMap, UT_hash_handle::next, Context::printHeader, context_metadata::printName, context_metadata::source, context_metadata::type, and context_metadata::value.
Referenced by main().
updateCharContext()
void updateCharContext (const char * name, const char * value, context_source_t source)
Definition at line 122 of file context.c.
References CONTEXT_CHAR_MAXLEN, ctx, EXIT_CODE_INTERNAL_ERROR, HASH_FIND_STR, hasSourcePrecedence(), keyName, Context::metaMap, nameToKey(), context_metadata::source, and context_metadata::value.
Referenced by main(), parseCommandLineArgs(), and readInputFile().
updateIntContext()
void updateIntContext (const char * name, int value, context_source_t source)
Definition at line 108 of file context.c.
References ctx, EXIT_CODE_INTERNAL_ERROR, HASH_FIND_STR, hasSourcePrecedence(), keyName, Context::metaMap, nameToKey(), context_metadata::source, and context_metadata::value.
Referenced by parseCommandLineArgs(), and readInputFile().
validateContext()
void validateContext (void)
Definition at line 183 of file context.c.
References ctx, EXIT_CODE_BAD_PARAMETER_VALUE, Context::gdd, logError, and Context::soilPhenol.
Referenced by main().
validateFilename()
void validateFilename (void)
Definition at line 167 of file context.c.
References ctx, EXIT_CODE_BAD_PARAMETER_VALUE, Context::fileName, and FILENAME_MAXLEN.
Referenced by readInputFile().
Variable Documentation
ctx
struct Context ctx extern
Definition at line 19 of file context.c.
Referenced by calcMaintenanceRespiration(), calcPrecip(), calculateFluxes(), checkAllRead(), checkCLINameMap(), checkRuntype(), cleanupModel(), createContextMetadata(), ensureNonNegativeStocks(), getContextMetadata(), initContext(), initEvents(), logprint(), main(), microbeGrowth(), parseCommandLineArgs(), pastLeafGrowth(), printConfig(), processEvents(), readClimData(), readInputFile(), readParamData(), setupModel(), soilBreakdown(), soilDegradation(), updateCharContext(), updateIntContext(), validateContext(), and validateFilename().