SIPNET: namelistInput.h File Reference
namelistInput.h File Reference
Data Structures
struct NamelistInputItemStruct
struct NamelistInputsStruct
Macros
#define NAMELIST_INPUT_MAXNAME 64
Typedefs
typedef struct NamelistInputItemStruct NamelistInputItem
typedef struct NamelistInputsStruct NamelistInputs
Enumerations
enum INPUT_TYPES { INT_TYPE , LONG_TYPE , DOUBLE_TYPE , STRING_TYPE }
Functions
NamelistInputs * newNamelistInputs (void)
void addNamelistInputItem (NamelistInputs *namelistInputs, char *name, int type, void *ptr, int maxlen)
void readNamelistInputs (NamelistInputs *namelistInputs, const char *fileName)
void dieIfNotRead (NamelistInputs *namelistInputs, char *name)
void dieIfNotSet (NamelistInputs *namelistInputs, char *name)
void deleteNamelistInputs (NamelistInputs *namelistInputs)
Macro Definition Documentation
NAMELIST_INPUT_MAXNAME
#define NAMELIST_INPUT_MAXNAME 64
Definition at line 8 of file namelistInput.h.
Typedef Documentation
NamelistInputItem
typedef struct NamelistInputItemStruct NamelistInputItem
NamelistInputs
typedef struct NamelistInputsStruct NamelistInputs
Enumeration Type Documentation
INPUT_TYPES
enum INPUT_TYPES
Enumerator
INT_TYPE
LONG_TYPE
DOUBLE_TYPE
STRING_TYPE
Definition at line 11 of file namelistInput.h.
Function Documentation
addNamelistInputItem()
void addNamelistInputItem (NamelistInputs * namelistInputs, char * name, int type, void * ptr, int maxlen)
Definition at line 96 of file namelistInput.c.
References NamelistInputsStruct::count, newNamelistInputItem(), NamelistInputItemStruct::nextItem, and NamelistInputsStruct::tail.
Referenced by main().
deleteNamelistInputs()
void deleteNamelistInputs (NamelistInputs * namelistInputs)
Definition at line 282 of file namelistInput.c.
References NamelistInputsStruct::head, and NamelistInputItemStruct::nextItem.
dieIfNotRead()
void dieIfNotRead (NamelistInputs * namelistInputs, char * name)
Definition at line 238 of file namelistInput.c.
References locateNamelistInputItem(), and NamelistInputItemStruct::wasRead.
Referenced by dieIfNotSet(), and main().
dieIfNotSet()
void dieIfNotSet (NamelistInputs * namelistInputs, char * name)
Definition at line 260 of file namelistInput.c.
References dieIfNotRead(), locateNamelistInputItem(), NamelistInputItemStruct::ptr, STRING_TYPE, and NamelistInputItemStruct::type.
Referenced by main().
newNamelistInputs()
NamelistInputs * newNamelistInputs (void)
Definition at line 72 of file namelistInput.c.
References NamelistInputsStruct::count, NamelistInputsStruct::head, newNamelistInputItem(), and NamelistInputsStruct::tail.
Referenced by main().
readNamelistInputs()
void readNamelistInputs (NamelistInputs * namelistInputs, const char * fileName)
Definition at line 119 of file namelistInput.c.
References DOUBLE_TYPE, INT_TYPE, locateNamelistInputItem(), LONG_TYPE, NamelistInputItemStruct::maxlen, openFile(), NamelistInputItemStruct::ptr, SEPARATORS, STRING_TYPE, stripComment(), NamelistInputItemStruct::type, and NamelistInputItemStruct::wasRead.
Referenced by main().