SIPNET: subsetData.c File Reference
subsetData.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "util.h"
#include "namelistInput.h"
Macros
#define NAMELIST_FILE "subset.in"
#define MAX_LINE 1024
#define MAX_FILENAME 256
#define MAX_NAME 64
Enumerations
enum AGGREGATION_TYPES { NO_AGGREGATION , DAILY_AGGREGATION }
Functions
void checkStatus (char *status, char *message)
char * readClimLine (FILE *f, char *line, int maxLength, int *loc, int *year, int *day)
void checkLocations (FILE *climFin)
int pastStart (int year, int day, int startYear, int startDay)
void gotoStart (FILE *climFin, FILE *dataFin, FILE *validFin, FILE *sigmaFin, int *startYear, int *startDay)
void copySubset (FILE *climFin, FILE *dataFin, FILE *validFin, FILE *sigmaFin, FILE *climFout, FILE *dataFout, FILE *validFout, FILE *sigmaFout, FILE *spdFout, FILE *aggFout, int aggType, int startYear, int startDay, int numDays)
void copyFile (char *inFilename, char *outFilename)
void copyOtherFiles (char *inFilename, char *outFilename)
int main (int argc, char *argv[])
Macro Definition Documentation
MAX_FILENAME
#define MAX_FILENAME 256
Definition at line 31 of file subsetData.c.
MAX_LINE
#define MAX_LINE 1024
Definition at line 30 of file subsetData.c.
MAX_NAME
#define MAX_NAME 64
Definition at line 32 of file subsetData.c.
NAMELIST_FILE
#define NAMELIST_FILE "subset.in"
Definition at line 29 of file subsetData.c.
Enumeration Type Documentation
AGGREGATION_TYPES
enum AGGREGATION_TYPES
Enumerator
NO_AGGREGATION
DAILY_AGGREGATION
Definition at line 35 of file subsetData.c.
Function Documentation
checkLocations()
void checkLocations (FILE * climFin)
Definition at line 69 of file subsetData.c.
References day, exit(), index, MAX_LINE, readClimLine(), and year.
Referenced by main().
checkStatus()
void checkStatus (char * status, char * message)
Definition at line 39 of file subsetData.c.
References exit(), and index.
Referenced by copySubset(), and gotoStart().
copyFile()
void copyFile (char * inFilename, char * outFilename)
Definition at line 286 of file subsetData.c.
References fclose(), index, and openFile().
Referenced by copyOtherFiles().
copyOtherFiles()
void copyOtherFiles (char * inFilename, char * outFilename)
Definition at line 304 of file subsetData.c.
References copyFile(), and index.
Referenced by main().
copySubset()
void copySubset (FILE * climFin, FILE * dataFin, FILE * validFin, FILE * sigmaFin, FILE * climFout, FILE * dataFout, FILE * validFout, FILE * sigmaFout, FILE * spdFout, FILE * aggFout, int aggType, int startYear, int startDay, int numDays)
Definition at line 168 of file subsetData.c.
References checkStatus(), DAILY_AGGREGATION, day, exit(), fprintf(), index, MAX_LINE, ndays, NO_AGGREGATION, readClimLine(), and year.
Referenced by main().
gotoStart()
void gotoStart (FILE * climFin, FILE * dataFin, FILE * validFin, FILE * sigmaFin, int * startYear, int * startDay)
Definition at line 109 of file subsetData.c.
References checkStatus(), day, err, exit(), index, MAX_LINE, pastStart(), readClimLine(), and year.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 331 of file subsetData.c.
References addNamelistInputItem(), checkLocations(), copyOtherFiles(), copySubset(), DAILY_AGGREGATION, dieIfNotRead(), exit(), fclose(), gotoStart(), index, INT_TYPE, MAX_FILENAME, MAX_NAME, NAMELIST_FILE, newNamelistInputs(), NO_AGGREGATION, openFileExt(), readNamelistInputs(), strcmpIgnoreCase(), and STRING_TYPE.
pastStart()
int pastStart (int year, int day, int startYear, int startDay)
Definition at line 89 of file subsetData.c.
References day, and year.
Referenced by gotoStart().
readClimLine()
char * readClimLine (FILE * f, char * line, int maxLength, int * loc, int * year, int * day)
Definition at line 53 of file subsetData.c.
References day, f, index, and year.
Referenced by checkLocations(), copySubset(), and gotoStart().