SIPNET: ml-metrorun.c File Reference
ml-metrorun.c File Reference
#include <signal.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "sipnet.h"
#include "ml-metro.h"
#include "paramchange.h"
#include "util.h"
#include "spatialParams.h"
Macros
#define ADD_PERCENT 0.5
#define COMPARE_INDICES_FILE ""
#define FILE_FOR_AGG ""
#define UNAGGED_WEIGHT 0.0
#define NUM_CHAINS 10
#define ITER 375000
#define SCALE_FACTOR 1.0
#define LOC -1
#define NUM_RUNS 1
#define NUM_AT_ONCE 10000
#define PARAM_FILE ""
#define RANDOM_START 0
#define NUM_SPIN_UPS 125000
#define OPT_INDICES_FILE ""
#define VALID_FRAC
#define PARAM_WEIGHT 0.0
Functions
void usage (char *progName)
int initDataTypeIndices (int dataTypeIndices[])
int setDataTypeIndices (int dataTypeIndices[])
int parseDataTypeIndices (int dataTypeIndices[], char *argv[], int startPos, int argc)
void printDataTypeIndices (int dataTypeIndices[], int numDataTypes, FILE *filePtr)
int main (int argc, char *argv[])
Macro Definition Documentation
ADD_PERCENT
#define ADD_PERCENT 0.5
Definition at line 18 of file SIPNEToptsIn/ml-metrorun.c.
COMPARE_INDICES_FILE
#define COMPARE_INDICES_FILE ""
Definition at line 19 of file SIPNEToptsIn/ml-metrorun.c.
FILE_FOR_AGG
#define FILE_FOR_AGG ""
Definition at line 20 of file SIPNEToptsIn/ml-metrorun.c.
ITER
#define ITER 375000
Definition at line 23 of file SIPNEToptsIn/ml-metrorun.c.
LOC
#define LOC -1
Definition at line 25 of file SIPNEToptsIn/ml-metrorun.c.
NUM_AT_ONCE
#define NUM_AT_ONCE 10000
Definition at line 27 of file SIPNEToptsIn/ml-metrorun.c.
NUM_CHAINS
#define NUM_CHAINS 10
Definition at line 22 of file SIPNEToptsIn/ml-metrorun.c.
NUM_RUNS
#define NUM_RUNS 1
Definition at line 26 of file SIPNEToptsIn/ml-metrorun.c.
NUM_SPIN_UPS
#define NUM_SPIN_UPS 125000
Definition at line 30 of file SIPNEToptsIn/ml-metrorun.c.
OPT_INDICES_FILE
#define OPT_INDICES_FILE ""
Definition at line 31 of file SIPNEToptsIn/ml-metrorun.c.
PARAM_FILE
#define PARAM_FILE ""
Definition at line 28 of file SIPNEToptsIn/ml-metrorun.c.
PARAM_WEIGHT
#define PARAM_WEIGHT 0.0
Definition at line 33 of file SIPNEToptsIn/ml-metrorun.c.
RANDOM_START
#define RANDOM_START 0
Definition at line 29 of file SIPNEToptsIn/ml-metrorun.c.
SCALE_FACTOR
#define SCALE_FACTOR 1.0
Definition at line 24 of file SIPNEToptsIn/ml-metrorun.c.
UNAGGED_WEIGHT
#define UNAGGED_WEIGHT 0.0
Definition at line 21 of file SIPNEToptsIn/ml-metrorun.c.
VALID_FRAC
#define VALID_FRAC
Value:
                     0.5 /* fraction of data points which must be valid
                     to use data from a given time step */
Definition at line 32 of file SIPNEToptsIn/ml-metrorun.c.
Function Documentation
initDataTypeIndices()
int initDataTypeIndices (int dataTypeIndices[])
Definition at line 95 of file SIPNEToptsIn/ml-metrorun.c.
References i, and MAX_DATA_TYPES.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 230 of file SIPNEToptsIn/ml-metrorun.c.
References ADD_PERCENT, aggedDifference(), cleanupModel(), cleanupParamchange(), COMPARE_INDICES_FILE, deleteSpatialParams(), difference(), exit(), fclose(), FILE_FOR_AGG, fprintf(), index, initDataTypeIndices(), initModel(), ITER, LOC, MAX_DATA_TYPES, metropolis(), NUM_AT_ONCE, NUM_CHAINS, NUM_RUNS, NUM_SPIN_UPS, numLocs, openFile(), OPT_INDICES_FILE, PARAM_FILE, PARAM_WEIGHT, parseDataTypeIndices(), printDataTypeIndices(), printModelComponents(), RANDOM_START, readData(), readFileForAgg(), runModelNoOut(), SCALE_FACTOR, scaleFactor, seedRand(), UNAGGED_WEIGHT, unaggedWeight, usage(), VALID_FRAC, and writeBestSpatialParams().
parseDataTypeIndices()
int parseDataTypeIndices (int dataTypeIndices[], char * argv[], int startPos, int argc)
Definition at line 167 of file SIPNEToptsIn/ml-metrorun.c.
References exit(), i, index, MAX_DATA_TYPES, and usage().
Referenced by main().
printDataTypeIndices()
void printDataTypeIndices (int dataTypeIndices[], int numDataTypes, FILE * filePtr)
Definition at line 218 of file SIPNEToptsIn/ml-metrorun.c.
References fprintf(), getDataTypeNames(), i, and index.
Referenced by main().
setDataTypeIndices()
int setDataTypeIndices (int dataTypeIndices[])
Definition at line 110 of file SIPNEToptsIn/ml-metrorun.c.
References getDataTypeNames(), i, index, j, and MAX_DATA_TYPES.
usage()
void usage (char * progName)
Definition at line 36 of file SIPNEToptsIn/ml-metrorun.c.
References ADD_PERCENT, COMPARE_INDICES_FILE, FILE_FOR_AGG, getDataTypeNames(), i, ITER, LOC, MAX_DATA_TYPES, NUM_AT_ONCE, NUM_CHAINS, NUM_RUNS, NUM_SPIN_UPS, OPT_INDICES_FILE, PARAM_FILE, PARAM_WEIGHT, RANDOM_START, SCALE_FACTOR, UNAGGED_WEIGHT, and VALID_FRAC.
Referenced by main(), and parseDataTypeIndices().