SIPNET: utils.h File Reference
utils.h File Reference
#include <math.h>
#include <stdio.h>
Functions
int copyFile (char *src, char *dest)
int compareDoubles (double a, double b)
Function Documentation
compareDoubles()
int compareDoubles (double a, double b) extern inline
Definition at line 33 of file utils.h.
References index.
Referenced by checkFertilizationParams(), checkHarvestParams(), checkIrrigationParams(), checkOutput(), checkPlantingParams(), and checkTillageParams().
copyFile()
int copyFile (char * src, char * dest) extern inline
Definition at line 7 of file utils.h.
References fclose(), and index.