SIPNET: modisFPARqc.m File Reference
modisFPARqc.m File Reference
Functions
length(v ones ()
Termed good quality vQC (index)=0.8.*vQC(index)
Variables
function vQC
function JZ Modified
numCols =length(v{1})
v =char(v)
Test to see if good quality by checking bit index =find(bin2dec(v(:,1:2))==1)
Reduce factor
Termed not produced
Function Documentation
ones()
length(v ones () virtual
References first, and length().
vQC()
Termed good quality vQC (index) pure virtual
Variable Documentation
factor
Reduce factor
Definition at line 27 of file modisFPARqc.m.
index
Test user mask index =find(bin2dec(v(:,1:2))==1)
Definition at line 26 of file modisFPARqc.m.
Referenced by addNamelistInputItem(), addOutputItem(), addValueToMeanTracker(), aggedDifference(), aggregates(), allParamsInitialized(), allParamsRead(), assignArray(), buildFileName(), calcLightEff(), calcLightEff2(), calcLightEff3(), calcMaintenanceRespiration(), calcPrecip(), calcRootResp(), calculateFluxes(), checkAllRead(), checkEvent(), checkHarvestParams(), checkLocations(), checkOutput(), checkSpatialParam(), checkStatus(), checkTillageParams(), cleanupParamchange(), closeOutputItemFile(), compareDoubles(), computeAggedData(), copyFile(), copyFile(), copyOtherFiles(), copyOutputInfo(), copySubset(), countItems(), countLines(), deallocateMeanTracker(), deleteNamelistInputs(), deleteOutputItems(), deleteSpatialParams(), dieIfNotRead(), dieIfNotSet(), difference(), ensureAllocation(), ensureNonNegative(), ensureNonNegativeStocks(), evapSoilFluxes(), exit(), free2DArray(), freeClimateList(), freeOutputInfo(), getDataTypeNames(), getGpp(), getMeanTrackerMean(), getNumParameters(), getNumParamsRead(), getPossiblySpatial(), getSpatialParam(), getSpatialParamBest(), getSpatialParamGuess(), getSpatialParamKnob(), getSpatialParamMax(), getSpatialParamMin(), getSpatialParamSigma(), gotoStart(), initDataTypeIndices(), initEvents(), initializeOneSpatialParam(), initModel(), initModel(), initModel(), isChangeable(), isSpatial(), litterInputPool(), loadSpatialParams(), locateNamelistInputItem(), locateParam(), main(), main(), make2DArray(), make2DIntArray(), makeArray(), microbeGrowth(), microbeQualityEfficiency(), moisture(), moisture_bwb(), moisture_pm(), newMeanTracker(), newNamelistInputItem(), newNamelistInputs(), newOutputInfo(), newOutputItems(), newSingleOutputItem(), newSpatialParams(), newSpatialParams(), nextUnreadParam(), numlines(), openFile(), openFile(), openFile(), openFileExt(), openOutputItemFile(), outputHeader(), outputState(), outputStatecsv(), outputTranspose(), parseDataTypeIndices(), parseDataTypeSwitches(), parseSpdValue(), pastLeafGrowth(), potPsn(), printDataTypeIndices(), printModelComponents(), randm(), randomChangeableSpatialParam(), readChainInfo(), readClimData(), readClimLine(), readData(), readDataLine(), readFile(), readFileForAgg(), readGirdlingData(), readIndicesFile(), readItems(), readNamelistInputs(), readOneSpatialParam(), readOptions(), readParamData(), readSpatialParams(), readSpatialValues(), resetMeanTracker(), resetSpatialParams(), run(), runModelNoOut(), runModelOutput(), runModelOutput(), runTestMulti(), runTestSimple(), seedRand(), sensTest(), sensTest(), setAll(), setAllSpatialParamBests(), setDataTypeIndices(), setPossiblySpatial(), setSpatialParam(), setSpatialParamBest(), setSpatialParamKnob(), setupModel(), setupOutputItems(), simpleWaterFlow(), snowPack(), soilDegradation(), soilWaterFluxes(), strcmpIgnoreCase(), stripComment(), sumArray(), terminateOutputItemLines(), transSoilDrainage(), updateState(), updateTrackers(), usage(), valueSet(), vegResp(), vegResp2(), writeBestSpatialParams(), writeChainInfo(), writeChangeableParamInfo(), writeOutputItemLabels(), and writeOutputItemValues().
Modified
function JZ Modified
Definition at line 4 of file modisFPARqc.m.
numCols
numCols =length(v{1})
Definition at line 13 of file modisFPARqc.m.
produced
Termed not produced
Definition at line 29 of file modisFPARqc.m.
v
v =char(v)
Definition at line 18 of file modisFPARqc.m.
vQC
Do the opposite way and then transpose vQC
Initial value:
=modisFPARqc(v)
% Author: AB
Definition at line 1 of file modisFPARqc.m.