SIPNET: paramchange.h File Reference
paramchange.h File Reference
#include "spatialParams.h"
Data Structures
struct ChangeableParamInfo
struct OutputInfoStruct
Typedefs
typedef struct ChangeableParamInfo PInfo
typedef struct OutputInfoStruct OutputInfo
Functions
double difference (double *sigma, OutputInfo *outputInfo, int loc, SpatialParams *spatialParams, double paramWeight, void(*modelF)(double **, int, int *, SpatialParams *, int), int dataTypeIndices[], int numDataTypes, int costFunction, double dataTypeWeights[])
double aggedDifference (double *sigma, OutputInfo *outputInfo, int loc, SpatialParams *spatialParams, double paramWeight, void(*modelF)(double **, int, int *, SpatialParams *, int), int dataTypeIndices[], int numDataTypes, int costFunction, double dataTypeWeights[])
void aggregates (OutputInfo *outputInfo, double **model, int loc, int dataNum)
void readData (char *fileName, int dataTypeIndices[], int numDataTypes, int totNumDataTypes, int myNumLocs, int *steps, double validFrac, char *optIndicesFile, char *compareIndicesFile, FILE *outFile)
void readFileForAgg (char *fileForAgg, int numDataTypes, double myUnaggedWeight)
OutputInfo * newOutputInfo (int numDataTypes, int loc)
void copyOutputInfo (OutputInfo *out, OutputInfo *in)
void freeOutputInfo (OutputInfo *outputInfo, int numDataTypes)
void cleanupParamchange ()
Typedef Documentation
OutputInfo
typedef struct OutputInfoStruct OutputInfo
PInfo
typedef struct ChangeableParamInfo PInfo
Function Documentation
aggedDifference()
double aggedDifference (double * sigma, OutputInfo * outputInfo, int loc, SpatialParams * spatialParams, double paramWeight, void(*)(double **, int, int *, SpatialParams *, int) modelF, int dataTypeIndices[], int numDataTypes, int costFunction, double dataTypeWeights[])
Definition at line 352 of file paramchange.c.
References aggedData, aggedModel, aggregates(), aggSteps, computeAggedData(), copyOutputInfo(), data, endOpt, i, index, makeArray(), model, n, numAggSteps, startOpt, unaggedWeight, and valid.
Referenced by main().
aggregates()
void aggregates (OutputInfo * outputInfo, double ** model, int loc, int dataNum)
Definition at line 438 of file paramchange.c.
References aggInfo, data, day, AggregateInfoStruct::endPt, i, index, j, makeArray(), model, AggregateInfoStruct::numDays, AggregateInfoStruct::spd, AggregateInfoStruct::startDay, AggregateInfoStruct::startPt, AggregateInfoStruct::startYear, sum(), and year.
Referenced by aggedDifference(), and difference().
cleanupParamchange()
void cleanupParamchange ()
Definition at line 968 of file paramchange.c.
References aggedData, aggedModel, aggInfo, aggSteps, data, endOpt, free2DArray(), index, model, numAggSteps, numLocs, sigmas, startOpt, and valid.
Referenced by main().
copyOutputInfo()
void copyOutputInfo (OutputInfo * out, OutputInfo * in)
Definition at line 945 of file paramchange.c.
References OutputInfoStruct::daysError, i, index, OutputInfoStruct::meanError, OutputInfoStruct::numYears, and OutputInfoStruct::years.
Referenced by aggedDifference().
difference()
double difference (double * sigma, OutputInfo * outputInfo, int loc, SpatialParams * spatialParams, double paramWeight, void(*)(double **, int, int *, SpatialParams *, int) modelF, int dataTypeIndices[], int numDataTypes, int costFunction, double dataTypeWeights[])
Definition at line 74 of file paramchange.c.
References aggregates(), data, endOpt, i, index, makeArray(), model, n, sigmas, startOpt, and valid.
Referenced by main().
freeOutputInfo()
void freeOutputInfo (OutputInfo * outputInfo, int numDataTypes)
Definition at line 957 of file paramchange.c.
References i, index, and years.
Referenced by main(), and metropolis().
newOutputInfo()
OutputInfo * newOutputInfo (int numDataTypes, int loc)
Definition at line 929 of file paramchange.c.
References aggInfo, i, index, makeArray(), AggregateInfoStruct::numDays, and years.
Referenced by main(), and metropolis().
readData()
void readData (char * fileName, int dataTypeIndices[], int numDataTypes, int totNumDataTypes, int myNumLocs, int * steps, double validFrac, char * optIndicesFile, char * compareIndicesFile, FILE * outFile)
Definition at line 627 of file paramchange.c.
References aggInfo, count, countLines(), data, endOpt, AggregateInfoStruct::endPt, exit(), fclose(), fileName, fprintf(), i, index, make2DArray(), make2DIntArray(), makeArray(), model, AggregateInfoStruct::numDays, numLocs, openFile(), parseSpdValue(), readDataLine(), readIndicesFile(), sigmas, AggregateInfoStruct::spd, AggregateInfoStruct::startDay, startOpt, AggregateInfoStruct::startPt, AggregateInfoStruct::startYear, valid, and year.
Referenced by main().
readFileForAgg()
void readFileForAgg (char * fileForAgg, int numDataTypes, double myUnaggedWeight)
Definition at line 873 of file paramchange.c.
References aggedData, aggedModel, aggSteps, computeAggedData(), count, data, endOpt, exit(), f, fclose(), i, index, make2DArray(), numAggSteps, numLocs, openFile(), startOpt, sum(), and unaggedWeight.
Referenced by main().