SIPNET: ml-metro5.c File Reference
ml-metro5.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <float.h>
#include "paramchange.h"
#include "spatialParams.h"
#include "util.h"
Macros
#define A_STAR 0.4
#define DEC 0.99
#define THRESH 0.02
Functions
void writeHistFileHeader (FILE *histFile, int numYears, int np, int numDataTypes)
void writeHistFile (FILE *histFile, double ltotnew, double *sigma, OutputInfo *outputInfo, int numDataTypes, SpatialParams *spatialParams, int loc)
void writeHistFileBinHeader (FILE *histFile, int numYears, int np, int numDataTypes)
void writeDoubleAsFloat (double num, FILE *outfile)
void writeHistFileBin (FILE *histFile, double ltotnew, double *sigma, OutputInfo *outputInfo, int numDataTypes, SpatialParams *spatialParams, int loc)
void reset (SpatialParams *spatialParams, double *loglikely, double *ltotnew, double *ltotold, double *ltotmax, double **sigma, OutputInfo **outputInfo, int loc, int randomStart, double addFraction, FILE *userOut, double(*likely)(double *, OutputInfo *, int, SpatialParams *, double, void(*)(double **, int, int *, SpatialParams *, int), int[], int, int, double[]), double paramWeight, void(*model)(double **, int, int *, SpatialParams *, int), int dataTypeIndices[], int numDataTypes, int costFunction, double dataTypeWeights[])
void writeChainInfo (char *chainInfo, double ltotold, double ltotmax, SpatialParams *spatialParams, int loc)
void readChainInfo (char *chainInfo, double *ltotold, double *ltotmax, SpatialParams *spatialParams, int loc)
void metropolis (char *outNameBase, SpatialParams *spatialParams, int loc, double(*likely)(double *, OutputInfo *, int, SpatialParams *, double, void(*)(double **, int, int *, SpatialParams *, int), int[], int, int, double[]), void(*model)(double **, int, int *, SpatialParams *, int), double addFraction, long estSteps, int numAtOnce, int numChains, int randomStart, long numSpinUps, double paramWeight, double scaleFactor, int dataTypeIndices[], int numDataTypes, int costFunction, double dataTypeWeights[], FILE *userOut)
Macro Definition Documentation
A_STAR
#define A_STAR 0.4
Definition at line 16 of file ml-metro5.c.
DEC
#define DEC 0.99
Definition at line 17 of file ml-metro5.c.
THRESH
#define THRESH 0.02
Definition at line 18 of file ml-metro5.c.
Function Documentation
metropolis()
void metropolis (char * outNameBase, SpatialParams * spatialParams, int loc, double(*)(double *, OutputInfo *, int, SpatialParams *, double, void(*)(double **, int, int *, SpatialParams *, int), int[], int, int, double[]) likely, void(*)(double **, int, int *, SpatialParams *, int) model, double addFraction, long estSteps, int numAtOnce, int numChains, int randomStart, long numSpinUps, double paramWeight, double scaleFactor, int dataTypeIndices[], int numDataTypes, int costFunction, double dataTypeWeights[], FILE * userOut)
Definition at line 301 of file ml-metro5.c.
References A_STAR, checkSpatialParam(), DEC, fclose(), fprintf(), free2DArray(), freeOutputInfo(), getSpatialParam(), getSpatialParamKnob(), getSpatialParamMax(), getSpatialParamMin(), isSpatial(), k, make2DArray(), makeArray(), model, newOutputInfo(), SpatialParamsStruct::numChangeableParams, numLocs, SpatialParamsStruct::numLocs, openFile(), randm(), randomChangeableSpatialParam(), readChainInfo(), reset(), scaleFactor, setAllSpatialParamBests(), setSpatialParam(), setSpatialParamKnob(), sumArray(), THRESH, writeChainInfo(), writeChangeableParamInfo(), writeHistFileBin(), and writeHistFileBinHeader().
Referenced by main().
readChainInfo()
void readChainInfo (char * chainInfo, double * ltotold, double * ltotmax, SpatialParams * spatialParams, int loc)
Definition at line 239 of file ml-metro5.c.
References SpatialParamsStruct::changeableParamIndices, fclose(), i, index, isSpatial(), SpatialParamsStruct::numChangeableParams, SpatialParamsStruct::numLocs, openFile(), setSpatialParam(), setSpatialParamBest(), setSpatialParamKnob(), and value.
Referenced by metropolis().
reset()
void reset (SpatialParams * spatialParams, double * loglikely, double * ltotnew, double * ltotold, double * ltotmax, double ** sigma, OutputInfo ** outputInfo, int loc, int randomStart, double addFraction, FILE * userOut, double(*)(double *, OutputInfo *, int, SpatialParams *, double, void(*)(double **, int, int *, SpatialParams *, int), int[], int, int, double[]) likely, double paramWeight, void(*)(double **, int, int *, SpatialParams *, int) model, int dataTypeIndices[], int numDataTypes, int costFunction, double dataTypeWeights[])
Definition at line 126 of file ml-metro5.c.
References fprintf(), model, SpatialParamsStruct::numLocs, resetSpatialParams(), sumArray(), and writeChangeableParamInfo().
Referenced by metropolis().
writeChainInfo()
void writeChainInfo (char * chainInfo, double ltotold, double ltotmax, SpatialParams * spatialParams, int loc)
Definition at line 178 of file ml-metro5.c.
References SpatialParamsStruct::changeableParamIndices, fclose(), getSpatialParam(), getSpatialParamBest(), getSpatialParamKnob(), i, index, isSpatial(), SpatialParamsStruct::numChangeableParams, SpatialParamsStruct::numLocs, openFile(), and value.
Referenced by metropolis().
writeDoubleAsFloat()
void writeDoubleAsFloat (double num, FILE * outfile)
Definition at line 75 of file ml-metro5.c.
Referenced by writeHistFileBin().
writeHistFile()
void writeHistFile (FILE * histFile, double ltotnew, double * sigma, OutputInfo * outputInfo, int numDataTypes, SpatialParams * spatialParams, int loc)
Definition at line 31 of file ml-metro5.c.
References SpatialParamsStruct::changeableParamIndices, fprintf(), getSpatialParam(), i, j, SpatialParamsStruct::numChangeableParams, OutputInfoStruct::numYears, and years.
writeHistFileBin()
void writeHistFileBin (FILE * histFile, double ltotnew, double * sigma, OutputInfo * outputInfo, int numDataTypes, SpatialParams * spatialParams, int loc)
Definition at line 84 of file ml-metro5.c.
References SpatialParamsStruct::changeableParamIndices, getSpatialParam(), i, j, SpatialParamsStruct::numChangeableParams, OutputInfoStruct::numYears, writeDoubleAsFloat(), and years.
Referenced by metropolis().
writeHistFileBinHeader()
void writeHistFileBinHeader (FILE * histFile, int numYears, int np, int numDataTypes)
Definition at line 61 of file ml-metro5.c.
Referenced by metropolis().
writeHistFileHeader()
void writeHistFileHeader (FILE * histFile, int numYears, int np, int numDataTypes)
Definition at line 22 of file ml-metro5.c.
References fprintf().