SIPNET: spatialParams.c File Reference
spatialParams.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include "spatialParams.h"
#include "util.h"
Functions
int allParamsInitialized (SpatialParams *spatialParams)
void setAll (double *array, int length, double value)
void checkAllRead (SpatialParams *spatialParams)
double getPossiblySpatial (double *array, int loc, int isSpatial)
void setPossiblySpatial (double *array, int loc, double value, int isSpatial, int length)
void readSpatialValues (double *spatialValues, FILE *spatialParamFile, char pName[PARAM_MAXNAME], int numLocs)
SpatialParams * newSpatialParams (int maxParameters, int numLocs)
void initializeOneSpatialParam (SpatialParams *spatialParams, char *name, double *externalLoc, int isRequired)
void readSpatialParams (SpatialParams *spatialParams, FILE *paramFile, FILE *spatialParamFile)
int getNumParameters (SpatialParams *spatialParams)
int getNumParamsRead (SpatialParams *spatialParams)
int locateParam (SpatialParams *spatialParams, char *name)
int valueSet (SpatialParams *spatialParams, int i)
int isSpatial (SpatialParams *spatialParams, int i)
int isChangeable (SpatialParams *spatialParams, int i)
int checkSpatialParam (SpatialParams *spatialParams, int i, double value)
double getSpatialParam (SpatialParams *spatialParams, int i, int loc)
void setSpatialParam (SpatialParams *spatialParams, int i, int loc, double value)
double getSpatialParamGuess (SpatialParams *spatialParams, int i, int loc)
double getSpatialParamMin (SpatialParams *spatialParams, int i)
double getSpatialParamMax (SpatialParams *spatialParams, int i)
double getSpatialParamSigma (SpatialParams *spatialParams, int i)
double getSpatialParamKnob (SpatialParams *spatialParams, int i, int loc)
void setSpatialParamKnob (SpatialParams *spatialParams, int i, int loc, double value)
double getSpatialParamBest (SpatialParams *spatialParams, int i, int loc)
void setSpatialParamBest (SpatialParams *spatialParams, int i, int loc, double value)
void setAllSpatialParamBests (SpatialParams *spatialParams, int loc)
int randomChangeableSpatialParam (SpatialParams *spatialParams)
void loadSpatialParams (SpatialParams *spatialParams, int loc)
void resetSpatialParams (SpatialParams *spatialParams, double knob, int randomReset)
void writeBestSpatialParams (SpatialParams *spatialParams, char *paramFile, char *spatialParamFile)
void writeChangeableParamInfo (SpatialParams *spatialParams, int loc, FILE *outF)
void deleteSpatialParams (SpatialParams *spatialParams)
Function Documentation
allParamsInitialized()
int allParamsInitialized (SpatialParams * spatialParams)
Definition at line 19 of file spatialParams.c.
References index.
Referenced by initializeOneSpatialParam().
checkAllRead()
void checkAllRead (SpatialParams * spatialParams)
Definition at line 39 of file spatialParams.c.
References exit(), i, and index.
Referenced by readSpatialParams().
checkSpatialParam()
int checkSpatialParam (SpatialParams * spatialParams, int i, double value)
Definition at line 380 of file spatialParams.c.
References getSpatialParamMax(), getSpatialParamMin(), i, index, and value.
deleteSpatialParams()
void deleteSpatialParams (SpatialParams * spatialParams)
Definition at line 675 of file spatialParams.c.
References i, and index.
getNumParameters()
int getNumParameters (SpatialParams * spatialParams)
Definition at line 321 of file spatialParams.c.
References index.
getNumParamsRead()
int getNumParamsRead (SpatialParams * spatialParams)
Definition at line 327 of file spatialParams.c.
References index.
Referenced by writeBestSpatialParams(), and writeChangeableParamInfo().
getPossiblySpatial()
double getPossiblySpatial (double * array, int loc, int isSpatial)
Definition at line 66 of file spatialParams.c.
References index, and isSpatial().
Referenced by getSpatialParam(), getSpatialParamBest(), getSpatialParamGuess(), and getSpatialParamKnob().
getSpatialParam()
double getSpatialParam (SpatialParams * spatialParams, int i, int loc)
Definition at line 389 of file spatialParams.c.
References getPossiblySpatial(), i, index, and isSpatial().
Referenced by loadSpatialParams(), setAllSpatialParamBests(), and writeChangeableParamInfo().
getSpatialParamBest()
double getSpatialParamBest (SpatialParams * spatialParams, int i, int loc)
Definition at line 462 of file spatialParams.c.
References getPossiblySpatial(), i, index, and isSpatial().
Referenced by writeBestSpatialParams(), and writeChangeableParamInfo().
getSpatialParamGuess()
double getSpatialParamGuess (SpatialParams * spatialParams, int i, int loc)
Definition at line 409 of file spatialParams.c.
References getPossiblySpatial(), i, index, and isSpatial().
Referenced by resetSpatialParams(), and writeChangeableParamInfo().
getSpatialParamKnob()
double getSpatialParamKnob (SpatialParams * spatialParams, int i, int loc)
Definition at line 442 of file spatialParams.c.
References getPossiblySpatial(), i, index, and isSpatial().
Referenced by writeChangeableParamInfo().
getSpatialParamMax()
double getSpatialParamMax (SpatialParams * spatialParams, int i)
Definition at line 425 of file spatialParams.c.
References i, and index.
Referenced by checkSpatialParam(), resetSpatialParams(), writeBestSpatialParams(), and writeChangeableParamInfo().
getSpatialParamMin()
double getSpatialParamMin (SpatialParams * spatialParams, int i)
Definition at line 417 of file spatialParams.c.
References i, and index.
Referenced by checkSpatialParam(), resetSpatialParams(), writeBestSpatialParams(), and writeChangeableParamInfo().
getSpatialParamSigma()
double getSpatialParamSigma (SpatialParams * spatialParams, int i)
Definition at line 433 of file spatialParams.c.
References i, and index.
Referenced by writeBestSpatialParams().
initializeOneSpatialParam()
void initializeOneSpatialParam (SpatialParams * spatialParams, char * name, double * externalLoc, int isRequired)
Definition at line 156 of file spatialParams.c.
References allParamsInitialized(), exit(), index, and name.
Referenced by readParamData().
isChangeable()
int isChangeable (SpatialParams * spatialParams, int i)
Definition at line 372 of file spatialParams.c.
References i, and index.
Referenced by resetSpatialParams(), writeBestSpatialParams(), and writeChangeableParamInfo().
isSpatial()
int isSpatial (SpatialParams * spatialParams, int i)
Definition at line 364 of file spatialParams.c.
References i, and index.
Referenced by getPossiblySpatial(), getSpatialParam(), getSpatialParamBest(), getSpatialParamGuess(), getSpatialParamKnob(), resetSpatialParams(), setAllSpatialParamBests(), setPossiblySpatial(), setSpatialParam(), setSpatialParamBest(), setSpatialParamKnob(), writeBestSpatialParams(), and writeChangeableParamInfo().
loadSpatialParams()
void loadSpatialParams (SpatialParams * spatialParams, int loc)
Definition at line 533 of file spatialParams.c.
References getSpatialParam(), i, index, value, and valueSet().
locateParam()
int locateParam (SpatialParams * spatialParams, char * name)
Definition at line 334 of file spatialParams.c.
References i, index, name, and strcmpIgnoreCase().
Referenced by main(), and readSpatialParams().
newSpatialParams()
SpatialParams * newSpatialParams (int maxParameters, int numLocs)
Definition at line 131 of file spatialParams.c.
References index, SpatialParamsStruct::maxParameters, and numLocs.
randomChangeableSpatialParam()
int randomChangeableSpatialParam (SpatialParams * spatialParams)
Definition at line 516 of file spatialParams.c.
References index.
readSpatialParams()
void readSpatialParams (SpatialParams * spatialParams, FILE * paramFile, FILE * spatialParamFile)
Definition at line 200 of file spatialParams.c.
References checkAllRead(), exit(), i, index, locateParam(), min(), numLocs, PARAM_MAXNAME, readSpatialValues(), SEPARATORS, stripComment(), value, and valueSet().
Referenced by readParamData().
readSpatialValues()
void readSpatialValues (double * spatialValues, FILE * spatialParamFile, char pName[PARAM_MAXNAME], int numLocs)
Definition at line 97 of file spatialParams.c.
References exit(), i, index, numLocs, PARAM_MAXNAME, and strcmpIgnoreCase().
Referenced by readSpatialParams().
resetSpatialParams()
void resetSpatialParams (SpatialParams * spatialParams, double knob, int randomReset)
Definition at line 556 of file spatialParams.c.
References getSpatialParamGuess(), getSpatialParamMax(), getSpatialParamMin(), i, index, isChangeable(), isSpatial(), numLocs, setSpatialParam(), setSpatialParamBest(), setSpatialParamKnob(), value, and valueSet().
setAll()
void setAll (double * array, int length, double value)
Definition at line 28 of file spatialParams.c.
References i, index, length(), and value.
Referenced by setPossiblySpatial().
setAllSpatialParamBests()
void setAllSpatialParamBests (SpatialParams * spatialParams, int loc)
Definition at line 482 of file spatialParams.c.
References getSpatialParam(), i, index, isSpatial(), setSpatialParamBest(), value, and valueSet().
setPossiblySpatial()
void setPossiblySpatial (double * array, int loc, double value, int isSpatial, int length)
Definition at line 78 of file spatialParams.c.
References index, isSpatial(), length(), setAll(), and value.
Referenced by setSpatialParam(), setSpatialParamBest(), and setSpatialParamKnob().
setSpatialParam()
void setSpatialParam (SpatialParams * spatialParams, int i, int loc, double value)
Definition at line 400 of file spatialParams.c.
References i, index, isSpatial(), setPossiblySpatial(), and value.
Referenced by resetSpatialParams().
setSpatialParamBest()
void setSpatialParamBest (SpatialParams * spatialParams, int i, int loc, double value)
Definition at line 473 of file spatialParams.c.
References i, index, isSpatial(), setPossiblySpatial(), and value.
Referenced by resetSpatialParams(), and setAllSpatialParamBests().
setSpatialParamKnob()
void setSpatialParamKnob (SpatialParams * spatialParams, int i, int loc, double value)
Definition at line 453 of file spatialParams.c.
References i, index, isSpatial(), setPossiblySpatial(), and value.
Referenced by resetSpatialParams().
valueSet()
int valueSet (SpatialParams * spatialParams, int i)
Definition at line 355 of file spatialParams.c.
References i, and index.
Referenced by loadSpatialParams(), readSpatialParams(), resetSpatialParams(), and setAllSpatialParamBests().
writeBestSpatialParams()
void writeBestSpatialParams (SpatialParams * spatialParams, char * paramFile, char * spatialParamFile)
Definition at line 599 of file spatialParams.c.
References fclose(), fprintf(), getNumParamsRead(), getSpatialParamBest(), getSpatialParamMax(), getSpatialParamMin(), getSpatialParamSigma(), i, index, isChangeable(), isSpatial(), j, numLocs, and openFile().
writeChangeableParamInfo()
void writeChangeableParamInfo (SpatialParams * spatialParams, int loc, FILE * outF)
Definition at line 640 of file spatialParams.c.
References count, fprintf(), getNumParamsRead(), getSpatialParam(), getSpatialParamBest(), getSpatialParamGuess(), getSpatialParamKnob(), getSpatialParamMax(), getSpatialParamMin(), i, index, isChangeable(), and isSpatial().