SIPNET: neefill.m File Reference
neefill.m File Reference
Functions
nee (1:end-1)]
NIGHTTIME NEE (NIGHTTIME RESP) wg =find(~isnan(nee) & ustar>0.25 & potpar==0)
respmod (1)
respmod (i)
neefill (wb)
sigfill (wg)=0.0
id ascii ()
par (find(potpar==0))=0
'data/timeyears' load ()
Variables
nee =nangap(load('data/nee'))
tair =load('data/tairfill')
vpd =load('data/vpdfill')
tsoil =load('data/tsoilfill')
par =load('data/parfill')
ustar =load('data/ustarfill')
fh2o =load('data/fh2ofill')
wspd =load('data/wspdfill')
wdir =load('data/wdirfill')
year =load('data/year')
potpar =load('data/potpar')
hour =load('data/hourofday')
day =load('data/dayofyear')
shour =sin(2*pi*hour/24.)
chour =cos(2*pi*hour/24.)
sday =sin(2*pi*(day-1)/365.25)
cday =cos(2*pi*(day-1)/365.25)
neem1 =[NaN
p =[shour chour sday cday tair vpd tsoil fh2o wspd wdir]
pj =[shour(1) chour(1) sday(1) cday(1) tair(1) vpd(1) tsoil(1) fh2o(1) 0.0 wspd(1) wdir(1)]
for i
end neefill =nee
sigfill =sigmod
err =nee-neemod
wg =find(~isnan(nee) & ~isnan(neem1) & ustar>0.2)
wb =find(isnan(nee) | isnan(neem1) | ustar<=0.2)
pg =[hour(wg) day(wg) tair(wg) par(wg) vpd(wg) tsoil(wg) neem1(wg)]
tg =nee(wg)
R2
n =length(err)
i001 =fix(0.001*n)
i999 =fix(0.999*n)
f =find(sorterr>sorterr(i001) & sorterr<sorterr(i999))
tg2 =tg(isorterr(f))
pg2 =pg(isorterr(f),:)
R __pad0__ =nnregress(pg,tg,7,1.,1)
wg2 =find(~isnan(nee) & ustar>0.2 & timeyears>=1997.0)
Function Documentation
ascii()
id ascii () virtual
References data.
load()
'data/timeyears' load () virtual
References data.
nee()
nee (1:end- 1)
NEE()
NIGHTTIME NEE (NIGHTTIME RESP) =find(~isnan(nee) & ustar>0.25 & potpar==0)
neefill()
neefill (wb)
par()
par (find(potpar==0)) pure virtual
respmod() [1/2]
respmod (1)
respmod() [2/2]
respmod (i)
sigfill()
sigfill (wg) pure virtual
Variable Documentation
__pad0__
R __pad0__ =nnregress(pg,tg,7,1.,1)
Definition at line 111 of file neefill.m.
cday
cday =cos(2*pi*(day-1)/365.25)
Definition at line 20 of file neefill.m.
chour
chour =cos(2*pi*hour/24.)
Definition at line 18 of file neefill.m.
day
day =load('data/dayofyear')
Definition at line 15 of file neefill.m.
err
SCREEN OUTLINERS err =nee-neemod
Definition at line 52 of file neefill.m.
Referenced by calcLightEff(), gotoStart(), and updateState().
f
f =find(sorterr>sorterr(i001) & sorterr<sorterr(i999))
Definition at line 86 of file neefill.m.
Referenced by countLines(), main(), numlines(), openFile(), openFile(), openFile(), openFileExt(), outputTranspose(), readClimLine(), readFile(), and readFileForAgg().
fh2o
Bill Sacks Modified function and take fh2o =load('data/fh2ofill')
Definition at line 8 of file neefill.m.
hour
hour =load('data/hourofday')
Definition at line 14 of file neefill.m.
i
for i
Initial value:
=2:length(nee)
        pj=[shour(i) chour(i) sday(i) cday(i) tair(i) vpd(i) tsoil(i) fh2o(i) respmod(i-1) wspd(i) wdir(i)]
Definition at line 41 of file neefill.m.
i001
i001 =fix(0.001*n)
Definition at line 84 of file neefill.m.
i999
i999 =fix(0.999*n)
Definition at line 85 of file neefill.m.
n
the measured points in this step n =length(err)
Definition at line 83 of file neefill.m.
Referenced by aggedDifference(), assignArray(), countItems(), and difference().
nee
nee =nangap(load('data/nee'))
Definition at line 2 of file neefill.m.
neefill
neefill =nee
Definition at line 47 of file neefill.m.
neem1
neem1 =[NaN
Definition at line 22 of file neefill.m.
p
p =[shour chour sday cday tair vpd tsoil fh2o wspd wdir]
Definition at line 26 of file neefill.m.
par
par =load('data/parfill')
Definition at line 6 of file neefill.m.
pg
pg =[hour(wg) day(wg) tair(wg) par(wg) vpd(wg) tsoil(wg) neem1(wg)]
Definition at line 69 of file neefill.m.
pg2
pg2 =pg(isorterr(f),:)
Definition at line 88 of file neefill.m.
pj
pj =[shour(1) chour(1) sday(1) cday(1) tair(1) vpd(1) tsoil(1) fh2o(1) 0.0 wspd(1) wdir(1)]
Definition at line 39 of file neefill.m.
potpar
potpar =load('data/potpar')
Definition at line 13 of file neefill.m.
R2
R2
Initial value:
=0.881
p=[hour day tair par vpd tsoil neem1]
Definition at line 71 of file neefill.m.
sday
sday =sin(2*pi*(day-1)/365.25)
Definition at line 19 of file neefill.m.
shour
shour =sin(2*pi*hour/24.)
Definition at line 17 of file neefill.m.
sigfill
sigfill =sigmod
Definition at line 49 of file neefill.m.
tair
tair =load('data/tairfill')
Definition at line 3 of file neefill.m.
tg
tg =nee(wg)
Definition at line 70 of file neefill.m.
tg2
tg2 =tg(isorterr(f))
Definition at line 87 of file neefill.m.
tsoil
tsoil =load('data/tsoilfill')
Definition at line 5 of file neefill.m.
ustar
ustar =load('data/ustarfill')
Definition at line 7 of file neefill.m.
vpd
vpd =load('data/vpdfill')
Definition at line 4 of file neefill.m.
wb
wb =find(isnan(nee) | isnan(neem1) | ustar<=0.2)
Definition at line 68 of file neefill.m.
wdir
wdir =load('data/wdirfill')
Definition at line 10 of file neefill.m.
wg
wg =find(~isnan(nee) & ~isnan(neem1) & ustar>0.2)
Definition at line 67 of file neefill.m.
wg2
wg2 =find(~isnan(nee) & ustar>0.2 & timeyears>=1997.0)
Definition at line 114 of file neefill.m.
wspd
wspd =load('data/wspdfill')
Definition at line 9 of file neefill.m.
Referenced by main(), and readClimData().
year
year =load('data/year')
Definition at line 11 of file neefill.m.
Referenced by aggregates(), checkEvent(), checkLocations(), copySubset(), createEventNode(), gotoStart(), if(), main(), outputState(), outputStatecsv(), pastStart(), printEvent(), readClimData(), readClimLine(), readData(), readEventData(), year(), years(), and years().