SIPNET: sensTestFull.c File Reference
sensTestFull.c File Reference
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "sipnet.h"
#include "paramchange.h"
#include "util.h"
#include "spatialParams.h"
Macros
#define FILE_FOR_AGG ""
#define UNAGGED_WEIGHT 0.0
#define LOC 0
#define PARAM_FILE ""
#define OPT_INDICES_FILE ""
#define VALID_FRAC
#define NUM_PARAMS 84
Functions
void usage (char *progName)
int initDataTypeIndices (int dataTypeIndices[])
int parseDataTypeIndices (int dataTypeIndices[], char *argv[], int startPos, int argc)
int main (int argc, char *argv[])
Macro Definition Documentation
FILE_FOR_AGG
#define FILE_FOR_AGG ""
Definition at line 21 of file sensTestFull.c.
LOC
#define LOC 0
Definition at line 23 of file sensTestFull.c.
NUM_PARAMS
#define NUM_PARAMS 84
Definition at line 28 of file sensTestFull.c.
OPT_INDICES_FILE
#define OPT_INDICES_FILE ""
Definition at line 25 of file sensTestFull.c.
PARAM_FILE
#define PARAM_FILE ""
Definition at line 24 of file sensTestFull.c.
UNAGGED_WEIGHT
#define UNAGGED_WEIGHT 0.0
Definition at line 22 of file sensTestFull.c.
VALID_FRAC
#define VALID_FRAC
Value:
                     0.5 /* fraction of data points which must be valid
                     to use data from a given time step */
Definition at line 26 of file sensTestFull.c.
Function Documentation
initDataTypeIndices()
int initDataTypeIndices (int dataTypeIndices[])
Definition at line 69 of file sensTestFull.c.
References i, index, and MAX_DATA_TYPES.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 138 of file sensTestFull.c.
References aggedDifference(), cleanupModel(), cleanupParamchange(), deleteSpatialParams(), difference(), exit(), fclose(), FILE_FOR_AGG, fileName, fprintf(), freeOutputInfo(), getSpatialParamMax(), getSpatialParamMin(), index, initDataTypeIndices(), initModel(), LOC, makeArray(), MAX_DATA_TYPES, newOutputInfo(), NUM_PARAMS, numLocs, openFile(), OPT_INDICES_FILE, PARAM_FILE, parseDataTypeIndices(), readData(), readFileForAgg(), runModelNoOut(), setSpatialParam(), UNAGGED_WEIGHT, unaggedWeight, usage(), and VALID_FRAC.
parseDataTypeIndices()
int parseDataTypeIndices (int dataTypeIndices[], char * argv[], int startPos, int argc)
Definition at line 87 of file sensTestFull.c.
References exit(), i, index, MAX_DATA_TYPES, and usage().
Referenced by main().
usage()
void usage (char * progName)
Definition at line 29 of file sensTestFull.c.
References FILE_FOR_AGG, getDataTypeNames(), i, index, LOC, MAX_DATA_TYPES, OPT_INDICES_FILE, PARAM_FILE, UNAGGED_WEIGHT, and VALID_FRAC.
Referenced by main(), and parseDataTypeIndices().