SIPNET: bintotxt.c File Reference
bintotxt.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
FILE * openFile (char *name, char *mode)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 21 of file bintotxt.c.
References exit(), fclose(), fprintf(), and openFile().
openFile()
FILE * openFile (char * name, char * mode)
Definition at line 9 of file bintotxt.c.
References exit(), f, and name.
Referenced by copyFile(), countLines(), main(), metropolis(), openOutputItemFile(), readChainInfo(), readClimData(), readData(), readEventData(), readFileForAgg(), readGirdlingData(), readIndicesFile(), readNamelistInputs(), readOptions(), readParamData(), writeBestSpatialParams(), and writeChainInfo().