SIPNET: modisTokenizeString.m File Reference
modisTokenizeString.m File Reference
Functions
tokenize and return the pixelValues First two tokens are just the long name and the modis followed by the time (in Ayyyyddd)
timeOut (1)
Variables
function [timeOut, elementName, pixelValues]
tokenize it
tokenize and return the pixelValues First two tokens are just the long name and the modis product
tokenize and return the pixelValues First two tokens are just the long name and the modis followed by the the site name
tokenize and return the pixelValues First two tokens are just the long name and the modis followed by the the site time it was analyzed
tokenize and return the pixelValues First two tokens are just the long name and the modis followed by the the site time it was the element and a element vector of results for generality
tokenize and return the pixelValues First two tokens are just the long name and the modis followed by the the site time it was the element and a element vector of results for the output will all be strings Out values
tokenize and return the pixelValues First two tokens are just the long name and the modis followed by the the site time it was the element and a element vector of results for the output will all be strings Out LAI
tokenize and return the pixelValues First two tokens are just the long name and the modis followed by the the site time it was the element and a element vector of results for the output will all be strings Out and their QC values pixelValues
Make a cellstring of values for pixels ignore the first two tokens [tok, stringIn] =strtok(stringIn,',')
assign time value [timeOut, stringIn] =strtok(stringIn,',')
Remove the A designation timeOut =str2num(timeOut)
Assign the element Name [elementName, stringIn] =strtok(stringIn,',')
for i
Function Documentation
time()
tokenize and return the pixelValues First two tokens are just the long name and the modis followed by the time (in Ayyyyddd)
timeOut()
timeOut (1)
Variable Documentation
analyzed
tokenize and return the pixelValues First two tokens are just the long name and the modis followed by the the site time it was analyzed
Definition at line 5 of file modisTokenizeString.m.
function
function[timeOut, elementName, pixelValues]
Initial value:
=modisTokenizeString(stringIn)
%%% Take a modis data string
Definition at line 1 of file modisTokenizeString.m.
generality
tokenize and return the pixelValues First two tokens are just the long name and the modis followed by the the site time it was the element and a element vector of results for generality
Definition at line 7 of file modisTokenizeString.m.
i
for i
Initial value:
= 1:49
        [pixelValues{i},stringIn]=strtok(stringIn,',')
Definition at line 32 of file modisTokenizeString.m.
it
tokenize it
Definition at line 3 of file modisTokenizeString.m.
LAI
tokenize and return the pixelValues First two tokens are just the long name and the modis followed by the the site time it was the element and a element vector of results for the output will all be strings Out LAI
Definition at line 11 of file modisTokenizeString.m.
name
tokenize and return the pixelValues First two tokens are just the long name and the modis followed by the the site time it was the element name
Definition at line 5 of file modisTokenizeString.m.
Referenced by addNamelistInputItem(), addOutputItem(), dieIfNotRead(), dieIfNotSet(), initializeOneSpatialParam(), locateNamelistInputItem(), locateParam(), newNamelistInputItem(), newSingleOutputItem(), openFile(), openFile(), openFile(), openFileExt(), and readOneSpatialParam().
Name
Assign the element Name[elementName, stringIn] =strtok(stringIn,',')
Definition at line 29 of file modisTokenizeString.m.
pixelValues
tokenize and return the pixelValues First two tokens are just the long name and the modis followed by the the site time it was the element and a element vector of results for the output will all be strings Out and their QC values pixelValues
Initial value:
= a cellstring of pixel values for the element analyzed
pixelValues=cellstr(char(zeros(49,1)))
Definition at line 12 of file modisTokenizeString.m.
product
tokenize and return the pixelValues First two tokens are just the long name and the modis product
Definition at line 4 of file modisTokenizeString.m.
timeOut
Remove the A designation timeOut =str2num(timeOut)
Definition at line 23 of file modisTokenizeString.m.
tokens
Convert to a number Ignore the next three tokens =strtok(stringIn,',')
Definition at line 16 of file modisTokenizeString.m.
value
assign time value[timeOut, stringIn] =strtok(stringIn,',')
Definition at line 20 of file modisTokenizeString.m.
Referenced by addValueToMeanTracker(), checkSpatialParam(), loadSpatialParams(), main(), readChainInfo(), readOneSpatialParam(), readSpatialParams(), resetSpatialParams(), sensTest(), sensTest(), setAll(), setAllSpatialParamBests(), setPossiblySpatial(), setSpatialParam(), setSpatialParamBest(), setSpatialParamKnob(), and writeChainInfo().
values
tokenize and return the pixelValues First two tokens are just the long name and the modis followed by the the site time it was the element and a element vector of results for the output will all be strings Out values
Definition at line 9 of file modisTokenizeString.m.