CC=gcc
LD=gcc
CFLAGS=-Wall -g
LDFLAGS=-L../../..
LDLIBS=-lsipnet -lm

# List test files in this directory here
TEST_CFILES=<c files in this directory containing tests> <<== CHANGE THIS

# The rest is boilerplate, likely copyable as is to a new test directory
TEST_OBJ_FILES=$(TEST_CFILES:%.c=%.o)
TEST_EXECUTABLES:=$(basename $(TEST_CFILES))
RUN_EXECUTABLES:= $(addsuffix .run, $(TEST_EXECUTABLES))

all: tests

tests: $(TEST_EXECUTABLES)

$(TEST_EXECUTABLES): %: %.o
	$(CC) $(LDFLAGS) $< $(LDLIBS) -o $@

$(TEST_OBJ_FILES): ../utils.h ../../../libsipnet.a ../exitHandler.c
$(TEST_OBJ_FILES): %.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

run: $(RUN_EXECUTABLES)

$(RUN_EXECUTABLES):
	./$(basename $@)

clean:
	rm -f $(TEST_OBJ_FILES) $(TEST_EXECUTABLES) events.in

.PHONY: all tests clean run $(RUN_EXECUTABLES)
