SIPNET: sipnet.c File Reference
sipnet.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include "sipnet.h"
#include "runmean.h"
#include "util.h"
#include "spatialParams.h"
Data Structures
struct ClimateVars
struct Parameters
struct Environment
struct FluxVars
struct TrackerVars
struct PhenologyTrackersStruct
struct ModelOptionsStruct
Macros
#define C_WEIGHT 12.0
#define TEN_6 1000000.0
#define TEN_9 1000000000.0
#define SEC_PER_DAY 86400.0
#define MEAN_NPP_DAYS 5
#define MEAN_NPP_MAX_ENTRIES MEAN_NPP_DAYS * 24
#define MEAN_GPP_SOIL_DAYS 3
#define MEAN_GPP_SOIL_MAX_ENTRIES MEAN_GPP_SOIL_DAYS * 24
#define MEAN_NPP_SOIL_DAYS 3
#define MEAN_NPP_SOIL_MAX_ENTRIES MEAN_NPP_SOIL_DAYS * 24
#define LAMBDA 2501000.
#define LAMBDA_S 2835000.
#define RHO 1.3
#define CP 1005.
#define GAMMA 66.
#define E_STAR_SNOW
#define TINY 0.000001
#define NUM_PARAMS 84
#define NUMBER_OPTIONS 24
Typedefs
typedef struct ClimateVars ClimateNode
typedef struct Parameters Params
typedef struct Environment Envi
typedef struct FluxVars Fluxes
typedef struct TrackerVars Trackers
typedef struct PhenologyTrackersStruct PhenologyTrackers
typedef struct ModelOptionsStruct ModelOptions
Functions
int * readClimData (char *climFile, int numLocs)
void readOptions (char *optionsFile)
int readParamData (SpatialParams **spatialParamsPtr, char *paramFile, char *spatialParamFile)
void outputHeader (FILE *out)
void outputState (FILE *out, int loc, int year, int day, double time)
void outputStatecsv (FILE *out, int loc, int year, int day, double time)
void freeClimateList (int numLocs)
void calcLightEff2 (double *lightEff, double lai, double par)
void calcLightEff3 (double *lightEff, double lai, double par)
void potPsn (double *potGrossPsn, double *baseFolResp, double lai, double tair, double vpd, double par, int day)
void moisture_bwb (double *trans, double *dWater, double potGrossPsn, double vpd, double vPress, double plantLeafC, double leafCSpWt, double soilWater)
void moisture_pm (double *trans, double *dWater, double potGrossPsn, double vpd, double soilWater)
void moisture (double *trans, double *dWater, double potGrossPsn, double vpd, double soilWater)
int pastLeafGrowth ()
int pastLeafFall ()
void leafFluxes (double *leafCreation, double *leafLitter, double plantLeafC)
void simpleWaterFlow (double *rain, double *snowFall, double *immedEvap, double *snowMelt, double *sublimation, double *fastFlow, double *evaporation, double *topDrainage, double *bottomDrainage, double water, double snow, double precip, double temp, double length, double trans)
void calcPrecip (double *rain, double *snowFall, double *immedEvap)
void snowPack (double *snowMelt, double *sublimation, double snowFall)
void evapSoilFluxes (double *fastFlow, double *evaporation, double *drainage, double water, double whc, double netRain, double snowMelt, double fluxesOut)
void transSoilDrainage (double *bottomDrainage, double topDrainage, double trans, double soilWater)
void soilWaterFluxes (double *fastFlow, double *evaporation, double *topDrainage, double *bottomDrainage, double netRain, double snowMelt, double trans, double litterWater, double soilWater)
void getGpp (double *gpp, double potGrossPsn, double dWater)
void vegResp (double *folResp, double *woodResp, double baseFolResp)
void calcRootResp (double *rootResp, double respQ10, double baseRate, double poolSize)
void vegResp2 (double *folResp, double *woodResp, double *growthResp, double baseFolResp, double gpp)
void ensureAllocation ()
void calcMaintenanceRespiration (double tsoil, double water, double whc)
double microbeQualityEfficiency (double soilQuality)
void microbeGrowth ()
int litterInputPool (double qualityComponent)
void soilDegradation ()
double woodLitterF (double plantWoodC)
void calculateFluxes ()
void initTrackers (void)
void ensureNonNegative (double *var, double minVal)
void ensureNonNegativeStocks ()
void updateTrackers (double oldSoilWater)
void updateState ()
void initPhenologyTrackers ()
void optionsSet ()
void setupModel (SpatialParams *spatialParams, int loc)
void runModelOutput (FILE *out, int printHeader, SpatialParams *spatialParams, int loc)
void runModelNoOut (double **outArray, int numDataTypes, int dataTypeIndices[], SpatialParams *spatialParams, int loc)
void sensTest (FILE *out, int paramNum, double low, double high, int numRuns, SpatialParams *spatialParams, int loc)
void printModelComponents (FILE *out)
char ** getDataTypeNames ()
void setupOutputPointers (void)
int initModel (SpatialParams **spatialParams, int **steps, char *paramFile, char *climFile, char *optionsFile)
void cleanupModel (int numLocs)
Variables
static ClimateNode ** firstClimates
static Params params
static Envi envi
static Trackers trackers
static PhenologyTrackers phenologyTrackers
static MeanTracker * meanNPP
static MeanTracker * meanGPP
static ClimateNode * climate
static Fluxes fluxes
static double * outputPtrs [MAX_DATA_TYPES]
static ModelOptions options
Macro Definition Documentation
C_WEIGHT
#define C_WEIGHT 12.0
Definition at line 24 of file SIPNEToptsIn/sipnet.c.
CP
#define CP 1005.
Definition at line 45 of file SIPNEToptsIn/sipnet.c.
E_STAR_SNOW
#define E_STAR_SNOW
Value:
                           0.6 /* approximate saturation vapor pressure at 0 degrees C (kPa)
                           (we assume snow temperature is 0 degrees C or slightly lower) */
Definition at line 47 of file SIPNEToptsIn/sipnet.c.
GAMMA
#define GAMMA 66.
Definition at line 46 of file SIPNEToptsIn/sipnet.c.
LAMBDA
#define LAMBDA 2501000.
Definition at line 42 of file SIPNEToptsIn/sipnet.c.
LAMBDA_S
#define LAMBDA_S 2835000.
Definition at line 43 of file SIPNEToptsIn/sipnet.c.
MEAN_GPP_SOIL_DAYS
#define MEAN_GPP_SOIL_DAYS 3
Definition at line 34 of file SIPNEToptsIn/sipnet.c.
MEAN_GPP_SOIL_MAX_ENTRIES
#define MEAN_GPP_SOIL_MAX_ENTRIES MEAN_GPP_SOIL_DAYS * 24
Definition at line 35 of file SIPNEToptsIn/sipnet.c.
MEAN_NPP_DAYS
#define MEAN_NPP_DAYS 5
Definition at line 30 of file SIPNEToptsIn/sipnet.c.
MEAN_NPP_MAX_ENTRIES
#define MEAN_NPP_MAX_ENTRIES MEAN_NPP_DAYS * 24
Definition at line 31 of file SIPNEToptsIn/sipnet.c.
MEAN_NPP_SOIL_DAYS
#define MEAN_NPP_SOIL_DAYS 3
Definition at line 38 of file SIPNEToptsIn/sipnet.c.
MEAN_NPP_SOIL_MAX_ENTRIES
#define MEAN_NPP_SOIL_MAX_ENTRIES MEAN_NPP_SOIL_DAYS * 24
Definition at line 39 of file SIPNEToptsIn/sipnet.c.
NUM_PARAMS
#define NUM_PARAMS 84
Definition at line 254 of file SIPNEToptsIn/sipnet.c.
NUMBER_OPTIONS
#define NUMBER_OPTIONS 24
Definition at line 473 of file SIPNEToptsIn/sipnet.c.
RHO
#define RHO 1.3
Definition at line 44 of file SIPNEToptsIn/sipnet.c.
SEC_PER_DAY
#define SEC_PER_DAY 86400.0
Definition at line 27 of file SIPNEToptsIn/sipnet.c.
TEN_6
#define TEN_6 1000000.0
Definition at line 25 of file SIPNEToptsIn/sipnet.c.
TEN_9
#define TEN_9 1000000000.0
Definition at line 26 of file SIPNEToptsIn/sipnet.c.
TINY
#define TINY 0.000001
Definition at line 49 of file SIPNEToptsIn/sipnet.c.
Typedef Documentation
ClimateNode
typedef struct ClimateVars ClimateNode
Definition at line 57 of file SIPNEToptsIn/sipnet.c.
Envi
typedef struct Environment Envi
Fluxes
typedef struct FluxVars Fluxes
ModelOptions
typedef struct ModelOptionsStruct ModelOptions
Params
typedef struct Parameters Params
PhenologyTrackers
typedef struct PhenologyTrackersStruct PhenologyTrackers
Trackers
typedef struct TrackerVars Trackers
Function Documentation
calcLightEff2()
void calcLightEff2 (double * lightEff, double lai, double par)
Definition at line 899 of file SIPNEToptsIn/sipnet.c.
References Parameters::attenuation, Parameters::halfSatPar, index, par, and params.
calcLightEff3()
void calcLightEff3 (double * lightEff, double lai, double par)
Definition at line 925 of file SIPNEToptsIn/sipnet.c.
References Parameters::attenuation, Parameters::halfSatPar, index, par, and params.
Referenced by potPsn().
calcMaintenanceRespiration()
void calcMaintenanceRespiration (double tsoil, double water, double whc)
Definition at line 1580 of file SIPNEToptsIn/sipnet.c.
References Parameters::baseMicrobeResp, Parameters::baseSoilResp, Parameters::baseSoilRespCold, Parameters::baseSoilRespColdEpsilon, Parameters::baseSoilRespEpsilon, Parameters::coldSoilThreshold, ModelOptionsStruct::DAYCENT_WATER_HRESP, envi, fluxes, index, FluxVars::maintRespiration, Environment::microbeC, Parameters::microbeQ10, ModelOptionsStruct::MICROBES, ModelOptionsStruct::NUMBER_SOIL_CARBON_POOLS, options, params, ModelOptionsStruct::SEASONAL_R_SOIL, Environment::soil, ModelOptionsStruct::SOIL_MULTIPOOL, ModelOptionsStruct::SOIL_QUALITY, Parameters::soilRespMoistEffect, Parameters::soilRespQ10, Parameters::soilRespQ10Cold, Parameters::soilRespQ10ColdEpsilon, Parameters::soilRespQ10Epsilon, tsoil, and ModelOptionsStruct::WATER_HRESP.
Referenced by soilDegradation().
calcPrecip()
void calcPrecip (double * rain, double * snowFall, double * immedEvap)
Definition at line 1318 of file SIPNEToptsIn/sipnet.c.
References climate, Parameters::immedEvapFrac, ClimateVars::length, params, ClimateVars::precip, and ClimateVars::tair.
Referenced by calculateFluxes().
calcRootResp()
void calcRootResp (double * rootResp, double respQ10, double baseRate, double poolSize)
Definition at line 1534 of file SIPNEToptsIn/sipnet.c.
References climate, index, and ClimateVars::tsoil.
Referenced by calculateFluxes().
calculateFluxes()
void calculateFluxes ()
Definition at line 1905 of file SIPNEToptsIn/sipnet.c.
References Parameters::baseCoarseRootResp, Parameters::baseFineRootResp, FluxVars::bottomDrainage, calcPrecip(), calcRootResp(), climate, Environment::coarseRootC, FluxVars::coarseRootCreation, Parameters::coarseRootExudation, FluxVars::coarseRootLoss, Parameters::coarseRootQ10, Parameters::coarseRootTurnoverRate, ModelOptionsStruct::COMPLEX_WATER, ClimateVars::day, envi, FluxVars::evaporation, FluxVars::fastFlow, Parameters::fineRootAllocation, Environment::fineRootC, FluxVars::fineRootCreation, Parameters::fineRootExudation, FluxVars::fineRootLoss, Parameters::fineRootQ10, Parameters::fineRootTurnoverRate, fluxes, Parameters::fracLitterRespired, getGpp(), getMeanTrackerMean(), ModelOptionsStruct::GROWTH_RESP, FluxVars::immedEvap, index, Parameters::leafAllocation, FluxVars::leafCreation, Parameters::leafCSpWt, leafFluxes(), FluxVars::leafLitter, ClimateVars::length, Environment::litter, ModelOptionsStruct::LITTER_POOL, Parameters::litterBreakdownRate, FluxVars::litterToSoil, Environment::litterWater, Parameters::litterWHC, meanGPP, meanNPP, Parameters::microbePulseEff, ModelOptionsStruct::MODEL_WATER, moisture(), options, ClimateVars::par, params, FluxVars::photosynthesis, Environment::plantLeafC, Environment::plantWoodC, potPsn(), ClimateVars::precip, FluxVars::rain, FluxVars::rCoarseRoot, FluxVars::rFineRoot, FluxVars::rLeaf, FluxVars::rLitter, ModelOptionsStruct::ROOTS, FluxVars::rVeg, FluxVars::rWood, simpleWaterFlow(), Environment::snow, FluxVars::snowFall, FluxVars::snowMelt, snowPack(), soilBreakdown(), FluxVars::soilPulse, Parameters::soilRespQ10, Environment::soilWater, soilWaterFluxes(), ClimateVars::soilWetness, Parameters::soilWHC, FluxVars::sublimation, ClimateVars::tair, FluxVars::topDrainage, FluxVars::transpiration, ClimateVars::tsoil, vegResp(), vegResp2(), ClimateVars::vpd, Parameters::woodAllocation, FluxVars::woodCreation, FluxVars::woodLitter, and woodLitterF().
Referenced by updateState().
cleanupModel()
void cleanupModel (int numLocs)
Definition at line 2666 of file SIPNEToptsIn/sipnet.c.
References deallocateMeanTracker(), freeClimateList(), meanGPP, meanNPP, and numLocs.
ensureAllocation()
void ensureAllocation ()
Definition at line 1559 of file SIPNEToptsIn/sipnet.c.
References Parameters::fineRootAllocation, index, Parameters::leafAllocation, params, and Parameters::woodAllocation.
Referenced by setupModel().
ensureNonNegative()
void ensureNonNegative (double * var, double minVal)
Definition at line 2115 of file SIPNEToptsIn/sipnet.c.
References index.
Referenced by ensureNonNegativeStocks().
ensureNonNegativeStocks()
void ensureNonNegativeStocks ()
Definition at line 2127 of file SIPNEToptsIn/sipnet.c.
References ensureNonNegative(), envi, Environment::litter, ModelOptionsStruct::LITTER_POOL, ModelOptionsStruct::LITTER_WATER, Environment::litterWater, ModelOptionsStruct::MODEL_WATER, options, Environment::plantLeafC, Environment::plantWoodC, Environment::snow, Environment::soil, Environment::soilWater, and TINY.
Referenced by updateState().
evapSoilFluxes()
void evapSoilFluxes (double * fastFlow, double * evaporation, double * drainage, double water, double whc, double netRain, double snowMelt, double fluxesOut)
Definition at line 1411 of file SIPNEToptsIn/sipnet.c.
References climate, CP, envi, Parameters::fastFlowFrac, GAMMA, index, LAMBDA, ClimateVars::length, ModelOptionsStruct::LITTER_WATER_DRAINAGE, Parameters::litWaterDrainRate, options, params, Parameters::rdConst, RHO, Parameters::rSoilConst1, Parameters::rSoilConst2, SEC_PER_DAY, Environment::snow, TINY, ClimateVars::vpdSoil, and ClimateVars::wspd.
Referenced by soilWaterFluxes().
freeClimateList()
void freeClimateList (int numLocs)
Definition at line 873 of file SIPNEToptsIn/sipnet.c.
References firstClimates, index, ClimateVars::nextClim, and numLocs.
Referenced by cleanupModel().
getDataTypeNames()
char ** getDataTypeNames ()
Definition at line 2580 of file SIPNEToptsIn/sipnet.c.
References index, and MAX_DATA_TYPES.
getGpp()
void getGpp (double * gpp, double potGrossPsn, double dWater)
Definition at line 1517 of file SIPNEToptsIn/sipnet.c.
References index.
Referenced by calculateFluxes().
initModel()
int initModel (SpatialParams ** spatialParams, int ** steps, char * paramFile, char * climFile, char * optionsFile)
Definition at line 2642 of file SIPNEToptsIn/sipnet.c.
References index, MEAN_GPP_SOIL_DAYS, MEAN_GPP_SOIL_MAX_ENTRIES, MEAN_NPP_DAYS, MEAN_NPP_MAX_ENTRIES, meanGPP, meanNPP, newMeanTracker(), numLocs, readClimData(), readOptions(), readParamData(), and setupOutputPointers().
initPhenologyTrackers()
void initPhenologyTrackers ()
Definition at line 2304 of file SIPNEToptsIn/sipnet.c.
References climate, PhenologyTrackersStruct::didLeafFall, PhenologyTrackersStruct::didLeafGrowth, PhenologyTrackersStruct::lastYear, pastLeafFall(), pastLeafGrowth(), phenologyTrackers, and ClimateVars::year.
Referenced by setupModel().
initTrackers()
void initTrackers (void)
Definition at line 2075 of file SIPNEToptsIn/sipnet.c.
References envi, TrackerVars::evapotranspiration, TrackerVars::fa, TrackerVars::fr, TrackerVars::gpp, TrackerVars::nee, TrackerVars::npp, params, TrackerVars::ra, TrackerVars::rAboveground, TrackerVars::rh, TrackerVars::rRoot, TrackerVars::rSoil, TrackerVars::rtot, Parameters::soilInit, Environment::soilWater, TrackerVars::soilWetnessFrac, Parameters::soilWHC, TrackerVars::totGpp, TrackerVars::totNee, TrackerVars::totNpp, TrackerVars::totRa, TrackerVars::totRh, TrackerVars::totRtot, TrackerVars::totSoilC, trackers, TrackerVars::yearlyGpp, TrackerVars::yearlyNee, TrackerVars::yearlyNpp, TrackerVars::yearlyRa, TrackerVars::yearlyRh, and TrackerVars::yearlyRtot.
Referenced by setupModel().
leafFluxes()
void leafFluxes (double * leafCreation, double * leafLitter, double plantLeafC)
Definition at line 1234 of file SIPNEToptsIn/sipnet.c.
References climate, PhenologyTrackersStruct::didLeafFall, PhenologyTrackersStruct::didLeafGrowth, Parameters::fracLeafFall, getMeanTrackerMean(), PhenologyTrackersStruct::lastYear, Parameters::leafAllocation, Parameters::leafGrowth, Parameters::leafTurnoverRate, ClimateVars::length, meanNPP, params, pastLeafFall(), pastLeafGrowth(), phenologyTrackers, and ClimateVars::year.
Referenced by calculateFluxes().
litterInputPool()
int litterInputPool (double qualityComponent)
Definition at line 1752 of file SIPNEToptsIn/sipnet.c.
References index, ModelOptionsStruct::NUMBER_SOIL_CARBON_POOLS, and options.
Referenced by soilDegradation().
microbeGrowth()
void microbeGrowth ()
Definition at line 1712 of file SIPNEToptsIn/sipnet.c.
References envi, fluxes, Parameters::halfSatIngestion, index, Parameters::maxIngestionRate, Parameters::maxIngestionRateEpsilon, Environment::microbeC, FluxVars::microbeIngestion, ModelOptionsStruct::MICROBES, ModelOptionsStruct::NUMBER_SOIL_CARBON_POOLS, options, params, Environment::soil, ModelOptionsStruct::SOIL_MULTIPOOL, ModelOptionsStruct::SOIL_QUALITY, TrackerVars::totSoilC, and trackers.
Referenced by soilDegradation().
microbeQualityEfficiency()
double microbeQualityEfficiency (double soilQuality)
Definition at line 1704 of file SIPNEToptsIn/sipnet.c.
References Parameters::efficiency, Parameters::efficiencyEpsilon, index, and params.
moisture()
void moisture (double * trans, double * dWater, double potGrossPsn, double vpd, double soilWater)
Definition at line 1168 of file SIPNEToptsIn/sipnet.c.
References climate, Parameters::frozenSoilEff, Parameters::frozenSoilThreshold, index, options, params, TINY, ClimateVars::tsoil, vpd, ModelOptionsStruct::WATER_PSN, Parameters::waterRemoveFrac, and Parameters::wueConst.
Referenced by calculateFluxes().
moisture_bwb()
void moisture_bwb (double * trans, double * dWater, double potGrossPsn, double vpd, double vPress, double plantLeafC, double leafCSpWt, double soilWater)
Definition at line 1009 of file SIPNEToptsIn/sipnet.c.
References climate, envi, Parameters::frozenSoilEff, Parameters::frozenSoilThreshold, index, Parameters::leafCSpWt, Parameters::m_ballBerry, options, params, Environment::plantLeafC, TINY, ClimateVars::tsoil, ClimateVars::vpd, ClimateVars::vPress, ModelOptionsStruct::WATER_PSN, and Parameters::waterRemoveFrac.
moisture_pm()
void moisture_pm (double * trans, double * dWater, double potGrossPsn, double vpd, double soilWater)
Definition at line 1095 of file SIPNEToptsIn/sipnet.c.
References climate, CP, DELTA, Parameters::frozenSoilEff, Parameters::frozenSoilThreshold, GAMMA, index, ClimateVars::netrad, options, params, Parameters::rdConst, RHO, ClimateVars::soilheat, ClimateVars::tair, TINY, ClimateVars::tsoil, vpd, ModelOptionsStruct::WATER_PSN, Parameters::waterRemoveFrac, and ClimateVars::wspd.
optionsSet()
void optionsSet ()
Definition at line 2326 of file SIPNEToptsIn/sipnet.c.
References ModelOptionsStruct::COMPLEX_WATER, ModelOptionsStruct::DAYCENT_WATER_HRESP, ModelOptionsStruct::GDD, ModelOptionsStruct::LITTER_POOL, ModelOptionsStruct::LITTER_WATER, ModelOptionsStruct::LITTER_WATER_DRAINAGE, ModelOptionsStruct::LLOYD_TAYLOR, ModelOptionsStruct::MICROBES, ModelOptionsStruct::MODEL_WATER, options, ModelOptionsStruct::SEASONAL_R_SOIL, ModelOptionsStruct::SNOW, ModelOptionsStruct::SOIL_MULTIPOOL, ModelOptionsStruct::SOIL_PHENOL, ModelOptionsStruct::SOIL_QUALITY, ModelOptionsStruct::STOICHIOMETRY, and ModelOptionsStruct::WATER_HRESP.
Referenced by setupModel().
outputHeader()
void outputHeader (FILE * out)
Definition at line 817 of file SIPNEToptsIn/sipnet.c.
References fprintf(), and index.
Referenced by runModelOutput().
outputState()
void outputState (FILE * out, int loc, int year, int day, double time)
Definition at line 824 of file SIPNEToptsIn/sipnet.c.
References Environment::coarseRootC, day, envi, Environment::fineRootC, fprintf(), TrackerVars::gpp, index, Environment::litter, Environment::litterWater, Environment::microbeC, TrackerVars::nee, TrackerVars::npp, ModelOptionsStruct::NUMBER_SOIL_CARBON_POOLS, options, Environment::plantLeafC, Environment::plantWoodC, TrackerVars::rAboveground, ModelOptionsStruct::ROOTS, TrackerVars::rSoil, TrackerVars::rtot, Environment::snow, Environment::soil, ModelOptionsStruct::SOIL_MULTIPOOL, Environment::soilWater, TrackerVars::soilWetnessFrac, time, TrackerVars::totSoilC, trackers, and year.
Referenced by runModelOutput().
outputStatecsv()
void outputStatecsv (FILE * out, int loc, int year, int day, double time)
Definition at line 864 of file SIPNEToptsIn/sipnet.c.
References day, envi, TrackerVars::evapotranspiration, fluxes, fprintf(), TrackerVars::gpp, index, Environment::litter, Environment::litterWater, TrackerVars::nee, TrackerVars::npp, Environment::plantLeafC, Environment::plantWoodC, TrackerVars::ra, TrackerVars::rh, TrackerVars::rtot, Environment::snow, Environment::soil, Environment::soilWater, TrackerVars::soilWetnessFrac, time, TrackerVars::totNee, trackers, FluxVars::transpiration, year, and TrackerVars::yearlyNpp.
pastLeafFall()
int pastLeafFall ()
Definition at line 1226 of file SIPNEToptsIn/sipnet.c.
References climate, ClimateVars::day, Parameters::leafOffDay, params, and ClimateVars::time.
Referenced by initPhenologyTrackers(), and leafFluxes().
pastLeafGrowth()
int pastLeafGrowth ()
Definition at line 1213 of file SIPNEToptsIn/sipnet.c.
References climate, ClimateVars::day, ClimateVars::gdd, ModelOptionsStruct::GDD, Parameters::gddLeafOn, Parameters::leafOnDay, options, params, ModelOptionsStruct::SOIL_PHENOL, Parameters::soilTempLeafOn, ClimateVars::time, and ClimateVars::tsoil.
Referenced by initPhenologyTrackers(), and leafFluxes().
potPsn()
void potPsn (double * potGrossPsn, double * baseFolResp, double lai, double tair, double vpd, double par, int day)
Definition at line 981 of file SIPNEToptsIn/sipnet.c.
References Parameters::aMax, Parameters::aMaxFrac, Parameters::baseFolRespFrac, C_WEIGHT, calcLightEff3(), Parameters::cFracLeaf, Parameters::dVpdExp, Parameters::dVpdSlope, index, Parameters::leafCSpWt, par, params, Parameters::psnTMax, Parameters::psnTMin, SEC_PER_DAY, tair, TEN_9, and vpd.
Referenced by calculateFluxes().
printModelComponents()
void printModelComponents (FILE * out)
Definition at line 2550 of file SIPNEToptsIn/sipnet.c.
References ModelOptionsStruct::COMPLEX_WATER, ModelOptionsStruct::DAYCENT_WATER_HRESP, fprintf(), ModelOptionsStruct::GDD, ModelOptionsStruct::GROWTH_RESP, index, ModelOptionsStruct::LITTER_POOL, ModelOptionsStruct::LITTER_WATER, ModelOptionsStruct::LITTER_WATER_DRAINAGE, ModelOptionsStruct::LLOYD_TAYLOR, ModelOptionsStruct::MODEL_WATER, options, ModelOptionsStruct::SEASONAL_R_SOIL, ModelOptionsStruct::SNOW, ModelOptionsStruct::SOIL_PHENOL, ModelOptionsStruct::WATER_HRESP, and ModelOptionsStruct::WATER_PSN.
readClimData()
int * readClimData (char * climFile, int numLocs)
Definition at line 512 of file SIPNEToptsIn/sipnet.c.
References count, day, exit(), fclose(), firstClimates, ModelOptionsStruct::GDD, i, index, lastYear, length(), numLocs, openFile(), options, par, tair, time, TINY, tsoil, vpd, wspd, ClimateVars::year, and year.
Referenced by initModel().
readOptions()
void readOptions (char * optionsFile)
Definition at line 648 of file SIPNEToptsIn/sipnet.c.
References ModelOptionsStruct::ALTERNATIVE_TRANS, ModelOptionsStruct::BALL_BERRY, ModelOptionsStruct::COMPLEX_WATER, ModelOptionsStruct::CSV_OUTPUT, ModelOptionsStruct::DAYCENT_WATER_HRESP, fclose(), ModelOptionsStruct::GDD, ModelOptionsStruct::GROWTH_RESP, index, ModelOptionsStruct::LITTER_POOL, ModelOptionsStruct::LITTER_WATER, ModelOptionsStruct::LITTER_WATER_DRAINAGE, ModelOptionsStruct::LLOYD_TAYLOR, ModelOptionsStruct::MICROBES, ModelOptionsStruct::MODEL_WATER, ModelOptionsStruct::NUMBER_SOIL_CARBON_POOLS, openFile(), options, ModelOptionsStruct::PENMAN_MONTEITH_TRANS, ModelOptionsStruct::ROOTS, ModelOptionsStruct::SEASONAL_R_SOIL, ModelOptionsStruct::SNOW, ModelOptionsStruct::SOIL_MULTIPOOL, ModelOptionsStruct::SOIL_PHENOL, ModelOptionsStruct::SOIL_QUALITY, ModelOptionsStruct::STOICHIOMETRY, ModelOptionsStruct::WATER_HRESP, and ModelOptionsStruct::WATER_PSN.
Referenced by initModel().
readParamData()
int readParamData (SpatialParams ** spatialParamsPtr, char * paramFile, char * spatialParamFile)
Definition at line 692 of file SIPNEToptsIn/sipnet.c.
References allParamsRead(), Parameters::aMax, Parameters::aMaxFrac, Parameters::attenuation, Parameters::baseCoarseRootResp, Parameters::baseFineRootResp, Parameters::baseFolRespFrac, Parameters::baseMicrobeResp, Parameters::baseSoilResp, Parameters::baseSoilRespCold, Parameters::baseSoilRespColdEpsilon, Parameters::baseSoilRespEpsilon, Parameters::baseVegResp, Parameters::cFracLeaf, Parameters::coarseRootExudation, Parameters::coarseRootFrac, Parameters::coarseRootQ10, Parameters::coarseRootTurnoverRate, Parameters::coldSoilThreshold, Parameters::dVpdExp, Parameters::dVpdSlope, Parameters::E0, Parameters::efficiency, Parameters::efficiencyEpsilon, exit(), Parameters::fastFlowFrac, fclose(), Parameters::fineRootAllocation, Parameters::fineRootExudation, Parameters::fineRootFrac, Parameters::fineRootQ10, Parameters::fineRootTurnoverRate, Parameters::fracLeafFall, Parameters::fracLitterRespired, Parameters::frozenSoilEff, Parameters::frozenSoilFolREff, Parameters::frozenSoilThreshold, Parameters::gddLeafOn, Parameters::growthRespFrac, Parameters::halfSatIngestion, Parameters::halfSatPar, Parameters::immedEvapFrac, index, Parameters::laiInit, Parameters::leafAllocation, Parameters::leafCSpWt, Parameters::leafGrowth, Parameters::leafOffDay, Parameters::leafOnDay, Parameters::leafTurnoverRate, Parameters::litterBreakdownRate, Parameters::litterInit, Parameters::litterWFracInit, Parameters::litterWHC, Parameters::litWaterDrainRate, Parameters::m_ballBerry, Parameters::maxIngestionRate, Parameters::maxIngestionRateEpsilon, Parameters::microbeInit, Parameters::microbeNC, Parameters::microbePulseEff, Parameters::microbeQ10, newSpatialParams(), NUM_PARAMS, numLocs, openFile(), params, Parameters::plantWoodInit, Parameters::psnTMin, Parameters::psnTOpt, Parameters::qualityLeaf, Parameters::qualityWood, Parameters::rdConst, readOneSpatialParam(), Parameters::rSoilConst1, Parameters::rSoilConst2, Parameters::snowInit, Parameters::snowMelt, Parameters::soilInit, Parameters::soilRespMoistEffect, Parameters::soilRespQ10, Parameters::soilRespQ10Cold, Parameters::soilRespQ10ColdEpsilon, Parameters::soilRespQ10Epsilon, Parameters::soilTempLeafOn, Parameters::soilWFracInit, Parameters::soilWHC, Parameters::T0, Parameters::totNitrogen, Parameters::vegRespQ10, Parameters::waterRemoveFrac, Parameters::woodAllocation, Parameters::woodTurnoverRate, and Parameters::wueConst.
Referenced by initModel().
runModelNoOut()
void runModelNoOut (double ** outArray, int numDataTypes, int dataTypeIndices[], SpatialParams * spatialParams, int loc)
Definition at line 2508 of file SIPNEToptsIn/sipnet.c.
References climate, index, ClimateVars::nextClim, outputPtrs, setupModel(), step, and updateState().
runModelOutput()
void runModelOutput (FILE * out, int printHeader, SpatialParams * spatialParams, int loc)
Definition at line 2473 of file SIPNEToptsIn/sipnet.c.
References climate, ClimateVars::day, index, ClimateVars::nextClim, outputHeader(), outputState(), setupModel(), ClimateVars::time, updateState(), and ClimateVars::year.
Referenced by sensTest().
sensTest()
void sensTest (FILE * out, int paramNum, double low, double high, int numRuns, SpatialParams * spatialParams, int loc)
Definition at line 2529 of file SIPNEToptsIn/sipnet.c.
References fprintf(), index, runModelOutput(), setSpatialParam(), and value.
setupModel()
void setupModel (SpatialParams * spatialParams, int loc)
Definition at line 2353 of file SIPNEToptsIn/sipnet.c.
References Parameters::baseCoarseRootResp, Parameters::baseFineRootResp, Parameters::baseMicrobeResp, Parameters::baseSoilResp, Parameters::baseSoilRespCold, Parameters::baseVegResp, climate, Environment::coarseRootC, Parameters::coarseRootFrac, Parameters::coarseRootTurnoverRate, ensureAllocation(), envi, Environment::fineRootC, Parameters::fineRootFrac, Parameters::fineRootTurnoverRate, firstClimates, Parameters::halfSatIngestion, index, initPhenologyTrackers(), initTrackers(), Parameters::laiInit, Parameters::leafCSpWt, Parameters::leafTurnoverRate, Environment::litter, Parameters::litterBreakdownRate, Parameters::litterInit, Environment::litterWater, Parameters::litterWFracInit, Parameters::litterWHC, loadSpatialParams(), Parameters::maxIngestionRate, meanGPP, meanNPP, Environment::microbeC, Parameters::microbeInit, Parameters::microbePulseEff, ModelOptionsStruct::MICROBES, ModelOptionsStruct::NUMBER_SOIL_CARBON_POOLS, options, optionsSet(), params, Environment::plantLeafC, Environment::plantWoodC, Parameters::plantWoodInit, Parameters::psnTMax, Parameters::psnTMin, Parameters::psnTOpt, resetMeanTracker(), ModelOptionsStruct::ROOTS, Environment::snow, Parameters::snowInit, Environment::soil, ModelOptionsStruct::SOIL_MULTIPOOL, ModelOptionsStruct::SOIL_QUALITY, Parameters::soilInit, Environment::soilWater, Parameters::soilWFracInit, Parameters::soilWHC, Parameters::totNitrogen, TrackerVars::totSoilC, trackers, and Parameters::woodTurnoverRate.
Referenced by runModelNoOut(), and runModelOutput().
setupOutputPointers()
void setupOutputPointers (void)
Definition at line 2594 of file SIPNEToptsIn/sipnet.c.
References TrackerVars::evapotranspiration, TrackerVars::gpp, i, TrackerVars::nee, TrackerVars::npp, outputPtrs, TrackerVars::ra, TrackerVars::rh, TrackerVars::rtot, TrackerVars::soilWetnessFrac, TrackerVars::totGpp, TrackerVars::totNee, TrackerVars::totNpp, TrackerVars::totRa, TrackerVars::totRh, TrackerVars::totRtot, trackers, TrackerVars::yearlyGpp, TrackerVars::yearlyNee, TrackerVars::yearlyNpp, TrackerVars::yearlyRa, TrackerVars::yearlyRh, and TrackerVars::yearlyRtot.
Referenced by initModel().
simpleWaterFlow()
void simpleWaterFlow (double * rain, double * snowFall, double * immedEvap, double * snowMelt, double * sublimation, double * fastFlow, double * evaporation, double * topDrainage, double * bottomDrainage, double water, double snow, double precip, double temp, double length, double trans)
Definition at line 1274 of file SIPNEToptsIn/sipnet.c.
References index, length(), options, params, ModelOptionsStruct::SNOW, Parameters::snowMelt, and Parameters::soilWHC.
Referenced by calculateFluxes().
snowPack()
void snowPack (double * snowMelt, double * sublimation, double snowFall)
Definition at line 1345 of file SIPNEToptsIn/sipnet.c.
References climate, CP, E_STAR_SNOW, envi, GAMMA, index, LAMBDA_S, ClimateVars::length, params, Parameters::rdConst, RHO, SEC_PER_DAY, Environment::snow, Parameters::snowMelt, ClimateVars::tair, ClimateVars::vPress, and ClimateVars::wspd.
Referenced by calculateFluxes().
soilDegradation()
void soilDegradation ()
Definition at line 1757 of file SIPNEToptsIn/sipnet.c.
References calcMaintenanceRespiration(), climate, Environment::coarseRootC, FluxVars::coarseRootCreation, FluxVars::coarseRootLoss, Parameters::efficiency, envi, Environment::fineRootC, FluxVars::fineRootCreation, FluxVars::fineRootLoss, fluxes, index, FluxVars::leafLitter, ClimateVars::length, length(), Environment::litter, ModelOptionsStruct::LITTER_POOL, litterInputPool(), FluxVars::litterToSoil, FluxVars::maintRespiration, Environment::microbeC, microbeGrowth(), FluxVars::microbeIngestion, Parameters::microbeNC, ModelOptionsStruct::MICROBES, ModelOptionsStruct::MODEL_WATER, ModelOptionsStruct::NUMBER_SOIL_CARBON_POOLS, options, params, Parameters::qualityLeaf, Parameters::qualityWood, FluxVars::rCoarseRoot, FluxVars::rFineRoot, FluxVars::rLitter, FluxVars::rSoil, Environment::soil, ModelOptionsStruct::SOIL_MULTIPOOL, ModelOptionsStruct::SOIL_QUALITY, FluxVars::soilPulse, Environment::soilWater, ClimateVars::soilWetness, Parameters::soilWHC, ModelOptionsStruct::STOICHIOMETRY, Parameters::totNitrogen, ClimateVars::tsoil, and FluxVars::woodLitter.
Referenced by updateState().
soilWaterFluxes()
void soilWaterFluxes (double * fastFlow, double * evaporation, double * topDrainage, double * bottomDrainage, double netRain, double snowMelt, double trans, double litterWater, double soilWater)
Definition at line 1499 of file SIPNEToptsIn/sipnet.c.
References evapSoilFluxes(), index, ModelOptionsStruct::LITTER_WATER, Parameters::litterWHC, options, params, Parameters::soilWHC, and transSoilDrainage().
Referenced by calculateFluxes().
transSoilDrainage()
void transSoilDrainage (double * bottomDrainage, double topDrainage, double trans, double soilWater)
Definition at line 1482 of file SIPNEToptsIn/sipnet.c.
References climate, index, ClimateVars::length, params, and Parameters::soilWHC.
Referenced by soilWaterFluxes().
updateState()
void updateState ()
Definition at line 2242 of file SIPNEToptsIn/sipnet.c.
References addValueToMeanTracker(), FluxVars::bottomDrainage, calculateFluxes(), climate, FluxVars::coarseRootCreation, ensureNonNegativeStocks(), envi, err, FluxVars::evaporation, exit(), FluxVars::fastFlow, FluxVars::fineRootCreation, fluxes, FluxVars::immedEvap, index, FluxVars::leafCreation, FluxVars::leafLitter, ClimateVars::length, ModelOptionsStruct::LITTER_WATER, Environment::litterWater, meanGPP, meanNPP, ModelOptionsStruct::MODEL_WATER, options, FluxVars::photosynthesis, Environment::plantLeafC, Environment::plantWoodC, FluxVars::rain, FluxVars::rCoarseRoot, FluxVars::rFineRoot, FluxVars::rVeg, Environment::snow, FluxVars::snowFall, FluxVars::snowMelt, soilDegradation(), Environment::soilWater, FluxVars::sublimation, FluxVars::topDrainage, FluxVars::transpiration, updateTrackers(), FluxVars::woodCreation, and FluxVars::woodLitter.
Referenced by runModelNoOut(), and runModelOutput().
updateTrackers()
void updateTrackers (double oldSoilWater)
Definition at line 2157 of file SIPNEToptsIn/sipnet.c.
References climate, envi, FluxVars::evaporation, TrackerVars::evapotranspiration, TrackerVars::fa, fluxes, TrackerVars::fr, TrackerVars::gpp, FluxVars::immedEvap, index, lastYear, ClimateVars::length, length(), TrackerVars::nee, TrackerVars::npp, ModelOptionsStruct::NUMBER_SOIL_CARBON_POOLS, options, params, FluxVars::photosynthesis, TrackerVars::ra, TrackerVars::rAboveground, FluxVars::rCoarseRoot, FluxVars::rFineRoot, TrackerVars::rh, FluxVars::rLeaf, FluxVars::rLitter, TrackerVars::rRoot, FluxVars::rSoil, TrackerVars::rSoil, TrackerVars::rtot, FluxVars::rVeg, FluxVars::rWood, Environment::soil, ModelOptionsStruct::SOIL_MULTIPOOL, Environment::soilWater, TrackerVars::soilWetnessFrac, Parameters::soilWHC, FluxVars::sublimation, TrackerVars::totGpp, TrackerVars::totNee, TrackerVars::totNpp, TrackerVars::totRa, TrackerVars::totRh, TrackerVars::totRtot, TrackerVars::totSoilC, trackers, FluxVars::transpiration, ClimateVars::year, TrackerVars::yearlyGpp, TrackerVars::yearlyNee, TrackerVars::yearlyNpp, TrackerVars::yearlyRa, TrackerVars::yearlyRh, and TrackerVars::yearlyRtot.
Referenced by updateState().
vegResp()
void vegResp (double * folResp, double * woodResp, double baseFolResp)
Definition at line 1524 of file SIPNEToptsIn/sipnet.c.
References Parameters::baseVegResp, climate, envi, Parameters::frozenSoilFolREff, Parameters::frozenSoilThreshold, index, params, Environment::plantWoodC, Parameters::psnTOpt, ClimateVars::tair, ClimateVars::tsoil, and Parameters::vegRespQ10.
Referenced by calculateFluxes().
vegResp2()
void vegResp2 (double * folResp, double * woodResp, double * growthResp, double baseFolResp, double gpp)
Definition at line 1544 of file SIPNEToptsIn/sipnet.c.
References Parameters::baseVegResp, climate, envi, Parameters::frozenSoilFolREff, Parameters::frozenSoilThreshold, getMeanTrackerMean(), Parameters::growthRespFrac, index, meanNPP, params, Environment::plantWoodC, Parameters::psnTOpt, ClimateVars::tair, ClimateVars::tsoil, and Parameters::vegRespQ10.
Referenced by calculateFluxes().
woodLitterF()
double woodLitterF (double plantWoodC)
Definition at line 1900 of file SIPNEToptsIn/sipnet.c.
References params, and Parameters::woodTurnoverRate.
Referenced by calculateFluxes().
Variable Documentation
climate
ClimateNode* climate static
Definition at line 491 of file SIPNEToptsIn/sipnet.c.
Referenced by calcPrecip(), calcRootResp(), calculateFluxes(), evapSoilFluxes(), initPhenologyTrackers(), leafFluxes(), moisture(), moisture_bwb(), moisture_pm(), pastLeafFall(), pastLeafGrowth(), runModelNoOut(), runModelOutput(), setupModel(), snowPack(), soilDegradation(), transSoilDrainage(), updateState(), updateTrackers(), vegResp(), and vegResp2().
envi
Envi envi static
Definition at line 485 of file SIPNEToptsIn/sipnet.c.
Referenced by calcMaintenanceRespiration(), calculateFluxes(), ensureNonNegativeStocks(), evapSoilFluxes(), initTrackers(), microbeGrowth(), moisture_bwb(), outputState(), outputStatecsv(), setupModel(), snowPack(), soilDegradation(), updateState(), updateTrackers(), vegResp(), and vegResp2().
firstClimates
ClimateNode** firstClimates static
Definition at line 479 of file SIPNEToptsIn/sipnet.c.
Referenced by freeClimateList(), readClimData(), and setupModel().
fluxes
Fluxes fluxes static
Definition at line 492 of file SIPNEToptsIn/sipnet.c.
Referenced by calcMaintenanceRespiration(), calculateFluxes(), microbeGrowth(), outputStatecsv(), soilDegradation(), updateState(), and updateTrackers().
meanGPP
MeanTracker* meanGPP static
Definition at line 489 of file SIPNEToptsIn/sipnet.c.
Referenced by calculateFluxes(), cleanupModel(), initModel(), setupModel(), and updateState().
meanNPP
MeanTracker* meanNPP static
Definition at line 488 of file SIPNEToptsIn/sipnet.c.
Referenced by calculateFluxes(), cleanupModel(), initModel(), leafFluxes(), setupModel(), updateState(), and vegResp2().
options
ModelOptions options static
Definition at line 495 of file SIPNEToptsIn/sipnet.c.
Referenced by calcMaintenanceRespiration(), calculateFluxes(), ensureNonNegativeStocks(), evapSoilFluxes(), litterInputPool(), microbeGrowth(), moisture(), moisture_bwb(), moisture_pm(), optionsSet(), outputState(), pastLeafGrowth(), printModelComponents(), readClimData(), readOptions(), setupModel(), simpleWaterFlow(), soilDegradation(), soilWaterFluxes(), updateState(), and updateTrackers().
outputPtrs
double* outputPtrs[MAX_DATA_TYPES] static
Definition at line 493 of file SIPNEToptsIn/sipnet.c.
Referenced by runModelNoOut(), and setupOutputPointers().
params
Params params static
Definition at line 484 of file SIPNEToptsIn/sipnet.c.
Referenced by calcLightEff2(), calcLightEff3(), calcMaintenanceRespiration(), calcPrecip(), calculateFluxes(), ensureAllocation(), evapSoilFluxes(), initTrackers(), leafFluxes(), microbeGrowth(), microbeQualityEfficiency(), moisture(), moisture_bwb(), moisture_pm(), pastLeafFall(), pastLeafGrowth(), potPsn(), readParamData(), setupModel(), simpleWaterFlow(), snowPack(), soilDegradation(), soilWaterFluxes(), transSoilDrainage(), updateTrackers(), vegResp(), vegResp2(), and woodLitterF().
phenologyTrackers
PhenologyTrackers phenologyTrackers static
Definition at line 487 of file SIPNEToptsIn/sipnet.c.
Referenced by initPhenologyTrackers(), and leafFluxes().
trackers
Trackers trackers static
Definition at line 486 of file SIPNEToptsIn/sipnet.c.
Referenced by initTrackers(), microbeGrowth(), outputState(), outputStatecsv(), setupModel(), setupOutputPointers(), and updateTrackers().