SIPNET: context.c File Reference
context.c File Reference
#include "context.h"
#include <ctype.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include "exitCodes.h"
#include "logging.h"
Macros
#define DEFAULT_INPUT_FILE "sipnet.in"
#define DEFAULT_FILE_NAME "sipnet"
#define NO_DEFAULT_FILE ""
#define ARG_OFF 0
#define ARG_ON 1
#define FLAG_YES 1
#define FLAG_NO 0
Functions
void initContext (void)
void nameToKey (const char *name)
struct context_metadata * getContextMetadata (const char *name)
void createContextMetadata (const char *name, const char *printName, context_source_t source, context_type_t type, void *value, int isFlag)
void updateIntContext (const char *name, int value, context_source_t source)
void updateCharContext (const char *name, const char *value, context_source_t source)
int hasSourcePrecedence (struct context_metadata *s, context_source_t newSource)
char * getContextSourceString (context_source_t src)
int by_name (const struct context_metadata *a, const struct context_metadata *b)
void validateFilename (void)
void validateContext (void)
void printConfig (FILE *outFile)
Variables
struct Context ctx
static char keyName [CONTEXT_CHAR_MAXLEN]
Macro Definition Documentation
ARG_OFF
#define ARG_OFF 0
Definition at line 14 of file context.c.
ARG_ON
#define ARG_ON 1
Definition at line 15 of file context.c.
DEFAULT_FILE_NAME
#define DEFAULT_FILE_NAME "sipnet"
Definition at line 12 of file context.c.
DEFAULT_INPUT_FILE
#define DEFAULT_INPUT_FILE "sipnet.in"
Definition at line 11 of file context.c.
FLAG_NO
#define FLAG_NO 0
Definition at line 17 of file context.c.
FLAG_YES
#define FLAG_YES 1
Definition at line 16 of file context.c.
NO_DEFAULT_FILE
#define NO_DEFAULT_FILE ""
Definition at line 13 of file context.c.
Function Documentation
by_name()
int by_name (const struct context_metadata * a, const struct context_metadata * b)
Definition at line 162 of file context.c.
References context_metadata::keyName.
Referenced by printConfig().
createContextMetadata()
void createContextMetadata (const char * name, const char * printName, context_source_t source, context_type_t type, void * value, int isFlag)
Definition at line 87 of file context.c.
References ctx, EXIT_CODE_INTERNAL_ERROR, HASH_ADD_STR, HASH_FIND_STR, context_metadata::isFlag, keyName, context_metadata::keyName, Context::metaMap, nameToKey(), context_metadata::printName, context_metadata::source, context_metadata::type, and context_metadata::value.
getContextMetadata()
struct context_metadata * getContextMetadata (const char * name)
Definition at line 80 of file context.c.
References ctx, HASH_FIND_STR, keyName, Context::metaMap, and nameToKey().
Referenced by checkCLINameMap(), and readInputFile().
getContextSourceString()
char * getContextSourceString (context_source_t src)
Definition at line 144 of file context.c.
References CTX_CALCULATED, CTX_COMMAND_LINE, CTX_CONTEXT_FILE, CTX_DEFAULT, and CTX_TEST.
Referenced by printConfig().
hasSourcePrecedence()
int hasSourcePrecedence (struct context_metadata * s, context_source_t newSource)
Definition at line 137 of file context.c.
References context_metadata::source.
Referenced by updateCharContext(), and updateIntContext().
initContext()
void initContext (void)
Initialize the global context struct with default values
Definition at line 25 of file context.c.
References ARG_OFF, ARG_ON, Context::climFile, CREATE_CHAR_CONTEXT, CREATE_INT_CONTEXT, ctx, DEFAULT_FILE_NAME, DEFAULT_INPUT_FILE, Context::doMainOutput, Context::doSingleOutputs, Context::dumpConfig, events, Context::fileName, FLAG_YES, Context::gdd, Context::growthResp, Context::inputFile, Context::leafWater, Context::litterPool, Context::metaMap, Context::microbes, NO_DEFAULT_FILE, Context::outConfigFile, Context::outFile, Context::paramFile, Context::printHeader, Context::quiet, Context::snow, Context::soilPhenol, and Context::waterHResp.
Referenced by main().
nameToKey()
void nameToKey (const char * name)
Definition at line 68 of file context.c.
References keyName.
Referenced by createContextMetadata(), getContextMetadata(), updateCharContext(), and updateIntContext().
printConfig()
void printConfig (FILE * outFile)
Definition at line 196 of file context.c.
References by_name(), ctx, CTX_CHAR, CTX_INT, EXIT_CODE_INTERNAL_ERROR, getContextSourceString(), HASH_SORT, context_metadata::hh, Context::metaMap, UT_hash_handle::next, Context::printHeader, context_metadata::printName, context_metadata::source, context_metadata::type, and context_metadata::value.
Referenced by main().
updateCharContext()
void updateCharContext (const char * name, const char * value, context_source_t source)
Definition at line 122 of file context.c.
References CONTEXT_CHAR_MAXLEN, ctx, EXIT_CODE_INTERNAL_ERROR, HASH_FIND_STR, hasSourcePrecedence(), keyName, Context::metaMap, nameToKey(), context_metadata::source, and context_metadata::value.
Referenced by main(), parseCommandLineArgs(), and readInputFile().
updateIntContext()
void updateIntContext (const char * name, int value, context_source_t source)
Definition at line 108 of file context.c.
References ctx, EXIT_CODE_INTERNAL_ERROR, HASH_FIND_STR, hasSourcePrecedence(), keyName, Context::metaMap, nameToKey(), context_metadata::source, and context_metadata::value.
Referenced by parseCommandLineArgs(), and readInputFile().
validateContext()
void validateContext (void)
Definition at line 183 of file context.c.
References ctx, EXIT_CODE_BAD_PARAMETER_VALUE, Context::gdd, logError, and Context::soilPhenol.
Referenced by main().
validateFilename()
void validateFilename (void)
Definition at line 167 of file context.c.
References ctx, EXIT_CODE_BAD_PARAMETER_VALUE, Context::fileName, and FILENAME_MAXLEN.
Referenced by readInputFile().
Variable Documentation
ctx
struct Context ctx
Definition at line 19 of file context.c.
Referenced by calcMaintenanceRespiration(), calcPrecip(), calculateFluxes(), checkAllRead(), checkCLINameMap(), checkRuntype(), cleanupModel(), createContextMetadata(), ensureNonNegativeStocks(), getContextMetadata(), initContext(), initEvents(), logprint(), main(), microbeGrowth(), parseCommandLineArgs(), pastLeafGrowth(), printConfig(), processEvents(), readClimData(), readInputFile(), readParamData(), setupModel(), soilBreakdown(), soilDegradation(), updateCharContext(), updateIntContext(), validateContext(), and validateFilename().
keyName
char keyName[CONTEXT_CHAR_MAXLEN] static
Definition at line 22 of file context.c.
Referenced by createContextMetadata(), getContextMetadata(), nameToKey(), updateCharContext(), and updateIntContext().