SIPNET: sipnet.c File Reference
sipnet.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include "common/util.h"
#include "sipnet.h"
#include "runmean.h"
#include "outputItems.h"
#include "modelStructures.h"
#include "events.h"
#include "exitCodes.h"
Data Structures
struct ClimateVars
struct Parameters
struct Environment
struct FluxVars
struct TrackerVars
struct PhenologyTrackersStruct
Macros
#define CSV_OUTPUT 0
#define ALTERNATIVE_TRANS 0
#define BALL_BERRY 0
#define PENMAN_MONTEITH_TRANS 0
#define GROWTH_RESP 0
#define LLOYD_TAYLOR 0
#define SEASONAL_R_SOIL 0 && !LLOYD_TAYLOR
#define WATER_PSN 1
#define WATER_HRESP 1
#define DAYCENT_WATER_HRESP 0 && WATER_HRESP
#define MODEL_WATER 1
#define COMPLEX_WATER 1 && MODEL_WATER
#define LITTER_WATER 0 && (COMPLEX_WATER)
#define LITTER_WATER_DRAINAGE 1 && (LITTER_WATER)
#define LEAF_WATER 0 && (COMPLEX_WATER)
#define SNOW (1 || (COMPLEX_WATER)) && MODEL_WATER
#define GDD 1
#define SOIL_PHENOL 0 && !GDD
#define SOIL_MULTIPOOL 0 && !LITTER_POOL
#define NUMBER_SOIL_CARBON_POOLS 3
#define SOIL_QUALITY 0 && SOIL_MULTIPOOL
#define MICROBES 0 && !SOIL_MULTIPOOL
#define STOICHIOMETRY 0 && MICROBES
#define C_WEIGHT 12.0
#define TEN_6 1000000.0
#define TEN_9 1000000000.0
#define SEC_PER_DAY 86400.0
#define MEAN_NPP_DAYS 5
#define MEAN_NPP_MAX_ENTRIES (MEAN_NPP_DAYS * 50)
#define MEAN_GPP_SOIL_DAYS 5
#define MEAN_GPP_SOIL_MAX_ENTRIES (MEAN_GPP_SOIL_DAYS * 50)
#define MEAN_FPAR_DAYS 1
#define MEAN_FPAR_MAX_ENTRIES (MEAN_FPAR_DAYS * 24)
#define LAMBDA 2501000.
#define LAMBDA_S 2835000.
#define RHO 1.3
#define CP 1005.
#define GAMMA 66.
#define E_STAR_SNOW 0.6
#define TINY 0.000001
#define NUM_CLIM_FILE_COLS 14
#define NUM_PARAMS (sizeof(Params) / sizeof(double))
Typedefs
typedef struct ClimateVars ClimateNode
typedef struct Parameters Params
typedef struct Environment Envi
typedef struct FluxVars Fluxes
typedef struct TrackerVars Trackers
typedef struct PhenologyTrackersStruct PhenologyTrackers
Functions
int * readClimData (char *climFile, int numLocs)
int readParamData (SpatialParams **spatialParamsPtr, char *paramFile, char *spatialParamFile)
void outputHeader (FILE *out)
void outputState (FILE *out, int loc, int year, int day, double time)
void outputStatecsv (FILE *out, int loc, int year, int day, double time)
void freeClimateList (int numLocs)
void calcLightEff (double *lightEff, double lai, double par)
Compute canopy light effect using Simpson's rule.
void potPsn (double *potGrossPsn, double *baseFolResp, double lai, double tair, double vpd, double par, int day)
void moisture_bwb (double *trans, double *dWater, double potGrossPsn, double vpd, double vPress, double plantLeafC, double leafCSpWt, double soilWater)
void moisture_pm (double *trans, double *dWater, double potGrossPsn, double vpd, double soilWater)
void moisture (double *trans, double *dWater, double potGrossPsn, double vpd, double soilWater)
int pastLeafGrowth (void)
int pastLeafFall (void)
void leafFluxes (double *leafCreation, double *leafLitter, double plantLeafC)
void simpleWaterFlow (double *rain, double *snowFall, double *immedEvap, double *snowMelt, double *sublimation, double *fastFlow, double *evaporation, double *topDrainage, double *bottomDrainage, double water, double snow, double precip, double temp, double length, double trans)
void calcPrecip (double *rain, double *snowFall, double *immedEvap, double lai)
void snowPack (double *snowMelt, double *sublimation, double snowFall)
void evapSoilFluxes (double *fastFlow, double *evaporation, double *drainage, double water, double whc, double netRain, double snowMelt, double fluxesOut)
void transSoilDrainage (double *bottomDrainage, double topDrainage, double trans, double soilWater)
void soilWaterFluxes (double *fastFlow, double *evaporation, double *topDrainage, double *bottomDrainage, double netRain, double snowMelt, double trans, double litterWater, double soilWater)
void getGpp (double *gpp, double potGrossPsn, double dWater)
void vegResp (double *folResp, double *woodResp, double baseFolResp)
void calcRootResp (double *rootResp, double respQ10, double baseRate, double poolSize)
void vegResp2 (double *folResp, double *woodResp, double *growthResp, double baseFolResp, double gpp)
void ensureAllocation (void)
void calcMaintenanceRespiration (double tsoil, double water, double whc)
double microbeQualityEfficiency (double soilQuality)
void microbeGrowth (void)
int litterInputPool (double qualityComponent)
void soilDegradation (void)
double woodLitterF (double plantWoodC)
void calculateFluxes (void)
void initTrackers (void)
void ensureNonNegative (double *var, double minVal)
void ensureNonNegativeStocks (void)
void updateTrackers (double oldSoilWater)
void processEvents (void)
void updateState (void)
void initPhenologyTrackers (void)
void setupModel (SpatialParams *spatialParams, int loc)
void setupEvents (int currLoc)
void runModelOutput (FILE *out, OutputItems *outputItems, int printHeader, SpatialParams *spatialParams, int loc)
void runModelNoOut (double **outArray, int numDataTypes, int dataTypeIndices[], SpatialParams *spatialParams, int loc)
void sensTest (FILE *out, OutputItems *outputItems, int paramNum, double low, double high, int numRuns, SpatialParams *spatialParams, int loc)
void printModelComponents (FILE *out)
char ** getDataTypeNames (void)
void setupOutputPointers (void)
void setupOutputItems (OutputItems *outputItems)
int initModel (SpatialParams **spatialParams, int **steps, char *paramFile, char *climFile)
void initEvents (char *eventFile, int numLocs)
void cleanupModel (int numLocs)
Variables
static ClimateNode ** firstClimates
static Params params
static Envi envi
static Trackers trackers
static PhenologyTrackers phenologyTrackers
static MeanTracker * meanNPP
static MeanTracker * meanGPP
static MeanTracker * meanFPAR
static ClimateNode * climate
static Fluxes fluxes
static double * outputPtrs [MAX_DATA_TYPES]
static EventNode ** events
static EventNode * locEvent
Macro Definition Documentation
ALTERNATIVE_TRANS
#define ALTERNATIVE_TRANS 0
Definition at line 32 of file sipnet.c.
BALL_BERRY
#define BALL_BERRY 0
Definition at line 35 of file sipnet.c.
C_WEIGHT
#define C_WEIGHT 12.0
Definition at line 143 of file sipnet.c.
COMPLEX_WATER
#define COMPLEX_WATER 1 && MODEL_WATER
Definition at line 75 of file sipnet.c.
CP
#define CP 1005.
Definition at line 167 of file sipnet.c.
CSV_OUTPUT
#define CSV_OUTPUT 0
Definition at line 28 of file sipnet.c.
DAYCENT_WATER_HRESP
#define DAYCENT_WATER_HRESP 0 && WATER_HRESP
Definition at line 68 of file sipnet.c.
E_STAR_SNOW
#define E_STAR_SNOW 0.6
Definition at line 169 of file sipnet.c.
GAMMA
#define GAMMA 66.
Definition at line 168 of file sipnet.c.
GDD
#define GDD 1
Definition at line 106 of file sipnet.c.
GROWTH_RESP
#define GROWTH_RESP 0
Definition at line 46 of file sipnet.c.
LAMBDA
#define LAMBDA 2501000.
Definition at line 164 of file sipnet.c.
LAMBDA_S
#define LAMBDA_S 2835000.
Definition at line 165 of file sipnet.c.
LEAF_WATER
#define LEAF_WATER 0 && (COMPLEX_WATER)
Definition at line 97 of file sipnet.c.
LITTER_WATER
#define LITTER_WATER 0 && (COMPLEX_WATER)
Definition at line 81 of file sipnet.c.
LITTER_WATER_DRAINAGE
#define LITTER_WATER_DRAINAGE 1 && (LITTER_WATER)
Definition at line 92 of file sipnet.c.
LLOYD_TAYLOR
#define LLOYD_TAYLOR 0
Definition at line 49 of file sipnet.c.
MEAN_FPAR_DAYS
#define MEAN_FPAR_DAYS 1
Definition at line 159 of file sipnet.c.
MEAN_FPAR_MAX_ENTRIES
#define MEAN_FPAR_MAX_ENTRIES (MEAN_FPAR_DAYS * 24)
Definition at line 160 of file sipnet.c.
MEAN_GPP_SOIL_DAYS
#define MEAN_GPP_SOIL_DAYS 5
Definition at line 154 of file sipnet.c.
MEAN_GPP_SOIL_MAX_ENTRIES
#define MEAN_GPP_SOIL_MAX_ENTRIES (MEAN_GPP_SOIL_DAYS * 50)
Definition at line 155 of file sipnet.c.
MEAN_NPP_DAYS
#define MEAN_NPP_DAYS 5
Definition at line 149 of file sipnet.c.
MEAN_NPP_MAX_ENTRIES
#define MEAN_NPP_MAX_ENTRIES (MEAN_NPP_DAYS * 50)
Definition at line 150 of file sipnet.c.
MICROBES
#define MICROBES 0 && !SOIL_MULTIPOOL
Definition at line 129 of file sipnet.c.
MODEL_WATER
#define MODEL_WATER 1
Definition at line 71 of file sipnet.c.
NUM_CLIM_FILE_COLS
#define NUM_CLIM_FILE_COLS 14
Definition at line 217 of file sipnet.c.
NUM_PARAMS
#define NUM_PARAMS (sizeof(Params) / sizeof(double))
Definition at line 404 of file sipnet.c.
NUMBER_SOIL_CARBON_POOLS
#define NUMBER_SOIL_CARBON_POOLS 3
Definition at line 120 of file sipnet.c.
PENMAN_MONTEITH_TRANS
#define PENMAN_MONTEITH_TRANS 0
Definition at line 39 of file sipnet.c.
RHO
#define RHO 1.3
Definition at line 166 of file sipnet.c.
SEASONAL_R_SOIL
#define SEASONAL_R_SOIL 0 && !LLOYD_TAYLOR
Definition at line 56 of file sipnet.c.
SEC_PER_DAY
#define SEC_PER_DAY 86400.0
Definition at line 146 of file sipnet.c.
SNOW
#define SNOW (1 || (COMPLEX_WATER)) && MODEL_WATER
Definition at line 101 of file sipnet.c.
SOIL_MULTIPOOL
#define SOIL_MULTIPOOL 0 && !LITTER_POOL
Definition at line 115 of file sipnet.c.
SOIL_PHENOL
#define SOIL_PHENOL 0 && !GDD
Definition at line 109 of file sipnet.c.
SOIL_QUALITY
#define SOIL_QUALITY 0 && SOIL_MULTIPOOL
Definition at line 125 of file sipnet.c.
STOICHIOMETRY
#define STOICHIOMETRY 0 && MICROBES
Definition at line 133 of file sipnet.c.
TEN_6
#define TEN_6 1000000.0
Definition at line 144 of file sipnet.c.
TEN_9
#define TEN_9 1000000000.0
Definition at line 145 of file sipnet.c.
TINY
#define TINY 0.000001
Definition at line 173 of file sipnet.c.
WATER_HRESP
#define WATER_HRESP 1
Definition at line 65 of file sipnet.c.
WATER_PSN
#define WATER_PSN 1
Definition at line 62 of file sipnet.c.
Typedef Documentation
ClimateNode
typedef struct ClimateVars ClimateNode
Definition at line 181 of file sipnet.c.
Envi
typedef struct Environment Envi
Fluxes
typedef struct FluxVars Fluxes
Params
typedef struct Parameters Params
PhenologyTrackers
typedef struct PhenologyTrackersStruct PhenologyTrackers
Trackers
typedef struct TrackerVars Trackers
Function Documentation
calcLightEff()
void calcLightEff (double * lightEff, double lai, double par)
Compute canopy light effect using Simpson's rule.
Similar to light attenuation in PnET, first calculate light intensity and then the light effect lightEFF for each layer.
Integrating Light Effect over the canopy, from top to bottom, approximated numerically using Simpson's method. Simpson's rule requires an odd number of points, thus NUM_LAYERS must be EVEN because we loop from layer = 0 to layer = NUM_LAYERS
Simpson's rule approximates the integral as: (h/3) * (y(0) + 4y(1) + 2y(2) + 4y(3) + ... + 2y(n-2) + 4y(n-1) + y(n)), where h is the distance between each x value (here h = 1/NUM_LAYERS). We keep track of the running sum in cumLightEff.
cumLai is 0 at the canopy top and equals total LAI at the bottom.
Note: SIPNET is not a multi-layer model; this function derives a canopyaveraged light effect that is then used to calculate calculate GPP for the whole canopy.
Parameters
[out] lightEff Canopy average light effect.
[in] lai Leaf area index (m^2 leaf/m^2 ground).
[in] par Incoming Photosynthetically Active Radiation (PAR).
Definition at line 1044 of file sipnet.c.
References addValueToMeanTracker(), Parameters::attenuation, climate, Parameters::halfSatPar, ClimateVars::length, meanFPAR, and params.
Referenced by potPsn().
calcMaintenanceRespiration()
void calcMaintenanceRespiration (double tsoil, double water, double whc)
Definition at line 1848 of file sipnet.c.
References Parameters::baseMicrobeResp, Parameters::baseSoilResp, Parameters::baseSoilRespCold, climate, Parameters::coldSoilThreshold, envi, fluxes, FluxVars::maintRespiration, Environment::microbeC, Parameters::microbeQ10, NUMBER_SOIL_CARBON_POOLS, params, Environment::soil, Parameters::soilRespMoistEffect, Parameters::soilRespQ10, Parameters::soilRespQ10Cold, and ClimateVars::tsoil.
Referenced by soilDegradation().
calcPrecip()
void calcPrecip (double * rain, double * snowFall, double * immedEvap, double lai)
Definition at line 1544 of file sipnet.c.
References climate, Parameters::immedEvapFrac, Parameters::leafPoolDepth, ClimateVars::length, params, ClimateVars::precip, and ClimateVars::tair.
Referenced by calculateFluxes().
calcRootResp()
void calcRootResp (double * rootResp, double respQ10, double baseRate, double poolSize)
Definition at line 1802 of file sipnet.c.
References climate, and ClimateVars::tsoil.
Referenced by calculateFluxes().
calculateFluxes()
void calculateFluxes (void)
Definition at line 2144 of file sipnet.c.
References Parameters::baseCoarseRootResp, Parameters::baseFineRootResp, FluxVars::bottomDrainage, calcPrecip(), calcRootResp(), climate, Environment::coarseRootC, FluxVars::coarseRootCreation, Parameters::coarseRootExudation, FluxVars::coarseRootLoss, Parameters::coarseRootQ10, Parameters::coarseRootTurnoverRate, ClimateVars::day, envi, FluxVars::evaporation, FluxVars::fastFlow, Parameters::fineRootAllocation, Environment::fineRootC, FluxVars::fineRootCreation, Parameters::fineRootExudation, FluxVars::fineRootLoss, Parameters::fineRootQ10, Parameters::fineRootTurnoverRate, fluxes, Parameters::fracLitterRespired, getGpp(), getMeanTrackerMean(), FluxVars::immedEvap, Parameters::leafAllocation, FluxVars::leafCreation, Parameters::leafCSpWt, leafFluxes(), FluxVars::leafLitter, ClimateVars::length, Environment::litter, Parameters::litterBreakdownRate, FluxVars::litterToSoil, Environment::litterWater, Parameters::litterWHC, meanGPP, meanNPP, Parameters::microbePulseEff, moisture(), ClimateVars::par, params, FluxVars::photosynthesis, Environment::plantLeafC, Environment::plantWoodC, potPsn(), ClimateVars::precip, FluxVars::rain, FluxVars::rCoarseRoot, FluxVars::rFineRoot, FluxVars::rLeaf, FluxVars::rLitter, FluxVars::rVeg, FluxVars::rWood, simpleWaterFlow(), Environment::snow, FluxVars::snowFall, FluxVars::snowMelt, snowPack(), FluxVars::soilPulse, Parameters::soilRespQ10, Environment::soilWater, soilWaterFluxes(), ClimateVars::soilWetness, Parameters::soilWHC, FluxVars::sublimation, ClimateVars::tair, FluxVars::topDrainage, FluxVars::transpiration, ClimateVars::tsoil, vegResp(), vegResp2(), ClimateVars::vpd, Parameters::woodAllocation, FluxVars::woodCreation, FluxVars::woodLitter, and woodLitterF().
Referenced by updateState().
cleanupModel()
void cleanupModel (int numLocs)
Definition at line 3197 of file sipnet.c.
References deallocateMeanTracker(), freeClimateList(), meanFPAR, meanGPP, meanNPP, and numLocs.
Referenced by main().
ensureAllocation()
void ensureAllocation (void)
Definition at line 1833 of file sipnet.c.
References Parameters::coarseRootAllocation, EXIT_CODE_BAD_PARAMETER_VALUE, Parameters::fineRootAllocation, Parameters::leafAllocation, params, and Parameters::woodAllocation.
Referenced by setupModel().
ensureNonNegative()
void ensureNonNegative (double * var, double minVal)
Definition at line 2367 of file sipnet.c.
Referenced by ensureNonNegativeStocks().
ensureNonNegativeStocks()
void ensureNonNegativeStocks (void)
Definition at line 2383 of file sipnet.c.
References Environment::coarseRootC, ensureNonNegative(), envi, Environment::fineRootC, Environment::litter, Environment::litterWater, Environment::microbeC, NUMBER_SOIL_CARBON_POOLS, Environment::plantLeafC, Environment::plantWoodC, Environment::snow, Environment::soil, Environment::soilWater, and TINY.
Referenced by updateState().
evapSoilFluxes()
void evapSoilFluxes (double * fastFlow, double * evaporation, double * drainage, double water, double whc, double netRain, double snowMelt, double fluxesOut)
Definition at line 1660 of file sipnet.c.
References climate, CP, envi, Parameters::fastFlowFrac, GAMMA, LAMBDA, ClimateVars::length, Parameters::litWaterDrainRate, params, Parameters::rdConst, RHO, Parameters::rSoilConst1, Parameters::rSoilConst2, SEC_PER_DAY, Environment::snow, TINY, ClimateVars::vpdSoil, and ClimateVars::wspd.
Referenced by soilWaterFluxes().
freeClimateList()
void freeClimateList (int numLocs)
Definition at line 996 of file sipnet.c.
References firstClimates, ClimateVars::nextClim, and numLocs.
Referenced by cleanupModel().
getDataTypeNames()
char ** getDataTypeNames (void)
Definition at line 3041 of file sipnet.c.
References MAX_DATA_TYPES.
Referenced by main(), printDataTypeIndices(), and printDataTypeWeightIndices().
getGpp()
void getGpp (double * gpp, double potGrossPsn, double dWater)
Definition at line 1781 of file sipnet.c.
Referenced by calculateFluxes().
initEvents()
void initEvents (char * eventFile, int numLocs)
Definition at line 3189 of file sipnet.c.
References events, numLocs, and readEventData().
Referenced by main().
initModel()
int initModel (SpatialParams ** spatialParams, int ** steps, char * paramFile, char * climFile)
Definition at line 3165 of file sipnet.c.
References MEAN_FPAR_DAYS, MEAN_FPAR_MAX_ENTRIES, MEAN_GPP_SOIL_DAYS, MEAN_GPP_SOIL_MAX_ENTRIES, MEAN_NPP_DAYS, MEAN_NPP_MAX_ENTRIES, meanFPAR, meanGPP, meanNPP, newMeanTracker(), numLocs, readClimData(), readParamData(), and setupOutputPointers().
Referenced by main().
initPhenologyTrackers()
void initPhenologyTrackers (void)
Definition at line 2704 of file sipnet.c.
References climate, PhenologyTrackersStruct::didLeafFall, PhenologyTrackersStruct::didLeafGrowth, PhenologyTrackersStruct::lastYear, pastLeafFall(), pastLeafGrowth(), phenologyTrackers, and ClimateVars::year.
Referenced by setupModel().
initTrackers()
void initTrackers (void)
Definition at line 2326 of file sipnet.c.
References envi, TrackerVars::evapotranspiration, TrackerVars::fa, TrackerVars::fpar, TrackerVars::fr, TrackerVars::gpp, TrackerVars::LAI, TrackerVars::nee, TrackerVars::npp, params, TrackerVars::plantWoodC, TrackerVars::ra, TrackerVars::rAboveground, TrackerVars::rh, TrackerVars::rRoot, TrackerVars::rSoil, TrackerVars::rtot, Parameters::soilInit, Environment::soilWater, TrackerVars::soilWetnessFrac, Parameters::soilWHC, TrackerVars::totGpp, TrackerVars::totNee, TrackerVars::totNpp, TrackerVars::totRa, TrackerVars::totRh, TrackerVars::totRtot, TrackerVars::totSoilC, trackers, TrackerVars::yearlyGpp, TrackerVars::yearlyLitter, TrackerVars::yearlyNee, TrackerVars::yearlyNpp, TrackerVars::yearlyRa, TrackerVars::yearlyRh, and TrackerVars::yearlyRtot.
Referenced by setupModel().
leafFluxes()
void leafFluxes (double * leafCreation, double * leafLitter, double plantLeafC)
Definition at line 1452 of file sipnet.c.
References climate, PhenologyTrackersStruct::didLeafFall, PhenologyTrackersStruct::didLeafGrowth, Parameters::fracLeafFall, getMeanTrackerMean(), PhenologyTrackersStruct::lastYear, Parameters::leafAllocation, Parameters::leafGrowth, Parameters::leafTurnoverRate, ClimateVars::length, meanNPP, params, pastLeafFall(), pastLeafGrowth(), phenologyTrackers, and ClimateVars::year.
Referenced by calculateFluxes().
litterInputPool()
int litterInputPool (double qualityComponent)
Definition at line 1994 of file sipnet.c.
References NUMBER_SOIL_CARBON_POOLS.
Referenced by soilDegradation().
microbeGrowth()
void microbeGrowth (void)
Definition at line 1955 of file sipnet.c.
References envi, fluxes, Parameters::halfSatIngestion, Parameters::maxIngestionRate, Environment::microbeC, FluxVars::microbeIngestion, NUMBER_SOIL_CARBON_POOLS, params, Environment::soil, TrackerVars::totSoilC, and trackers.
Referenced by soilDegradation().
microbeQualityEfficiency()
double microbeQualityEfficiency (double soilQuality)
Definition at line 1950 of file sipnet.c.
References Parameters::efficiency, and params.
moisture()
void moisture (double * trans, double * dWater, double potGrossPsn, double vpd, double soilWater)
Definition at line 1362 of file sipnet.c.
References climate, Parameters::frozenSoilEff, Parameters::frozenSoilThreshold, params, TINY, ClimateVars::tsoil, Parameters::waterRemoveFrac, and Parameters::wueConst.
Referenced by calculateFluxes().
moisture_bwb()
void moisture_bwb (double * trans, double * dWater, double potGrossPsn, double vpd, double vPress, double plantLeafC, double leafCSpWt, double soilWater)
Definition at line 1173 of file sipnet.c.
References climate, envi, Parameters::frozenSoilEff, Parameters::frozenSoilThreshold, Parameters::leafCSpWt, Parameters::m_ballBerry, params, Environment::plantLeafC, TINY, ClimateVars::tsoil, ClimateVars::vpd, ClimateVars::vPress, and Parameters::waterRemoveFrac.
moisture_pm()
void moisture_pm (double * trans, double * dWater, double potGrossPsn, double vpd, double soilWater)
Definition at line 1275 of file sipnet.c.
References climate, CP, Parameters::frozenSoilEff, Parameters::frozenSoilThreshold, GAMMA, ClimateVars::par, params, Parameters::rdConst, RHO, ClimateVars::tair, TINY, ClimateVars::tsoil, Parameters::waterRemoveFrac, and ClimateVars::wspd.
outputHeader()
void outputHeader (FILE * out)
Definition at line 911 of file sipnet.c.
References envi, NUMBER_SOIL_CARBON_POOLS, and Environment::soil.
Referenced by runModelOutput().
outputState()
void outputState (FILE * out, int loc, int year, int day, double time)
Definition at line 937 of file sipnet.c.
References Environment::coarseRootC, envi, TrackerVars::evapotranspiration, Environment::fineRootC, fluxes, TrackerVars::fpar, TrackerVars::gpp, Environment::litter, Environment::litterWater, Environment::microbeC, TrackerVars::nee, TrackerVars::npp, NUMBER_SOIL_CARBON_POOLS, Environment::plantLeafC, Environment::plantWoodC, TrackerVars::ra, TrackerVars::rAboveground, TrackerVars::rh, TrackerVars::rRoot, TrackerVars::rSoil, TrackerVars::rtot, Environment::snow, Environment::soil, Environment::soilWater, TrackerVars::soilWetnessFrac, TrackerVars::totNee, TrackerVars::totSoilC, trackers, and FluxVars::transpiration.
Referenced by runModelOutput().
outputStatecsv()
void outputStatecsv (FILE * out, int loc, int year, int day, double time)
Definition at line 974 of file sipnet.c.
References envi, TrackerVars::evapotranspiration, fluxes, TrackerVars::fpar, TrackerVars::gpp, Environment::litter, Environment::litterWater, TrackerVars::nee, TrackerVars::npp, Environment::plantLeafC, Environment::plantWoodC, TrackerVars::ra, TrackerVars::rAboveground, TrackerVars::rh, TrackerVars::rRoot, TrackerVars::rSoil, TrackerVars::rtot, Environment::snow, Environment::soil, Environment::soilWater, TrackerVars::soilWetnessFrac, TrackerVars::totNee, TrackerVars::totSoilC, trackers, and FluxVars::transpiration.
pastLeafFall()
int pastLeafFall (void)
Definition at line 1441 of file sipnet.c.
References climate, ClimateVars::day, Parameters::leafOffDay, params, and ClimateVars::time.
Referenced by initPhenologyTrackers(), and leafFluxes().
pastLeafGrowth()
int pastLeafGrowth (void)
Definition at line 1417 of file sipnet.c.
References climate, ClimateVars::day, ClimateVars::gdd, Parameters::gddLeafOn, Parameters::leafOnDay, params, Parameters::soilTempLeafOn, ClimateVars::time, ClimateVars::tsoil, and ClimateVars::year.
Referenced by initPhenologyTrackers(), and leafFluxes().
potPsn()
void potPsn (double * potGrossPsn, double * baseFolResp, double lai, double tair, double vpd, double par, int day)
Definition at line 1136 of file sipnet.c.
References Parameters::aMax, Parameters::aMaxFrac, Parameters::baseFolRespFrac, C_WEIGHT, calcLightEff(), Parameters::cFracLeaf, Parameters::dVpdExp, Parameters::dVpdSlope, Parameters::leafCSpWt, params, Parameters::psnTMax, Parameters::psnTMin, SEC_PER_DAY, and TEN_9.
Referenced by calculateFluxes().
printModelComponents()
void printModelComponents (FILE * out)
Definition at line 2986 of file sipnet.c.
References ALTERNATIVE_TRANS, BALL_BERRY, COMPLEX_WATER, CSV_OUTPUT, DAYCENT_WATER_HRESP, GDD, GROWTH_RESP, LITTER_POOL, LITTER_WATER, LITTER_WATER_DRAINAGE, LLOYD_TAYLOR, MEAN_FPAR_DAYS, MEAN_GPP_SOIL_DAYS, MEAN_NPP_DAYS, MICROBES, MODEL_WATER, NUMBER_SOIL_CARBON_POOLS, PENMAN_MONTEITH_TRANS, ROOTS, SEASONAL_R_SOIL, SNOW, SOIL_MULTIPOOL, SOIL_PHENOL, SOIL_QUALITY, STOICHIOMETRY, WATER_HRESP, and WATER_PSN.
Referenced by main().
processEvents()
void processEvents (void)
Definition at line 2519 of file sipnet.c.
References IrrigationParams::amountAdded, CANOPY, climate, PlantingParams::coarseRootC, Environment::coarseRootC, EventNode::day, ClimateVars::day, envi, EventNode::eventParams, EXIT_CODE_INPUT_FILE_ERROR, EXIT_CODE_UNKNOWN_EVENT_TYPE_OR_PARAM, FERTILIZATION, PlantingParams::fineRootC, Environment::fineRootC, fluxes, HarvestParams::fractionRemovedAbove, HarvestParams::fractionRemovedBelow, HarvestParams::fractionTransferredAbove, HarvestParams::fractionTransferredBelow, HARVEST, FluxVars::immedEvap, Parameters::immedEvapFrac, IRRIGATION, PlantingParams::leafC, Environment::litter, locEvent, IrrigationParams::method, EventNode::nextEvent, params, PLANTING, Environment::plantLeafC, Environment::plantWoodC, SOIL, Environment::soilWater, TILLAGE, EventNode::type, PlantingParams::woodC, EventNode::year, and ClimateVars::year.
Referenced by updateState().
readClimData()
int * readClimData (char * climFile, int numLocs)
Definition at line 591 of file sipnet.c.
References ClimateVars::day, EXIT_CODE_INPUT_FILE_ERROR, firstClimates, ClimateVars::gdd, ClimateVars::length, ClimateVars::nextClim, NUM_CLIM_FILE_COLS, numLocs, openFile(), ClimateVars::par, ClimateVars::precip, ClimateVars::soilWetness, ClimateVars::tair, ClimateVars::time, TINY, ClimateVars::tsoil, ClimateVars::vpd, ClimateVars::vpdSoil, ClimateVars::vPress, ClimateVars::wspd, and ClimateVars::year.
Referenced by initModel().
readParamData()
int readParamData (SpatialParams ** spatialParamsPtr, char * paramFile, char * spatialParamFile)
Definition at line 780 of file sipnet.c.
References Parameters::aMax, Parameters::aMaxFrac, Parameters::attenuation, Parameters::baseCoarseRootResp, Parameters::baseFineRootResp, Parameters::baseFolRespFrac, Parameters::baseMicrobeResp, Parameters::baseSoilResp, Parameters::baseSoilRespCold, Parameters::baseVegResp, Parameters::cFracLeaf, Parameters::coarseRootExudation, Parameters::coarseRootFrac, Parameters::coarseRootQ10, Parameters::coarseRootTurnoverRate, Parameters::coldSoilThreshold, COMPLEX_WATER, DAYCENT_WATER_HRESP, Parameters::dVpdExp, Parameters::dVpdSlope, Parameters::E0, Parameters::efficiency, Parameters::fastFlowFrac, Parameters::fineRootAllocation, Parameters::fineRootExudation, Parameters::fineRootFrac, Parameters::fineRootQ10, Parameters::fineRootTurnoverRate, Parameters::fracLeafFall, Parameters::fracLitterRespired, Parameters::frozenSoilEff, Parameters::frozenSoilFolREff, Parameters::frozenSoilThreshold, GDD, Parameters::gddLeafOn, GROWTH_RESP, Parameters::growthRespFrac, Parameters::halfSatIngestion, Parameters::halfSatPar, Parameters::immedEvapFrac, initializeOneSpatialParam(), Parameters::laiInit, LEAF_WATER, Parameters::leafAllocation, Parameters::leafCSpWt, Parameters::leafGrowth, Parameters::leafOffDay, Parameters::leafOnDay, Parameters::leafPoolDepth, Parameters::leafTurnoverRate, LITTER_POOL, LITTER_WATER_DRAINAGE, Parameters::litterBreakdownRate, Parameters::litterInit, Parameters::litterWFracInit, Parameters::litterWHC, Parameters::litWaterDrainRate, LLOYD_TAYLOR, Parameters::m_ballBerry, Parameters::maxIngestionRate, Parameters::microbeInit, Parameters::microbeNC, Parameters::microbePulseEff, Parameters::microbeQ10, MICROBES, newSpatialParams(), NUM_PARAMS, numLocs, openFile(), params, PENMAN_MONTEITH_TRANS, Parameters::plantWoodInit, Parameters::psnTMin, Parameters::psnTOpt, Parameters::qualityLeaf, Parameters::qualityWood, Parameters::rdConst, readSpatialParams(), ROOTS, Parameters::rSoilConst1, Parameters::rSoilConst2, SEASONAL_R_SOIL, SNOW, Parameters::snowInit, Parameters::snowMelt, SOIL_PHENOL, SOIL_QUALITY, Parameters::soilInit, Parameters::soilRespMoistEffect, Parameters::soilRespQ10, Parameters::soilRespQ10Cold, Parameters::soilTempLeafOn, Parameters::soilWFracInit, Parameters::soilWHC, STOICHIOMETRY, Parameters::T0, Parameters::totNitrogen, Parameters::vegRespQ10, WATER_HRESP, Parameters::waterRemoveFrac, Parameters::woodAllocation, Parameters::woodTurnoverRate, and Parameters::wueConst.
Referenced by initModel().
runModelNoOut()
void runModelNoOut (double ** outArray, int numDataTypes, int dataTypeIndices[], SpatialParams * spatialParams, int loc)
Definition at line 2920 of file sipnet.c.
References climate, ClimateVars::nextClim, outputPtrs, setupModel(), and updateState().
Referenced by main().
runModelOutput()
void runModelOutput (FILE * out, OutputItems * outputItems, int printHeader, SpatialParams * spatialParams, int loc)
Definition at line 2867 of file sipnet.c.
References climate, ClimateVars::day, ClimateVars::nextClim, SpatialParamsStruct::numLocs, outputHeader(), outputState(), setupEvents(), setupModel(), terminateOutputItemLines(), ClimateVars::time, updateState(), writeOutputItemLabels(), writeOutputItemValues(), and ClimateVars::year.
Referenced by main(), and sensTest().
sensTest()
void sensTest (FILE * out, OutputItems * outputItems, int paramNum, double low, double high, int numRuns, SpatialParams * spatialParams, int loc)
Definition at line 2956 of file sipnet.c.
References runModelOutput(), setSpatialParam(), and writeOutputItemLabels().
Referenced by main().
setupEvents()
void setupEvents (int currLoc)
Definition at line 2856 of file sipnet.c.
References events, and locEvent.
Referenced by runModelOutput().
setupModel()
void setupModel (SpatialParams * spatialParams, int loc)
Definition at line 2734 of file sipnet.c.
References Parameters::baseCoarseRootResp, Parameters::baseFineRootResp, Parameters::baseMicrobeResp, Parameters::baseSoilResp, Parameters::baseSoilRespCold, Parameters::baseVegResp, climate, Environment::coarseRootC, Parameters::coarseRootFrac, Parameters::coarseRootTurnoverRate, ensureAllocation(), envi, Environment::fineRootC, Parameters::fineRootFrac, Parameters::fineRootTurnoverRate, firstClimates, initPhenologyTrackers(), initTrackers(), Parameters::laiInit, Parameters::leafCSpWt, Parameters::leafTurnoverRate, Environment::litter, Parameters::litterBreakdownRate, Parameters::litterInit, Environment::litterWater, Parameters::litterWFracInit, Parameters::litterWHC, loadSpatialParams(), Parameters::maxIngestionRate, meanFPAR, meanGPP, meanNPP, Environment::microbeC, Parameters::microbeInit, Parameters::microbePulseEff, NUMBER_SOIL_CARBON_POOLS, params, Environment::plantLeafC, Environment::plantWoodC, Parameters::plantWoodInit, Parameters::psnTMax, Parameters::psnTMin, Parameters::psnTOpt, resetMeanTracker(), Environment::snow, Parameters::snowInit, Environment::soil, Parameters::soilInit, Environment::soilWater, Parameters::soilWFracInit, Parameters::soilWHC, Parameters::totNitrogen, TrackerVars::totSoilC, trackers, and Parameters::woodTurnoverRate.
Referenced by runModelNoOut(), and runModelOutput().
setupOutputItems()
void setupOutputItems (OutputItems * outputItems)
Definition at line 3140 of file sipnet.c.
References addOutputItem(), TrackerVars::gpp, TrackerVars::nee, TrackerVars::totGpp, TrackerVars::totNee, and trackers.
Referenced by main().
setupOutputPointers()
void setupOutputPointers (void)
Definition at line 3094 of file sipnet.c.
References TrackerVars::evapotranspiration, TrackerVars::fpar, TrackerVars::gpp, TrackerVars::nee, TrackerVars::npp, outputPtrs, TrackerVars::ra, TrackerVars::rh, TrackerVars::rtot, TrackerVars::soilWetnessFrac, TrackerVars::totGpp, TrackerVars::totNee, TrackerVars::totNpp, TrackerVars::totRa, TrackerVars::totRh, TrackerVars::totRtot, trackers, TrackerVars::yearlyGpp, TrackerVars::yearlyNee, TrackerVars::yearlyNpp, TrackerVars::yearlyRa, TrackerVars::yearlyRh, and TrackerVars::yearlyRtot.
Referenced by initModel().
simpleWaterFlow()
void simpleWaterFlow (double * rain, double * snowFall, double * immedEvap, double * snowMelt, double * sublimation, double * fastFlow, double * evaporation, double * topDrainage, double * bottomDrainage, double water, double snow, double precip, double temp, double length, double trans)
Definition at line 1499 of file sipnet.c.
References params, Parameters::snowMelt, and Parameters::soilWHC.
Referenced by calculateFluxes().
snowPack()
void snowPack (double * snowMelt, double * sublimation, double snowFall)
Definition at line 1585 of file sipnet.c.
References climate, CP, E_STAR_SNOW, envi, GAMMA, LAMBDA_S, ClimateVars::length, params, Parameters::rdConst, RHO, SEC_PER_DAY, Environment::snow, Parameters::snowMelt, ClimateVars::tair, ClimateVars::vPress, and ClimateVars::wspd.
Referenced by calculateFluxes().
soilDegradation()
void soilDegradation (void)
Definition at line 1999 of file sipnet.c.
References calcMaintenanceRespiration(), climate, Environment::coarseRootC, FluxVars::coarseRootCreation, FluxVars::coarseRootLoss, Parameters::efficiency, envi, Environment::fineRootC, FluxVars::fineRootCreation, FluxVars::fineRootLoss, fluxes, FluxVars::leafLitter, ClimateVars::length, Environment::litter, litterInputPool(), FluxVars::litterToSoil, FluxVars::maintRespiration, Environment::microbeC, microbeGrowth(), FluxVars::microbeIngestion, Parameters::microbeNC, NUMBER_SOIL_CARBON_POOLS, params, Parameters::qualityLeaf, Parameters::qualityWood, FluxVars::rCoarseRoot, FluxVars::rFineRoot, FluxVars::rLitter, FluxVars::rSoil, Environment::soil, FluxVars::soilPulse, Environment::soilWater, ClimateVars::soilWetness, Parameters::soilWHC, Parameters::totNitrogen, ClimateVars::tsoil, and FluxVars::woodLitter.
Referenced by updateState().
soilWaterFluxes()
void soilWaterFluxes (double * fastFlow, double * evaporation, double * topDrainage, double * bottomDrainage, double netRain, double snowMelt, double trans, double litterWater, double soilWater)
Definition at line 1761 of file sipnet.c.
References evapSoilFluxes(), Parameters::litterWHC, params, Parameters::soilWHC, and transSoilDrainage().
Referenced by calculateFluxes().
transSoilDrainage()
void transSoilDrainage (double * bottomDrainage, double topDrainage, double trans, double soilWater)
Definition at line 1741 of file sipnet.c.
References climate, ClimateVars::length, params, and Parameters::soilWHC.
Referenced by soilWaterFluxes().
updateState()
void updateState (void)
Definition at line 2618 of file sipnet.c.
References addValueToMeanTracker(), FluxVars::bottomDrainage, calculateFluxes(), climate, FluxVars::coarseRootCreation, ensureNonNegativeStocks(), envi, FluxVars::evaporation, FluxVars::fastFlow, FluxVars::fineRootCreation, fluxes, FluxVars::immedEvap, FluxVars::leafCreation, FluxVars::leafLitter, ClimateVars::length, Environment::litterWater, meanGPP, meanNPP, FluxVars::photosynthesis, Environment::plantLeafC, Environment::plantWoodC, processEvents(), FluxVars::rain, FluxVars::rCoarseRoot, FluxVars::rFineRoot, FluxVars::rVeg, Environment::snow, FluxVars::snowFall, FluxVars::snowMelt, soilDegradation(), Environment::soilWater, FluxVars::sublimation, FluxVars::topDrainage, FluxVars::transpiration, updateTrackers(), FluxVars::woodCreation, and FluxVars::woodLitter.
Referenced by runModelNoOut(), and runModelOutput().
updateTrackers()
void updateTrackers (double oldSoilWater)
Definition at line 2425 of file sipnet.c.
References climate, envi, FluxVars::evaporation, TrackerVars::evapotranspiration, TrackerVars::fa, fluxes, TrackerVars::fpar, TrackerVars::fr, getMeanTrackerMean(), TrackerVars::gpp, FluxVars::immedEvap, TrackerVars::LAI, Parameters::leafCSpWt, FluxVars::leafLitter, ClimateVars::length, meanFPAR, TrackerVars::nee, TrackerVars::npp, NUMBER_SOIL_CARBON_POOLS, params, FluxVars::photosynthesis, Environment::plantLeafC, Environment::plantWoodC, TrackerVars::plantWoodC, TrackerVars::ra, TrackerVars::rAboveground, FluxVars::rCoarseRoot, FluxVars::rFineRoot, TrackerVars::rh, FluxVars::rLeaf, FluxVars::rLitter, TrackerVars::rRoot, FluxVars::rSoil, TrackerVars::rSoil, TrackerVars::rtot, FluxVars::rVeg, FluxVars::rWood, Environment::soil, Environment::soilWater, TrackerVars::soilWetnessFrac, Parameters::soilWHC, FluxVars::sublimation, TrackerVars::totGpp, TrackerVars::totNee, TrackerVars::totNpp, TrackerVars::totRa, TrackerVars::totRh, TrackerVars::totRtot, TrackerVars::totSoilC, trackers, FluxVars::transpiration, ClimateVars::year, TrackerVars::yearlyGpp, TrackerVars::yearlyLitter, TrackerVars::yearlyNee, TrackerVars::yearlyNpp, TrackerVars::yearlyRa, TrackerVars::yearlyRh, and TrackerVars::yearlyRtot.
Referenced by updateState().
vegResp()
void vegResp (double * folResp, double * woodResp, double baseFolResp)
Definition at line 1788 of file sipnet.c.
References Parameters::baseVegResp, climate, envi, Parameters::frozenSoilFolREff, Parameters::frozenSoilThreshold, params, Environment::plantWoodC, Parameters::psnTOpt, ClimateVars::tair, ClimateVars::tsoil, and Parameters::vegRespQ10.
Referenced by calculateFluxes().
vegResp2()
void vegResp2 (double * folResp, double * woodResp, double * growthResp, double baseFolResp, double gpp)
Definition at line 1810 of file sipnet.c.
References Parameters::baseVegResp, climate, envi, Parameters::frozenSoilFolREff, Parameters::frozenSoilThreshold, getMeanTrackerMean(), Parameters::growthRespFrac, meanNPP, params, Environment::plantWoodC, Parameters::psnTOpt, ClimateVars::tair, ClimateVars::tsoil, and Parameters::vegRespQ10.
Referenced by calculateFluxes().
woodLitterF()
double woodLitterF (double plantWoodC)
Definition at line 2139 of file sipnet.c.
References params, and Parameters::woodTurnoverRate.
Referenced by calculateFluxes().
Variable Documentation
climate
ClimateNode* climate static
Definition at line 559 of file sipnet.c.
Referenced by calcLightEff(), calcMaintenanceRespiration(), calcPrecip(), calcRootResp(), calculateFluxes(), evapSoilFluxes(), initPhenologyTrackers(), leafFluxes(), moisture(), moisture_bwb(), moisture_pm(), pastLeafFall(), pastLeafGrowth(), processEvents(), runModelNoOut(), runModelOutput(), setupModel(), snowPack(), soilDegradation(), transSoilDrainage(), updateState(), updateTrackers(), vegResp(), and vegResp2().
envi
Envi envi static
Definition at line 549 of file sipnet.c.
Referenced by calcMaintenanceRespiration(), calculateFluxes(), ensureNonNegativeStocks(), evapSoilFluxes(), initTrackers(), microbeGrowth(), moisture_bwb(), outputHeader(), outputState(), outputStatecsv(), processEvents(), setupModel(), snowPack(), soilDegradation(), updateState(), updateTrackers(), vegResp(), and vegResp2().
events
EventNode** events static
Definition at line 565 of file sipnet.c.
Referenced by initEvents(), readEventData(), and setupEvents().
firstClimates
ClimateNode** firstClimates static
Definition at line 542 of file sipnet.c.
Referenced by freeClimateList(), readClimData(), and setupModel().
fluxes
Fluxes fluxes static
Definition at line 560 of file sipnet.c.
Referenced by calcMaintenanceRespiration(), calculateFluxes(), microbeGrowth(), outputState(), outputStatecsv(), processEvents(), soilDegradation(), updateState(), and updateTrackers().
locEvent
EventNode* locEvent static
Definition at line 566 of file sipnet.c.
Referenced by processEvents(), and setupEvents().
meanFPAR
MeanTracker* meanFPAR static
Definition at line 556 of file sipnet.c.
Referenced by calcLightEff(), cleanupModel(), initModel(), setupModel(), and updateTrackers().
meanGPP
MeanTracker* meanGPP static
Definition at line 554 of file sipnet.c.
Referenced by calculateFluxes(), cleanupModel(), initModel(), setupModel(), and updateState().
meanNPP
MeanTracker* meanNPP static
Definition at line 552 of file sipnet.c.
Referenced by calculateFluxes(), cleanupModel(), initModel(), leafFluxes(), setupModel(), updateState(), and vegResp2().
outputPtrs
double* outputPtrs[MAX_DATA_TYPES] static
Definition at line 561 of file sipnet.c.
Referenced by runModelNoOut(), and setupOutputPointers().
params
Params params static
Definition at line 548 of file sipnet.c.
Referenced by calcLightEff(), calcMaintenanceRespiration(), calcPrecip(), calculateFluxes(), createEventNode(), ensureAllocation(), evapSoilFluxes(), initTrackers(), leafFluxes(), microbeGrowth(), microbeQualityEfficiency(), moisture(), moisture_bwb(), moisture_pm(), pastLeafFall(), pastLeafGrowth(), potPsn(), processEvents(), readParamData(), setupModel(), simpleWaterFlow(), snowPack(), soilDegradation(), soilWaterFluxes(), transSoilDrainage(), updateTrackers(), vegResp(), vegResp2(), and woodLitterF().
phenologyTrackers
PhenologyTrackers phenologyTrackers static
Definition at line 551 of file sipnet.c.
Referenced by initPhenologyTrackers(), and leafFluxes().
trackers
Trackers trackers static
Definition at line 550 of file sipnet.c.
Referenced by initTrackers(), microbeGrowth(), outputState(), outputStatecsv(), setupModel(), setupOutputItems(), setupOutputPointers(), and updateTrackers().