SIPNET: util.h File Reference
util.h File Reference
#include <stdio.h>
Functions
FILE * openFile (char *name, char *mode)
void seedRand (unsigned int seed, FILE *outF)
double randm ()
double * makeArray (int size)
double ** make2DArray (int nrows, int ncols)
int ** make2DIntArray (int nrows, int ncols)
void free2DArray (void **arr)
void assignArray (double *out, double *in, int n)
double sumArray (double *array, int length)
Function Documentation
assignArray()
void assignArray (double * out, double * in, int n)
Definition at line 111 of file SIPNEToptsIn/util.c.
free2DArray()
void free2DArray (void ** arr)
Definition at line 104 of file SIPNEToptsIn/util.c.
make2DArray()
double ** make2DArray (int nrows, int ncols)
Definition at line 72 of file SIPNEToptsIn/util.c.
make2DIntArray()
int ** make2DIntArray (int nrows, int ncols)
Definition at line 87 of file SIPNEToptsIn/util.c.
makeArray()
double * makeArray (int size)
Definition at line 58 of file SIPNEToptsIn/util.c.
openFile()
FILE * openFile (char * name, char * mode)
Definition at line 9 of file bintotxt.c.
References exit(), f, index, and name.
Referenced by copyFile(), countLines(), main(), metropolis(), openOutputItemFile(), readChainInfo(), readClimData(), readData(), readEventData(), readFileForAgg(), readGirdlingData(), readIndicesFile(), readNamelistInputs(), readOptions(), readParamData(), writeBestSpatialParams(), and writeChainInfo().
randm()
double randm ()
Definition at line 47 of file SIPNEToptsIn/util.c.
seedRand()
void seedRand (unsigned int seed, FILE * outF)
Definition at line 29 of file SIPNEToptsIn/util.c.
sumArray()
double sumArray (double * array, int length)
Definition at line 120 of file SIPNEToptsIn/util.c.