SIPNET: frontend.c File Reference
frontend.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <unistd.h>
#include "sipnet.h"
#include "util.h"
Macros
#define NUM_STEPS 4507
#define LOC -1
#define HEADER 0
Functions
void usage (char *progName)
int main (int argc, char *argv[])
Macro Definition Documentation
HEADER
#define HEADER 0
Definition at line 19 of file SIPNETparamsChange/frontend.c.
LOC
#define LOC -1
Definition at line 18 of file SIPNETparamsChange/frontend.c.
NUM_STEPS
#define NUM_STEPS 4507
Definition at line 14 of file SIPNETparamsChange/frontend.c.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 46 of file SIPNETparamsChange/frontend.c.
References cleanupModel(), deleteSpatialParams(), exit(), fclose(), fprintf(), free2DArray(), HEADER, i, indices, initModel(), j, k, LOC, make2DArray(), MAX_DATA_TYPES, model, NUM_STEPS, numLocs, openFile(), runModelNoOut(), runModelOutput(), sensTest(), setSpatialParam(), usage(), and value.
usage()
void usage (char * progName)
Definition at line 21 of file SIPNETparamsChange/frontend.c.
References LOC.
Referenced by main().