SIPNET: frontend.c File Reference
frontend.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "common/exitCodes.h"
#include "common/namelistInput.h"
#include "common/spatialParams.h"
#include "common/util.h"
#include "events.h"
#include "sipnet.h"
#include "outputItems.h"
#include "modelStructures.h"
Macros
#define FILE_MAXNAME 256
#define RUNTYPE_MAXNAME 16
#define INPUT_MAXNAME 64
#define INPUT_FILE "sipnet.in"
#define DO_MAIN_OUTPUT 1
#define DO_SINGLE_OUTPUTS 0
#define LOC (-1)
Functions
void checkRuntype (NamelistInputs *namelist, const char *inputFile)
void usage (char *progName)
int main (int argc, char *argv[])
Macro Definition Documentation
DO_MAIN_OUTPUT
#define DO_MAIN_OUTPUT 1
Definition at line 28 of file frontend.c.
DO_SINGLE_OUTPUTS
#define DO_SINGLE_OUTPUTS 0
Definition at line 29 of file frontend.c.
FILE_MAXNAME
#define FILE_MAXNAME 256
Definition at line 24 of file frontend.c.
INPUT_FILE
#define INPUT_FILE "sipnet.in"
Definition at line 27 of file frontend.c.
INPUT_MAXNAME
#define INPUT_MAXNAME 64
Definition at line 26 of file frontend.c.
LOC
#define LOC (-1)
Definition at line 31 of file frontend.c.
RUNTYPE_MAXNAME
#define RUNTYPE_MAXNAME 16
Definition at line 25 of file frontend.c.
Function Documentation
checkRuntype()
void checkRuntype (NamelistInputs * namelist, const char * inputFile)
Definition at line 33 of file frontend.c.
References EXIT_CODE_BAD_PARAMETER_VALUE, EXIT_CODE_INTERNAL_ERROR, locateNamelistInputItem(), NamelistInputItemStruct::ptr, strcmpIgnoreCase(), and NamelistInputItemStruct::wasRead.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 60 of file frontend.c.
References addNamelistInputItem(), checkRuntype(), cleanupModel(), deleteOutputItems(), deleteSpatialParams(), dieIfNotSet(), DO_MAIN_OUTPUT, DO_SINGLE_OUTPUTS, EVENT_IN_FILE, FILE_MAXNAME, HEADER, initEvents(), initModel(), INPUT_FILE, INPUT_MAXNAME, INT_TYPE, LOC, newNamelistInputs(), newOutputItems(), numLocs, openFile(), readNamelistInputs(), runModelOutput(), RUNTYPE_MAXNAME, setupOutputItems(), STRING_TYPE, and usage().
usage()
void usage (char * progName)
Definition at line 53 of file frontend.c.
References INPUT_FILE.
Referenced by main().