SIPNET: daylen.m File Reference
daylen.m File Reference
Functions
clear ('all')
close ('all', 'hidden')
id km: (id hrOffset)
id parFrac ()
add to put us in the middle of the timestep sza_nrm (k)
rad_nrm (k)
parA_nrm (k)
end srise_nrm (doy)
don t bother doing offset on srise and sset sset_nrm (doy)
because we only care about their difference daylen_nrm (doy)
subtract to put us in the middle of the timestep sza_leap (k)
rad_leap (k)
parA_leap (k)
end srise_leap (doy)
don t bother doing offset on srise and sset sset_leap (doy)
because we only care about their difference daylen_leap (doy)
rad_nrm (1:8688)']
parA_nrm (1:8688)']
daylen_nrm (1:181)']
find(parAY(r length ()
SAVE THE DATA save ('~/niwot/climate/potpar', 'parAY','-ascii')
save ('~/niwot/climate/daylen', 'daylenY','-ascii')
save ('~/niwot/climate/nlight', 'nlight','-ascii')
plot (timeY, parAY, timeY, par) % figure
plot(xc(87672-2:87672+2), 'o-') % xc(87672-2 plot (parAY, par,'.',[0 2200],[0 2200], 'r') % figure
hist (log(ratio))
Variables
nyears =11
Harvard forest
Niwot __pad0__
LBA km
latRad = lat*(pi/180)
omega = 0.2618
Niwot __pad1__
sunFrac = 1.0
nt_nrm =24*365
nt_leap =24*366
NORMAL YEARS for doy
eccent = 1.000110 + 0.034221*cos(dayAng) + 0.00128*sin(dayAng) + 0.000719*cos(2*dayAng) + 0.000077*sin(2*dayAng)
decl = (0.006918 - 0.399912*cos(dayAng) + 0.070257*sin(dayAng) - 0.006758*cos(2*dayAng) + 0.000907*sin(2*dayAng) - 0.002697*cos(3*dayAng) + 0.00148*sin(3*dayAng))
for hr
k = (doy - 1)*48 + hr*2 + 1
t =mod(hr+hrOffset,24)-12
end HARVARD FOREST
parA_1991 =parA_nrm(end-1559:end)
daylen_1991 =daylen_nrm(end-1559:end)
radY = [rad_1991'
rad_leap
rad_nrm
parAY = [parA_1991'
parA_leap
parA_nrm
daylenY = [daylen_1991'
daylen_leap
daylen_nrm
timeY = 1:((24*(365*11 + 3))+1560)
NIWOT __pad2__
parA_1998 = parA_nrm(end-2927:end)
daylen_1998 = daylen_nrm(end-60:end)
days for
days days for and
FOR CALCULATING STATISTICS TO CHECK POTPAR
w =find(par > 0 & parAY > 0)
ratio =(par(w)./parAY(w))
med =median(ratio)
ndays =length(parAY)/24
r = (i-1)*48+1:i*48
end nlight =nlight'
figure
xc =xcorr(parAY,par,'coeff')
Function Documentation
clear()
clear ('all')
close()
close ('all' , 'hidden')
daylen_leap()
because we only care about their difference daylen_leap (doy)
daylen_nrm() [1/2]
daylen_nrm (1:181)
daylen_nrm() [2/2]
because we only care about their difference daylen_nrm (doy)
hist()
hist (log(ratio))
km:()
id km: (id hrOffset) virtual
length()
find(parAY(r length () virtual
References i.
Referenced by fprintf(), fprintf(), if(), if(), intervaldn(), means:(), numlines(), ones(), readClimData(), setAll(), setPossiblySpatial(), simpleWaterFlow(), soilDegradation(), stepLength(), sumArray(), and updateTrackers().
parA_leap()
parA_leap (k)
parA_nrm() [1/2]
parA_nrm (1:8688)
parA_nrm() [2/2]
parA_nrm (k)
parFrac()
id parFrac () virtual
plot() [1/2]
plot(xc(87672-2:87672+2), 'o-') % xc(87672-2 plot (parAY , par , '.' , 'r')
plot() [2/2]
plot (timeY , parAY , timeY , par)
rad_leap()
rad_leap (k)
rad_nrm() [1/2]
rad_nrm (1:8688)
rad_nrm() [2/2]
rad_nrm (k)
save() [1/3]
save ('~/niwot/climate/daylen' , 'daylenY' , '-ascii')
save() [2/3]
save ('~/niwot/climate/nlight' , 'nlight' , '-ascii')
save() [3/3]
SAVE THE DATA save ('~/niwot/climate/potpar' , 'parAY' , '-ascii')
srise_leap()
end srise_leap (doy)
srise_nrm()
end srise_nrm (doy)
sset_leap()
don t bother doing offset on srise and sset sset_leap (doy)
sset_nrm()
don t bother doing offset on srise and sset sset_nrm (doy)
sza_leap()
subtract to put us in the middle of the timestep sza_leap (k)
sza_nrm()
add to put us in the middle of the timestep sza_nrm (k)
Variable Documentation
__pad0__
Niwot __pad0__
Definition at line 10 of file daylen.m.
__pad1__
Niwot __pad1__
Definition at line 25 of file daylen.m.
__pad2__
NIWOT __pad2__
Definition at line 92 of file daylen.m.
and
days days for and
Definition at line 98 of file daylen.m.
Referenced by fprintf(), it(), tsoil(), year(), years(), and years().
daylen_1991
daylen_1991 =daylen_nrm(end-1559:end)
Definition at line 84 of file daylen.m.
daylen_1998
daylen_1998 = daylen_nrm(end-60:end)
Definition at line 96 of file daylen.m.
daylen_leap
daylen_leap
Definition at line 88 of file daylen.m.
daylen_nrm
daylen_nrm
Definition at line 88 of file daylen.m.
daylenY
daylenY = [daylen_1991'
Definition at line 88 of file daylen.m.
decl
decl = (0.006918 - 0.399912*cos(dayAng) + 0.070257*sin(dayAng) - 0.006758*cos(2*dayAng) + 0.000907*sin(2*dayAng) - 0.002697*cos(3*dayAng) + 0.00148*sin(3*dayAng))
Definition at line 44 of file daylen.m.
doy
end LEAP YEARS for doy
Initial value:
=1:365
        dayAng = 2*pi*(doy-1)/365
Definition at line 41 of file daylen.m.
eccent
eccent = 1.000110 + 0.034221*cos(dayAng) + 0.00128*sin(dayAng) + 0.000719*cos(2*dayAng) + 0.000077*sin(2*dayAng)
Definition at line 43 of file daylen.m.
figure
figure
Definition at line 143 of file daylen.m.
for
days for
Definition at line 98 of file daylen.m.
forest
pi Harvard forest
Definition at line 7 of file daylen.m.
FOREST
end HARVARD FOREST
Definition at line 80 of file daylen.m.
hr
for hr
Initial value:
=1:24
    % for hr = 0.5:0.5:24 % every half hour - BAD: STARTS AT 0.5
Definition at line 45 of file daylen.m.
k
for k = (doy - 1)*48 + hr*2 + 1
Definition at line 49 of file daylen.m.
Referenced by main(), and metropolis().
km
LBA km
Definition at line 13 of file daylen.m.
latRad
latRad = lat*(pi/180)
Definition at line 19 of file daylen.m.
med
med =median(ratio)
Definition at line 122 of file daylen.m.
ndays
ndays =length(parAY)/24
Definition at line 126 of file daylen.m.
Referenced by copySubset().
nlight
end nlight =nlight'
Definition at line 134 of file daylen.m.
nt_leap
nt_leap =24*366
Definition at line 38 of file daylen.m.
nt_nrm
nt_nrm =24*365
Definition at line 37 of file daylen.m.
nyears
nyears =11
Definition at line 5 of file daylen.m.
omega
omega = 0.2618
Definition at line 20 of file daylen.m.
parA_1991
parA_1991 =parA_nrm(end-1559:end)
Definition at line 83 of file daylen.m.
parA_1998
parA_1998 = parA_nrm(end-2927:end)
Definition at line 95 of file daylen.m.
parA_leap
parA_leap
Definition at line 87 of file daylen.m.
parA_nrm
parA_nrm
Definition at line 87 of file daylen.m.
parAY
parAY = [parA_1991'
Definition at line 87 of file daylen.m.
POTPAR
FOR CALCULATING STATISTICS TO CHECK POTPAR
Definition at line 116 of file daylen.m.
r
r = (i-1)*48+1:i*48
Definition at line 131 of file daylen.m.
rad_leap
rad_leap
Definition at line 86 of file daylen.m.
rad_nrm
rad_nrm
Definition at line 86 of file daylen.m.
radY
radY = [rad_1991'
Definition at line 86 of file daylen.m.
ratio
ratio =(par(w)./parAY(w))
Definition at line 121 of file daylen.m.
sunFrac
sunFrac = 1.0
Definition at line 35 of file daylen.m.
t
t =mod(hr+hrOffset,24)-12
Definition at line 50 of file daylen.m.
Referenced by seedRand().
timeY
and last days of timeY = 1:((24*(365*11 + 3))+1560)
Definition at line 90 of file daylen.m.
w
w =find(par > 0 & parAY > 0)
Definition at line 119 of file daylen.m.
xc
xc =xcorr(parAY,par,'coeff')
Definition at line 147 of file daylen.m.