SIPNET: climfill.m File Reference
climfill.m File Reference
Functions
we use integer (equivalent to floor(dayofyear)) %time
2 *pi *hour/24. sin ()
nb (i)
badcount (wb{i})
r2a (i)
relerra (i)
r2b (i)
relerrb (i)
rhumfill (find(rhumfill< 0))=0
parfill (find(parfill< 0))=0
wspdfill (find(wspdfill< 0))=0
wdirfill (find(wdirfill >360|wdirfill< 0))=0
Variables
dat {1}=nangap(load('~/niwot/climate/tair'))
numvars =7
potpar =load('~/niwot/climate/potpar')
hour =load('~/niwot/climate/hourofday')
note __pad0__
we use hour at start = fin + 1
shouldn t make a difference day =load('~/niwot/climate/day')
note __pad1__
chour =cos(2*pi*hour/24.)
sday =sin(2*pi*(day-1)/365.25)
cday =cos(2*pi*(day-1)/365.25)
badcount =zeros(length(dat{1}),1)
for i
wb {i}=find(isnan(dat{i}))
end x =[shour chour sday cday]
go to next iteration of loop end [yg, net, sig] =nnregress(x(wg{i},:),dat{i}(wg{i}),5,1.5,1)
datfill {i}(wb{i})=nnfwd(net,x(wb{i},:))
datmod {i}=nnfwd(net,x)
end toterr =relerr.*nb
save climfill
D =cell2mat(datfill)
go to next iteration of loop end vars =setdiff((1:numvars),i)
X =[x D(:,vars) datmod{i}]
datfill2 {i}(wb{i})=nnfwd(net,X(wb{i},:))
datmod2 {i}=nnfwd(net,X)
tairfill =datfill2{1}
rhumfill =datfill2{2}
parfill =datfill2{3}
tsoilfill =datfill2{4}
ustarfill =datfill2{5}
wspdfill =datfill2{6}
wdirfill =datfill2{7}
fh2ofill =datfill2{8}
BUILD VPRESS
BUILD VPD
BUILD VPDSOIL [vpressfill, vpdfill, vpdsoilfill] = calcvpressNiwot(rhumfill, tairfill, tsoilfill)
Function Documentation
badcount()
badcount (wb{i})
integer()
we use integer (equivalent to floordayofyear)
nb()
nb (i)
parfill()
parfill (find(parfill< 0)) pure virtual
r2a()
r2a (i)
References net.
r2b()
r2b (i)
References net.
relerra()
relerra (i)
References i, and mean().
relerrb()
relerrb (i)
References i, and mean().
rhumfill()
rhumfill (find(rhumfill< 0)) pure virtual
sin()
2 *pi *hour/24. sin () virtual
wdirfill()
wdirfill (find(wdirfill >360|wdirfill< 0)) pure virtual
wspdfill()
wspdfill (find(wspdfill< 0)) pure virtual
Variable Documentation
__pad0__
note __pad0__
Definition at line 14 of file climfill.m.
__pad1__
note __pad1__
Definition at line 15 of file climfill.m.
badcount
badcount =zeros(length(dat{1}),1)
Definition at line 24 of file climfill.m.
cday
cday =cos(2*pi*(day-1)/365.25)
Definition at line 21 of file climfill.m.
chour
chour =cos(2*pi*hour/24.)
Definition at line 19 of file climfill.m.
climfill
end save climfill
Definition at line 50 of file climfill.m.
D
D =cell2mat(datfill)
Definition at line 52 of file climfill.m.
dat
dat {1}=nangap(load('~/niwot/climate/tair'))
Definition at line 2 of file climfill.m.
datfill
datfill {i}(wb{i})=nnfwd(net,x(wb{i},:))
Definition at line 44 of file climfill.m.
datfill2
datfill2 {i}(wb{i})=nnfwd(net,X(wb{i},:))
Definition at line 65 of file climfill.m.
datmod
datmod {i}=nnfwd(net,x)
Definition at line 45 of file climfill.m.
datmod2
datmod2 {i}=nnfwd(net,X)
Definition at line 66 of file climfill.m.
day
shouldn t make a difference day =load('~/niwot/climate/day')
Definition at line 15 of file climfill.m.
Referenced by aggregates(), checkEvent(), checkLocations(), copySubset(), createEventNode(), gotoStart(), main(), outputState(), outputStatecsv(), pastStart(), printEvent(), readClimData(), readClimLine(), readEventData(), year(), and years().
end
go to next iteration of loop end[yg, net, sig] =nnregress(x(wg{i},:),dat{i}(wg{i}),5,1.5,1)
Definition at line 40 of file climfill.m.
fh2ofill
fh2ofill =datfill2{8}
Definition at line 78 of file climfill.m.
hour
hour =load('~/niwot/climate/hourofday')
Definition at line 14 of file climfill.m.
i
end for i
Initial value:
=1:numvars
    wg{i}=find(~isnan(dat{i}))
Definition at line 25 of file climfill.m.
Referenced by relerra(), and relerrb().
numvars
numvars =7
Definition at line 11 of file climfill.m.
parfill
parfill =datfill2{3}
Definition at line 73 of file climfill.m.
potpar
potpar =load('~/niwot/climate/potpar')
Definition at line 13 of file climfill.m.
rhumfill
rhumfill =datfill2{2}
Definition at line 72 of file climfill.m.
sday
sday =sin(2*pi*(day-1)/365.25)
Definition at line 20 of file climfill.m.
start
fraction of valid pts in this step start = fin + 1
Definition at line 14 of file climfill.m.
tairfill
tairfill =datfill2{1}
Definition at line 71 of file climfill.m.
toterr
end toterr =relerr.*nb
Definition at line 48 of file climfill.m.
tsoilfill
tsoilfill =datfill2{4}
Definition at line 74 of file climfill.m.
ustarfill
ustarfill =datfill2{5}
Definition at line 75 of file climfill.m.
vars
go to next iteration of loop end vars =setdiff((1:numvars),i)
Definition at line 59 of file climfill.m.
VPD
BUILD VPD
Definition at line 85 of file climfill.m.
VPDSOIL
BUILD VPDSOIL[vpressfill, vpdfill, vpdsoilfill] = calcvpressNiwot(rhumfill, tairfill, tsoilfill)
Definition at line 85 of file climfill.m.
VPRESS
BUILD VPRESS
Definition at line 85 of file climfill.m.
wb
wb {i}=find(isnan(dat{i}))
Definition at line 27 of file climfill.m.
wdirfill
wdirfill =datfill2{7}
Definition at line 77 of file climfill.m.
wspdfill
wspdfill =datfill2{6}
Definition at line 76 of file climfill.m.
x
end x =[shour chour sday cday]
Definition at line 33 of file climfill.m.
X
X =[x D(:,vars) datmod{i}]
Definition at line 60 of file climfill.m.