SIPNET: climsteps.m File Reference
climsteps.m File Reference
Functions
Bill Sacks function climsteps (stepLength) % for each of tair
Bill Sacks function and take hourly data and aggregate up to timesteps of given stepLength (in hours) %(by just taking the mean across a timestep) % Assumes that(total hours)/length is an integer %(if not
indices counts[1, 2, 3] etc tairstep (i)
vpdstep (i)
parstep (i)
par is input as sum over entire timestep tsoilstep (i)
pptstep (i)
neestep (i)
id ascii ()
Variables
Bill Sacks function vpd = load('data/vpdfill')
Bill Sacks function par = load('data/parfill')
Bill Sacks function tsoil = load('data/tsoilfill')
Bill Sacks function ppt = load('data/ppt')
Bill Sacks function and nee = load('data/neefill')
Bill Sacks function and take hourly data and aggregate up to timesteps of given throws out last fraction of a time step tair = load('data/tairfill')
nhours = length(nee)
nsteps = nhours/stepLength
for i
indices counts[1, 2, 3] then [4, 5, 6]
nee is input as sum over entire timestep end transpose all matrices
vpdstep = vpdstep'
parstep = parstep'
tsoilstep = tsoilstep'
pptstep = pptstep'
neestep = neestep'
Function Documentation
ascii()
id ascii () virtual
References data.
climsteps()
Bill Sacks function climsteps (stepLength)
neestep()
neestep (i)
parstep()
parstep (i)
pptstep()
pptstep (i)
References mean().
stepLength()
Bill Sacks function and take hourly data and aggregate up to timesteps of given stepLength (in hours)
References length(), and mean().
tairstep()
indices counts[1, 2, 3] etc tairstep (i)
References mean().
tsoilstep()
par is input as sum over entire timestep tsoilstep (i)
References mean().
vpdstep()
vpdstep (i)
References mean().
Variable Documentation
i
for i
Initial value:
= 1:nsteps
    indices = ((i-1)*stepLength + 1):(i*stepLength)
Definition at line 22 of file datstuff/climsteps.m.
matrices
nee is input as sum over entire timestep end transpose all matrices
Definition at line 35 of file datstuff/climsteps.m.
nee
nee = load('data/neefill')
Definition at line 5 of file datstuff/climsteps.m.
neestep
neestep = neestep'
Definition at line 41 of file datstuff/climsteps.m.
nhours
nhours = length(nee)
Definition at line 19 of file datstuff/climsteps.m.
nsteps
nsteps = nhours/stepLength
Definition at line 20 of file datstuff/climsteps.m.
par
par = load('data/parfill')
Definition at line 5 of file datstuff/climsteps.m.
Referenced by calcLightEff(), calcLightEff2(), calcLightEff3(), main(), potPsn(), and readClimData().
parstep
parstep = parstep'
Definition at line 38 of file datstuff/climsteps.m.
ppt
ppt = load('data/ppt')
Definition at line 5 of file datstuff/climsteps.m.
pptstep
pptstep = pptstep'
Definition at line 40 of file datstuff/climsteps.m.
tair
Bill Sacks function and take hourly data and aggregate up to timesteps of given throws out last fraction of a time step tair = load('data/tairfill')
Definition at line 12 of file datstuff/climsteps.m.
Referenced by main(), potPsn(), and readClimData().
then
indices counts [1,2,3] then[4, 5, 6]
Definition at line 24 of file datstuff/climsteps.m.
tsoil
tsoil = load('data/tsoilfill')
Definition at line 5 of file datstuff/climsteps.m.
Referenced by calcMaintenanceRespiration(), main(), readClimData(), and soilBreakdown().
tsoilstep
tsoilstep = tsoilstep'
Definition at line 39 of file datstuff/climsteps.m.
vpd
vpd = load('data/vpdfill')
Definition at line 5 of file datstuff/climsteps.m.
vpdstep
vpdstep = vpdstep'
Definition at line 37 of file datstuff/climsteps.m.