SIPNET: events.h File Reference
events.h File Reference
#include <stdarg.h>
#include "common/util.h"
Data Structures
struct HarvestParams
struct IrrigationParams
struct FertilizationParams
struct PlantingParams
struct TillageParams
struct EventNode
struct EventTrackerStruct
Macros
#define EVENT_IN_FILE "events.in"
#define EVENT_OUT_FILE "events.out"
#define NUM_HARVEST_PARAMS 4
#define NUM_IRRIGATION_PARAMS 2
#define NUM_FERTILIZATION_PARAMS 3
#define NUM_PLANTING_PARAMS 4
#define NUM_TILLAGE_PARAMS 1
#define TILLAGE_THRESHOLD 0.01
#define TILLAGE_DECAY_FACTOR (1 / 30.0)
#define NUM_EVENT_CORE_PARAMS 3
Typedefs
typedef enum EventType event_type_t
typedef enum IrrigationMethod irrigation_method_t
typedef struct HarvestParams HarvestParams
typedef struct IrrigationParams IrrigationParams
typedef struct FertilizationParams FertilizationParams
typedef struct PlantingParams PlantingParams
typedef struct TillageParams TillageParams
typedef struct EventNode EventNode
typedef struct EventTrackerStruct EventTrackers
Enumerations
enum EventType {
FERTILIZATION , HARVEST , IRRIGATION , PLANTING ,
TILLAGE , UNKNOWN_EVENT
}
enum IrrigationMethod { CANOPY = 0 , SOIL = 1 , FLOOD = 2 }
Functions
const char * eventTypeToString (event_type_t type)
event_type_t eventStringToType (const char *eventTypeStr)
EventNode * readEventData (char *eventFile)
void openEventOutFile (int printHeader)
void writeEventOut (EventNode *oneEvent, int numParams,...)
Write a line to events.out for a single oneEvent.
void closeEventOutFile (void)
void initEvents (char *eventFile, int printHeader)
void setupEvents (void)
void resetEventFluxes (void)
void processEvents (void)
Process events for current location/year/day.
void updatePoolsForEvents (void)
void freeEventList (void)
void initEventTrackers (void)
void updateEventTrackers (void)
Variables
EventNode * gEvents
EventNode * gEvent
EventTrackers eventTrackers
Macro Definition Documentation
EVENT_IN_FILE
#define EVENT_IN_FILE "events.in"
Definition at line 8 of file events.h.
EVENT_OUT_FILE
#define EVENT_OUT_FILE "events.out"
Definition at line 9 of file events.h.
NUM_EVENT_CORE_PARAMS
#define NUM_EVENT_CORE_PARAMS 3
Definition at line 64 of file events.h.
NUM_FERTILIZATION_PARAMS
#define NUM_FERTILIZATION_PARAMS 3
Definition at line 40 of file events.h.
NUM_HARVEST_PARAMS
#define NUM_HARVEST_PARAMS 4
Definition at line 26 of file events.h.
NUM_IRRIGATION_PARAMS
#define NUM_IRRIGATION_PARAMS 2
Definition at line 34 of file events.h.
NUM_PLANTING_PARAMS
#define NUM_PLANTING_PARAMS 4
Definition at line 47 of file events.h.
NUM_TILLAGE_PARAMS
#define NUM_TILLAGE_PARAMS 1
Definition at line 55 of file events.h.
TILLAGE_DECAY_FACTOR
#define TILLAGE_DECAY_FACTOR (1 / 30.0)
Definition at line 62 of file events.h.
TILLAGE_THRESHOLD
#define TILLAGE_THRESHOLD 0.01
Definition at line 60 of file events.h.
Typedef Documentation
event_type_t
typedef enum EventType event_type_t
EventNode
typedef struct EventNode EventNode
Definition at line 65 of file events.h.
EventTrackers
typedef struct EventTrackerStruct EventTrackers
FertilizationParams
typedef struct FertilizationParams FertilizationParams
HarvestParams
typedef struct HarvestParams HarvestParams
irrigation_method_t
typedef enum IrrigationMethod irrigation_method_t
IrrigationParams
typedef struct IrrigationParams IrrigationParams
PlantingParams
typedef struct PlantingParams PlantingParams
TillageParams
typedef struct TillageParams TillageParams
Enumeration Type Documentation
EventType
enum EventType
Enumerator
FERTILIZATION
HARVEST
IRRIGATION
PLANTING
TILLAGE
UNKNOWN_EVENT
Definition at line 11 of file events.h.
IrrigationMethod
enum IrrigationMethod
Enumerator
CANOPY
SOIL
FLOOD
Definition at line 20 of file events.h.
Function Documentation
closeEventOutFile()
void closeEventOutFile (void)
Close the event output file
Parameters
file FILE pointer for output file
Definition at line 288 of file events.c.
References eventOutFile.
Referenced by cleanupModel().
eventStringToType()
event_type_t eventStringToType (const char * eventTypeStr)
Convert event string to corresponding enum value
Parameters
string string version of event enum type
Returns
enum value representing the event
Definition at line 158 of file events.c.
References FERTILIZATION, HARVEST, IRRIGATION, PLANTING, TILLAGE, and UNKNOWN_EVENT.
Referenced by readEventData().
eventTypeToString()
const char * eventTypeToString (event_type_t type)
Convert event enum value to corresponding string
Parameters
type enum value representing the event
Returns
string version of event enum type
Definition at line 140 of file events.c.
References EXIT_CODE_UNKNOWN_EVENT_TYPE_OR_PARAM, FERTILIZATION, HARVEST, IRRIGATION, logError, PLANTING, and TILLAGE.
Referenced by writeEventOut().
freeEventList()
void freeEventList (void)
Deallocate space used for events linked list
Definition at line 477 of file events.c.
References gEvents, and EventNode::nextEvent.
Referenced by cleanupModel().
initEvents()
void initEvents (char * eventFile, int printHeader)
Read in event data for all the model runs
Read in event data from a file with the following specification:
one line per event
all events are ordered by year/day ascending
Parameters
eventFile Name of file containing event data
Definition at line 294 of file events.c.
References ctx, Context::events, gEvents, openEventOutFile(), and readEventData().
Referenced by main().
initEventTrackers()
void initEventTrackers (void)
Initialize EventTrackers struct for tracking lingering event effects
Definition at line 491 of file events.c.
References EventTrackerStruct::d_till_mod, and eventTrackers.
Referenced by setupModel().
openEventOutFile()
void openEventOutFile (int printHeader)
Open the event output file and optionally write a header row
Parameters
printHeader Flag, non-zero value means write a header row
Returns
FILE pointer to output file
Definition at line 257 of file events.c.
References EVENT_OUT_FILE, eventOutFile, and openFile().
Referenced by initEvents().
processEvents()
void processEvents (void)
Process events for current location/year/day.
For a given year and day (as determined by the global climate pointer), process all events listed in the global events pointer for the referenced location.
For each event, modify flux variables according to the model for that event, and write a row to events.out listing the modified variables and the delta applied.
Definition at line 313 of file events.c.
References IrrigationParams::amountAdded, CANOPY, climate, PlantingParams::coarseRootC, Environment::coarseRootC, EventTrackerStruct::d_till_mod, EventNode::day, ClimateVars::day, envi, FluxVars::eventCoarseRootC, FluxVars::eventEvap, FluxVars::eventFineRootC, FluxVars::eventLeafC, FluxVars::eventLitterC, EventNode::eventParams, FluxVars::eventSoilWater, eventTrackers, FluxVars::eventWoodC, EXIT_CODE_BAD_PARAMETER_VALUE, EXIT_CODE_INPUT_FILE_ERROR, EXIT_CODE_UNKNOWN_EVENT_TYPE_OR_PARAM, FERTILIZATION, PlantingParams::fineRootC, Environment::fineRootC, fluxes, HarvestParams::fractionRemovedAbove, HarvestParams::fractionRemovedBelow, HarvestParams::fractionTransferredAbove, HarvestParams::fractionTransferredBelow, gEvent, HARVEST, Parameters::immedEvapFrac, IRRIGATION, PlantingParams::leafC, ClimateVars::length, logError, IrrigationParams::method, EventNode::nextEvent, FertilizationParams::orgC, params, PLANTING, Environment::plantLeafC, Environment::plantWoodC, resetEventFluxes(), SOIL, TILLAGE, TillageParams::tillageEffect, EventNode::type, PlantingParams::woodC, writeEventOut(), EventNode::year, and ClimateVars::year.
Referenced by updateState().
readEventData()
EventNode * readEventData (char * eventFile)
Read event data from input filename (canonically events.in)
Format: returned data is structured as an linked list of EventNode pointers. It is assumed that the events are ordered by year and day.
Definition at line 173 of file events.c.
References createEventNode(), eventStringToType(), EXIT_CODE_INPUT_FILE_ERROR, EXIT_CODE_UNKNOWN_EVENT_TYPE_OR_PARAM, logError, logInfo, EventNode::nextEvent, NUM_EVENT_CORE_PARAMS, openFile(), and UNKNOWN_EVENT.
Referenced by initEvents().
resetEventFluxes()
void resetEventFluxes (void)
Set all event fluxes to zero
Reset all event fluxes to zero in preparation for the next climate step.
Definition at line 303 of file events.c.
References FluxVars::eventCoarseRootC, FluxVars::eventEvap, FluxVars::eventFineRootC, FluxVars::eventLeafC, FluxVars::eventLitterC, FluxVars::eventSoilWater, FluxVars::eventWoodC, and fluxes.
Referenced by processEvents().
setupEvents()
void setupEvents (void)
Initialize global event pointer
Definition at line 301 of file events.c.
References gEvent, and gEvents.
Referenced by runModelOutput().
updateEventTrackers()
void updateEventTrackers (void)
Perform any needed udpates post fluxes-and-pools updates
Definition at line 493 of file events.c.
References climate, EventTrackerStruct::d_till_mod, eventTrackers, ClimateVars::length, TILLAGE_DECAY_FACTOR, and TILLAGE_THRESHOLD.
Referenced by updateState().
updatePoolsForEvents()
void updatePoolsForEvents (void)
Update relevant environment pools after event fluxes have been calculated
Definition at line 457 of file events.c.
References climate, Environment::coarseRootC, ctx, envi, FluxVars::eventCoarseRootC, FluxVars::eventFineRootC, FluxVars::eventLeafC, FluxVars::eventLitterC, FluxVars::eventSoilWater, FluxVars::eventWoodC, Environment::fineRootC, fluxes, ClimateVars::length, Environment::litter, Context::litterPool, Environment::plantLeafC, Environment::plantWoodC, Environment::soil, and Environment::soilWater.
Referenced by updateState().
writeEventOut()
void writeEventOut (EventNode * oneEvent, int numParams, ...)
Write a line to events.out for a single oneEvent.
Writes a single oneEvent to events.out. This is a variadic function which expects to receive 2*numParams values in (char*, double) pairs after the numParams argument.
Output format:
year day event_type <param_name>=<delta>[,<param_name>=<delta>,...]
Parameters
out FILE pointer to events.out
oneEvent Pointer to oneEvent node
numParams Number of param/value pairs to write
... Pairs of (char*, double) arguments to write, 2*numParams values
Definition at line 267 of file events.c.
References EventNode::day, eventOutFile, eventTypeToString(), EventNode::type, and EventNode::year.
Referenced by processEvents().
Variable Documentation
eventTrackers
EventTrackers eventTrackers extern
Definition at line 489 of file events.c.
Referenced by calcSoilMaintRespiration(), initEventTrackers(), processEvents(), and updateEventTrackers().
gEvent
EventNode* gEvent extern
Definition at line 28 of file events.c.
Referenced by processEvents(), and setupEvents().
gEvents
EventNode* gEvents extern
Definition at line 27 of file events.c.
Referenced by freeEventList(), initEvents(), and setupEvents().