SIPNET: spatialParams.h File Reference
spatialParams.h File Reference
Data Structures
struct OneSpatialParamStruct
struct SpatialParamsStruct
Typedefs
typedef struct OneSpatialParamStruct OneSpatialParam
typedef struct SpatialParamsStruct SpatialParams
Functions
SpatialParams * newSpatialParams (int numParameters, int numLocs)
int allParamsRead (SpatialParams *spatialParams)
void readOneSpatialParam (SpatialParams *spatialParams, FILE *paramFile, FILE *spatialParamFile, char *name, double *externalLoc)
int isSpatial (SpatialParams *spatialParams, int i)
int isChangeable (SpatialParams *spatialParams, int i)
int checkSpatialParam (SpatialParams *spatialParams, int i, double value)
double getSpatialParam (SpatialParams *spatialParams, int i, int loc)
void setSpatialParam (SpatialParams *spatialParams, int i, int loc, double value)
double getSpatialParamGuess (SpatialParams *spatialParams, int i, int loc)
double getSpatialParamMin (SpatialParams *spatialParams, int i)
double getSpatialParamMax (SpatialParams *spatialParams, int i)
double getSpatialParamSigma (SpatialParams *spatialParams, int i)
double getSpatialParamKnob (SpatialParams *spatialParams, int i, int loc)
void setSpatialParamKnob (SpatialParams *spatialParams, int i, int loc, double value)
double getSpatialParamBest (SpatialParams *spatialParams, int i, int loc)
void setSpatialParamBest (SpatialParams *spatialParams, int i, int loc, double value)
void setAllSpatialParamBests (SpatialParams *spatialParams, int loc)
int randomChangeableSpatialParam (SpatialParams *spatialParams)
void loadSpatialParams (SpatialParams *spatialParams, int loc)
void resetSpatialParams (SpatialParams *spatialParams, double knob, int randomReset)
void writeBestSpatialParams (SpatialParams *spatialParams, char *paramFile, char *spatialParamFile)
void writeChangeableParamInfo (SpatialParams *spatialParams, int loc, FILE *outF)
void deleteSpatialParams (SpatialParams *spatialParams)
Typedef Documentation
OneSpatialParam
typedef struct OneSpatialParamStruct OneSpatialParam
SpatialParams
typedef struct SpatialParamsStruct SpatialParams
Function Documentation
allParamsRead()
int allParamsRead (SpatialParams * spatialParams)
Definition at line 96 of file SIPNEToptsIn/spatialParams.c.
References index, and nextUnreadParam().
Referenced by readOneSpatialParam(), and readParamData().
checkSpatialParam()
int checkSpatialParam (SpatialParams * spatialParams, int i, double value)
Definition at line 250 of file SIPNEToptsIn/spatialParams.c.
deleteSpatialParams()
void deleteSpatialParams (SpatialParams * spatialParams)
Definition at line 534 of file SIPNEToptsIn/spatialParams.c.
getSpatialParam()
double getSpatialParam (SpatialParams * spatialParams, int i, int loc)
Definition at line 259 of file SIPNEToptsIn/spatialParams.c.
getSpatialParamBest()
double getSpatialParamBest (SpatialParams * spatialParams, int i, int loc)
Definition at line 332 of file SIPNEToptsIn/spatialParams.c.
getSpatialParamGuess()
double getSpatialParamGuess (SpatialParams * spatialParams, int i, int loc)
Definition at line 279 of file SIPNEToptsIn/spatialParams.c.
getSpatialParamKnob()
double getSpatialParamKnob (SpatialParams * spatialParams, int i, int loc)
Definition at line 312 of file SIPNEToptsIn/spatialParams.c.
getSpatialParamMax()
double getSpatialParamMax (SpatialParams * spatialParams, int i)
Definition at line 295 of file SIPNEToptsIn/spatialParams.c.
getSpatialParamMin()
double getSpatialParamMin (SpatialParams * spatialParams, int i)
Definition at line 287 of file SIPNEToptsIn/spatialParams.c.
getSpatialParamSigma()
double getSpatialParamSigma (SpatialParams * spatialParams, int i)
Definition at line 303 of file SIPNEToptsIn/spatialParams.c.
isChangeable()
int isChangeable (SpatialParams * spatialParams, int i)
Definition at line 242 of file SIPNEToptsIn/spatialParams.c.
isSpatial()
int isSpatial (SpatialParams * spatialParams, int i)
Definition at line 234 of file SIPNEToptsIn/spatialParams.c.
loadSpatialParams()
void loadSpatialParams (SpatialParams * spatialParams, int loc)
Definition at line 400 of file SIPNEToptsIn/spatialParams.c.
newSpatialParams()
SpatialParams * newSpatialParams (int numParameters, int numLocs)
Definition at line 74 of file SIPNEToptsIn/spatialParams.c.
randomChangeableSpatialParam()
int randomChangeableSpatialParam (SpatialParams * spatialParams)
Definition at line 383 of file SIPNEToptsIn/spatialParams.c.
readOneSpatialParam()
void readOneSpatialParam (SpatialParams * spatialParams, FILE * paramFile, FILE * spatialParamFile, char * name, double * externalLoc)
Definition at line 119 of file SIPNEToptsIn/spatialParams.c.
References allParamsRead(), exit(), i, index, min(), name, nextUnreadParam(), numLocs, and value.
Referenced by readParamData().
resetSpatialParams()
void resetSpatialParams (SpatialParams * spatialParams, double knob, int randomReset)
Definition at line 421 of file SIPNEToptsIn/spatialParams.c.
setAllSpatialParamBests()
void setAllSpatialParamBests (SpatialParams * spatialParams, int loc)
Definition at line 351 of file SIPNEToptsIn/spatialParams.c.
setSpatialParam()
void setSpatialParam (SpatialParams * spatialParams, int i, int loc, double value)
Definition at line 270 of file SIPNEToptsIn/spatialParams.c.
setSpatialParamBest()
void setSpatialParamBest (SpatialParams * spatialParams, int i, int loc, double value)
Definition at line 343 of file SIPNEToptsIn/spatialParams.c.
setSpatialParamKnob()
void setSpatialParamKnob (SpatialParams * spatialParams, int i, int loc, double value)
Definition at line 323 of file SIPNEToptsIn/spatialParams.c.
writeBestSpatialParams()
void writeBestSpatialParams (SpatialParams * spatialParams, char * paramFile, char * spatialParamFile)
Definition at line 461 of file SIPNEToptsIn/spatialParams.c.
writeChangeableParamInfo()
void writeChangeableParamInfo (SpatialParams * spatialParams, int loc, FILE * outF)
Definition at line 500 of file SIPNEToptsIn/spatialParams.c.