SIPNET: ml-metro.h File Reference
ml-metro.h File Reference
#include "paramchange.h"
#include "spatialParams.h"
Functions
void metropolis (char *outNameBase, SpatialParams *spatialParams, int loc, double(*likely)(double *, OutputInfo *, int, SpatialParams *, double, void(*)(double **, int, int *, SpatialParams *, int), int[], int, int, double[]), void(*model)(double **, int, int *, SpatialParams *, int), double addFraction, long estSteps, int numAtOnce, int numChains, int randomStart, long numSpinUps, double paramWeight, double scaleFactor, int dataTypeIndices[], int numDataTypes, int costFunction, double dataTypeWeights[], FILE *userOut)
Function Documentation
metropolis()
void metropolis (char * outNameBase, SpatialParams * spatialParams, int loc, double(*)(double *, OutputInfo *, int, SpatialParams *, double, void(*)(double **, int, int *, SpatialParams *, int), int[], int, int, double[]) likely, void(*)(double **, int, int *, SpatialParams *, int) model, double addFraction, long estSteps, int numAtOnce, int numChains, int randomStart, long numSpinUps, double paramWeight, double scaleFactor, int dataTypeIndices[], int numDataTypes, int costFunction, double dataTypeWeights[], FILE * userOut)
Definition at line 301 of file ml-metro5.c.
References A_STAR, checkSpatialParam(), DEC, fclose(), fprintf(), free2DArray(), freeOutputInfo(), getSpatialParam(), getSpatialParamKnob(), getSpatialParamMax(), getSpatialParamMin(), isSpatial(), k, make2DArray(), makeArray(), model, newOutputInfo(), SpatialParamsStruct::numChangeableParams, numLocs, SpatialParamsStruct::numLocs, openFile(), randm(), randomChangeableSpatialParam(), readChainInfo(), reset(), scaleFactor, setAllSpatialParamBests(), setSpatialParam(), setSpatialParamKnob(), sumArray(), THRESH, writeChainInfo(), writeChangeableParamInfo(), writeHistFileBin(), and writeHistFileBinHeader().
Referenced by main().