SIPNET: txttobin.c File Reference
txttobin.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
FILE * openFile (char *name, char *mode)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 23 of file txttobin.c.
References exit(), fclose(), i, index, MAX_LINE, and openFile().
openFile()
FILE * openFile (char * name, char * mode)
Definition at line 11 of file txttobin.c.
References exit(), f, index, and name.
Referenced by main().