SIPNET: spatialParams.c File Reference
spatialParams.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include "spatialParams.h"
#include "util.h"
Functions
int nextUnreadParam (SpatialParams *spatialParams)
void setAll (double *array, int length, double value)
double getPossiblySpatial (double *array, int loc, int isSpatial)
void setPossiblySpatial (double *array, int loc, double value, int isSpatial, int length)
SpatialParams * newSpatialParams (int numParameters, int numLocs)
int allParamsRead (SpatialParams *spatialParams)
void readOneSpatialParam (SpatialParams *spatialParams, FILE *paramFile, FILE *spatialParamFile, char *name, double *externalLoc)
int isSpatial (SpatialParams *spatialParams, int i)
int isChangeable (SpatialParams *spatialParams, int i)
int checkSpatialParam (SpatialParams *spatialParams, int i, double value)
double getSpatialParam (SpatialParams *spatialParams, int i, int loc)
void setSpatialParam (SpatialParams *spatialParams, int i, int loc, double value)
double getSpatialParamGuess (SpatialParams *spatialParams, int i, int loc)
double getSpatialParamMin (SpatialParams *spatialParams, int i)
double getSpatialParamMax (SpatialParams *spatialParams, int i)
double getSpatialParamSigma (SpatialParams *spatialParams, int i)
double getSpatialParamKnob (SpatialParams *spatialParams, int i, int loc)
void setSpatialParamKnob (SpatialParams *spatialParams, int i, int loc, double value)
double getSpatialParamBest (SpatialParams *spatialParams, int i, int loc)
void setSpatialParamBest (SpatialParams *spatialParams, int i, int loc, double value)
void setAllSpatialParamBests (SpatialParams *spatialParams, int loc)
int randomChangeableSpatialParam (SpatialParams *spatialParams)
void loadSpatialParams (SpatialParams *spatialParams, int loc)
void resetSpatialParams (SpatialParams *spatialParams, double knob, int randomReset)
void writeBestSpatialParams (SpatialParams *spatialParams, char *paramFile, char *spatialParamFile)
void writeChangeableParamInfo (SpatialParams *spatialParams, int loc, FILE *outF)
void deleteSpatialParams (SpatialParams *spatialParams)
Function Documentation
allParamsRead()
int allParamsRead (SpatialParams * spatialParams)
Definition at line 96 of file SIPNEToptsIn/spatialParams.c.
References index, and nextUnreadParam().
Referenced by readOneSpatialParam(), and readParamData().
checkSpatialParam()
int checkSpatialParam (SpatialParams * spatialParams, int i, double value)
Definition at line 250 of file SIPNEToptsIn/spatialParams.c.
References getSpatialParamMax(), getSpatialParamMin(), i, index, and value.
Referenced by metropolis().
deleteSpatialParams()
void deleteSpatialParams (SpatialParams * spatialParams)
Definition at line 534 of file SIPNEToptsIn/spatialParams.c.
References i, and index.
Referenced by main().
getPossiblySpatial()
double getPossiblySpatial (double * array, int loc, int isSpatial)
Definition at line 45 of file SIPNEToptsIn/spatialParams.c.
References index, and isSpatial().
Referenced by getSpatialParam(), getSpatialParamBest(), getSpatialParamGuess(), and getSpatialParamKnob().
getSpatialParam()
double getSpatialParam (SpatialParams * spatialParams, int i, int loc)
Definition at line 259 of file SIPNEToptsIn/spatialParams.c.
References getPossiblySpatial(), i, index, and isSpatial().
Referenced by loadSpatialParams(), metropolis(), setAllSpatialParamBests(), writeChainInfo(), writeChangeableParamInfo(), writeHistFile(), and writeHistFileBin().
getSpatialParamBest()
double getSpatialParamBest (SpatialParams * spatialParams, int i, int loc)
Definition at line 332 of file SIPNEToptsIn/spatialParams.c.
References getPossiblySpatial(), i, index, and isSpatial().
Referenced by writeBestSpatialParams(), writeChainInfo(), and writeChangeableParamInfo().
getSpatialParamGuess()
double getSpatialParamGuess (SpatialParams * spatialParams, int i, int loc)
Definition at line 279 of file SIPNEToptsIn/spatialParams.c.
References getPossiblySpatial(), i, index, and isSpatial().
Referenced by resetSpatialParams(), and writeChangeableParamInfo().
getSpatialParamKnob()
double getSpatialParamKnob (SpatialParams * spatialParams, int i, int loc)
Definition at line 312 of file SIPNEToptsIn/spatialParams.c.
References getPossiblySpatial(), i, index, and isSpatial().
Referenced by metropolis(), writeChainInfo(), and writeChangeableParamInfo().
getSpatialParamMax()
double getSpatialParamMax (SpatialParams * spatialParams, int i)
Definition at line 295 of file SIPNEToptsIn/spatialParams.c.
References i, and index.
Referenced by checkSpatialParam(), main(), metropolis(), resetSpatialParams(), writeBestSpatialParams(), and writeChangeableParamInfo().
getSpatialParamMin()
double getSpatialParamMin (SpatialParams * spatialParams, int i)
Definition at line 287 of file SIPNEToptsIn/spatialParams.c.
References i, and index.
Referenced by checkSpatialParam(), main(), metropolis(), resetSpatialParams(), writeBestSpatialParams(), and writeChangeableParamInfo().
getSpatialParamSigma()
double getSpatialParamSigma (SpatialParams * spatialParams, int i)
Definition at line 303 of file SIPNEToptsIn/spatialParams.c.
References i, and index.
Referenced by writeBestSpatialParams().
isChangeable()
int isChangeable (SpatialParams * spatialParams, int i)
Definition at line 242 of file SIPNEToptsIn/spatialParams.c.
References i, and index.
Referenced by writeBestSpatialParams(), and writeChangeableParamInfo().
isSpatial()
int isSpatial (SpatialParams * spatialParams, int i)
Definition at line 234 of file SIPNEToptsIn/spatialParams.c.
References i, and index.
Referenced by getPossiblySpatial(), getSpatialParam(), getSpatialParamBest(), getSpatialParamGuess(), getSpatialParamKnob(), metropolis(), readChainInfo(), resetSpatialParams(), setAllSpatialParamBests(), setPossiblySpatial(), setSpatialParam(), setSpatialParamBest(), setSpatialParamKnob(), writeBestSpatialParams(), writeChainInfo(), and writeChangeableParamInfo().
loadSpatialParams()
void loadSpatialParams (SpatialParams * spatialParams, int loc)
Definition at line 400 of file SIPNEToptsIn/spatialParams.c.
References getSpatialParam(), i, index, and value.
Referenced by setupModel().
newSpatialParams()
SpatialParams * newSpatialParams (int numParameters, int numLocs)
Definition at line 74 of file SIPNEToptsIn/spatialParams.c.
References i, index, and numLocs.
Referenced by readParamData().
nextUnreadParam()
int nextUnreadParam (SpatialParams * spatialParams)
Definition at line 21 of file SIPNEToptsIn/spatialParams.c.
References index.
Referenced by allParamsRead(), and readOneSpatialParam().
randomChangeableSpatialParam()
int randomChangeableSpatialParam (SpatialParams * spatialParams)
Definition at line 383 of file SIPNEToptsIn/spatialParams.c.
References index.
Referenced by metropolis().
readOneSpatialParam()
void readOneSpatialParam (SpatialParams * spatialParams, FILE * paramFile, FILE * spatialParamFile, char * name, double * externalLoc)
Definition at line 119 of file SIPNEToptsIn/spatialParams.c.
References allParamsRead(), exit(), i, index, min(), name, nextUnreadParam(), numLocs, and value.
Referenced by readParamData().
resetSpatialParams()
void resetSpatialParams (SpatialParams * spatialParams, double knob, int randomReset)
Definition at line 421 of file SIPNEToptsIn/spatialParams.c.
References getSpatialParamGuess(), getSpatialParamMax(), getSpatialParamMin(), i, index, isSpatial(), numLocs, setSpatialParam(), setSpatialParamBest(), setSpatialParamKnob(), and value.
Referenced by reset().
setAll()
void setAll (double * array, int length, double value)
Definition at line 34 of file SIPNEToptsIn/spatialParams.c.
References i, index, length(), and value.
Referenced by setPossiblySpatial().
setAllSpatialParamBests()
void setAllSpatialParamBests (SpatialParams * spatialParams, int loc)
Definition at line 351 of file SIPNEToptsIn/spatialParams.c.
References getSpatialParam(), i, index, isSpatial(), setSpatialParamBest(), and value.
Referenced by metropolis().
setPossiblySpatial()
void setPossiblySpatial (double * array, int loc, double value, int isSpatial, int length)
Definition at line 57 of file SIPNEToptsIn/spatialParams.c.
References index, isSpatial(), length(), setAll(), and value.
Referenced by setSpatialParam(), setSpatialParamBest(), and setSpatialParamKnob().
setSpatialParam()
void setSpatialParam (SpatialParams * spatialParams, int i, int loc, double value)
Definition at line 270 of file SIPNEToptsIn/spatialParams.c.
References i, index, isSpatial(), setPossiblySpatial(), and value.
Referenced by main(), metropolis(), readChainInfo(), resetSpatialParams(), sensTest(), and sensTest().
setSpatialParamBest()
void setSpatialParamBest (SpatialParams * spatialParams, int i, int loc, double value)
Definition at line 343 of file SIPNEToptsIn/spatialParams.c.
References i, index, isSpatial(), setPossiblySpatial(), and value.
Referenced by readChainInfo(), resetSpatialParams(), and setAllSpatialParamBests().
setSpatialParamKnob()
void setSpatialParamKnob (SpatialParams * spatialParams, int i, int loc, double value)
Definition at line 323 of file SIPNEToptsIn/spatialParams.c.
References i, index, isSpatial(), setPossiblySpatial(), and value.
Referenced by metropolis(), readChainInfo(), and resetSpatialParams().
writeBestSpatialParams()
void writeBestSpatialParams (SpatialParams * spatialParams, char * paramFile, char * spatialParamFile)
Definition at line 461 of file SIPNEToptsIn/spatialParams.c.
References fclose(), fprintf(), getSpatialParamBest(), getSpatialParamMax(), getSpatialParamMin(), getSpatialParamSigma(), i, index, isChangeable(), isSpatial(), j, numLocs, and openFile().
Referenced by main().
writeChangeableParamInfo()
void writeChangeableParamInfo (SpatialParams * spatialParams, int loc, FILE * outF)
Definition at line 500 of file SIPNEToptsIn/spatialParams.c.
References count, fprintf(), getSpatialParam(), getSpatialParamBest(), getSpatialParamGuess(), getSpatialParamKnob(), getSpatialParamMax(), getSpatialParamMin(), i, index, isChangeable(), and isSpatial().
Referenced by metropolis(), and reset().