SIPNET: modelParams.c File Reference
modelParams.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "common/context.h"
#include "exitCodes.h"
#include "logging.h"
#include "modelParams.h"
#include "util.h"
Functions
int allParamsInitialized (ModelParams *ModelParams)
void setAll (double *array, int length, double value)
void checkAllRead (ModelParams *ModelParams)
ModelParams * newModelParams (int maxParams)
void initializeOneModelParam (ModelParams *modelParams, char *name, double *externalLoc, int isRequired)
void checkParamFormat (char *line, const char *sep)
void readModelParams (ModelParams *modelParams, FILE *paramFile)
int getnumParams (ModelParams *modelParams)
int getNumParamsRead (ModelParams *modelParams)
int locateParam (ModelParams *modelParams, char *name)
int valueSet (ModelParams *modelParams, int i)
void deleteModelParams (ModelParams *modelParams)
Function Documentation
allParamsInitialized()
int allParamsInitialized (ModelParams * ModelParams)
Definition at line 15 of file modelParams.c.
References ModelParamsStruct::maxParams, and ModelParamsStruct::numParams.
Referenced by initializeOneModelParam().
checkAllRead()
void checkAllRead (ModelParams * ModelParams)
Definition at line 38 of file modelParams.c.
References ctx, OneModelParamStruct::isRead, OneModelParamStruct::isRequired, logError, logInfo, logWarning, OneModelParamStruct::name, ModelParamsStruct::numParams, OBSOLETE_PARAM, ModelParamsStruct::params, and Context::quiet.
Referenced by readModelParams().
checkParamFormat()
void checkParamFormat (char * line, const char * sep)
Definition at line 148 of file modelParams.c.
References countFields(), and logWarning.
Referenced by readModelParams().
deleteModelParams()
void deleteModelParams (ModelParams * modelParams)
Definition at line 269 of file modelParams.c.
References ModelParamsStruct::params, and ModelParamsStruct::readIndices.
getnumParams()
int getnumParams (ModelParams * modelParams)
Definition at line 235 of file modelParams.c.
References ModelParamsStruct::numParams.
getNumParamsRead()
int getNumParamsRead (ModelParams * modelParams)
Definition at line 238 of file modelParams.c.
References ModelParamsStruct::numParamsRead.
initializeOneModelParam()
void initializeOneModelParam (ModelParams * modelParams, char * name, double * externalLoc, int isRequired)
Parameters
modelParams
name
externalLoc
isRequired
Definition at line 121 of file modelParams.c.
References allParamsInitialized(), OneModelParamStruct::isRead, OneModelParamStruct::isRequired, logError, ModelParamsStruct::maxParams, OneModelParamStruct::name, ModelParamsStruct::numParams, ModelParamsStruct::params, and OneModelParamStruct::value.
Referenced by readParamData().
locateParam()
int locateParam (ModelParams * modelParams, char * name)
Definition at line 244 of file modelParams.c.
References OneModelParamStruct::name, and ModelParamsStruct::params.
Referenced by readModelParams().
newModelParams()
ModelParams * newModelParams (int maxParams)
Definition at line 98 of file modelParams.c.
References ModelParamsStruct::maxParams, ModelParamsStruct::numParams, ModelParamsStruct::numParamsRead, ModelParamsStruct::params, and ModelParamsStruct::readIndices.
Referenced by readParamData().
readModelParams()
void readModelParams (ModelParams * modelParams, FILE * paramFile)
Definition at line 157 of file modelParams.c.
References checkAllRead(), checkParamFormat(), EXIT_CODE_BAD_PARAMETER_VALUE, EXIT_CODE_INPUT_FILE_ERROR, OneModelParamStruct::isRead, locateParam(), logError, logWarning, MODEL_PARAM_MAXNAME, ModelParamsStruct::numParamsRead, ModelParamsStruct::params, ModelParamsStruct::readIndices, stripComment(), OneModelParamStruct::value, and valueSet().
Referenced by readParamData().
setAll()
void setAll (double * array, int length, double value)
Definition at line 25 of file modelParams.c.
valueSet()
int valueSet (ModelParams * modelParams, int i)
Definition at line 265 of file modelParams.c.
References OneModelParamStruct::isRead, and ModelParamsStruct::params.
Referenced by readModelParams().