SIPNET: runmean.c File Reference
runmean.c File Reference
#include <stdlib.h>
#include "runmean.h"
Functions
MeanTracker * newMeanTracker (double initMean, double totWeight, int maxEntries)
void resetMeanTracker (MeanTracker *tracker, double initMean)
int addValueToMeanTracker (MeanTracker *tracker, double value, double weight)
double getMeanTrackerMean (MeanTracker *tracker)
void deallocateMeanTracker (MeanTracker *tracker)
Function Documentation
addValueToMeanTracker()
int addValueToMeanTracker (MeanTracker * tracker, double value, double weight)
Definition at line 61 of file runmean.c.
References MeanTrackerStruct::last, MeanTrackerStruct::length, resetMeanTracker(), MeanTrackerStruct::start, MeanTrackerStruct::sum, MeanTrackerStruct::totWeight, MeanTrackerStruct::values, and MeanTrackerStruct::weights.
Referenced by calcLightEff(), and updateState().
deallocateMeanTracker()
void deallocateMeanTracker (MeanTracker * tracker)
Definition at line 125 of file runmean.c.
References MeanTrackerStruct::values, and MeanTrackerStruct::weights.
Referenced by cleanupModel().
getMeanTrackerMean()
double getMeanTrackerMean (MeanTracker * tracker)
Definition at line 119 of file runmean.c.
References MeanTrackerStruct::sum, and MeanTrackerStruct::totWeight.
Referenced by calculateFluxes(), leafFluxes(), updateTrackers(), and vegResp2().
newMeanTracker()
MeanTracker * newMeanTracker (double initMean, double totWeight, int maxEntries)
Definition at line 22 of file runmean.c.
References MeanTrackerStruct::length, resetMeanTracker(), MeanTrackerStruct::totWeight, MeanTrackerStruct::values, and MeanTrackerStruct::weights.
Referenced by initModel().
resetMeanTracker()
void resetMeanTracker (MeanTracker * tracker, double initMean)
Definition at line 44 of file runmean.c.
References MeanTrackerStruct::last, MeanTrackerStruct::start, MeanTrackerStruct::sum, MeanTrackerStruct::totWeight, MeanTrackerStruct::values, and MeanTrackerStruct::weights.
Referenced by addValueToMeanTracker(), newMeanTracker(), and setupModel().