SIPNET: cli.h File Reference
cli.h File Reference
#include <getopt.h>
#include <stdio.h>
#include "common/context.h"
Macros
#define NUM_FLAG_OPTIONS 14
Functions
void checkCLINameMap (void)
void usage (char *progName)
void version (void)
void parseCommandLineArgs (int argc, char *argv[])
Variables
char * argNameMap [2 *NUM_FLAG_OPTIONS]
Macro Definition Documentation
NUM_FLAG_OPTIONS
#define NUM_FLAG_OPTIONS 14
Definition at line 17 of file cli.h.
Function Documentation
checkCLINameMap()
void checkCLINameMap (void)
Verify that the cli's arg-name map is valid
Verifies that everything in argNameMap maps to a valid context metadata. Does not verify that we failed to add a flag to the map. Call this after initContext()
Definition at line 162 of file cli.c.
References argNameMap, ctx, EXIT_CODE_INTERNAL_ERROR, getContextMetadata(), context_metadata::hh, context_metadata::isFlag, logInternalError, Context::metaMap, UT_hash_handle::next, and NUM_FLAG_OPTIONS.
Referenced by main().
parseCommandLineArgs()
void parseCommandLineArgs (int argc, char * argv[])
Definition at line 112 of file cli.c.
References argNameMap, ctx, CTX_COMMAND_LINE, EXIT_CODE_BAD_CLI_ARGUMENT, EXIT_CODE_SUCCESS, FILENAME_MAXLEN, long_options, Context::tmpFlag, updateCharContext(), updateIntContext(), usage(), and version().
Referenced by main().
usage()
void usage (char * progName)
Definition at line 67 of file cli.c.
Referenced by parseCommandLineArgs().
version()
void version (void)
Definition at line 109 of file cli.c.
References VERSION_STRING.
Referenced by parseCommandLineArgs().
Variable Documentation
argNameMap
char* argNameMap[2 *NUM_FLAG_OPTIONS] extern
Definition at line 48 of file cli.c.
Referenced by checkCLINameMap(), and parseCommandLineArgs().