SIPNET: transpose.c File Reference
transpose.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "util.h"
Macros
#define SEPARATORS " \t\n\r"
Functions
void usage (char *progName)
int numlines (FILE *f, int *longestLine)
void readFile (FILE *f, char **lines, int maxLength)
int countItems (char *line)
void readItems (char **lines, char ***items, int numLines, int numItems)
void outputTranspose (FILE *f, char ***items, int numLines, int numItems)
int main (int argc, char *argv[])
Macro Definition Documentation
SEPARATORS
#define SEPARATORS " \t\n\r"
Definition at line 15 of file transpose.c.
Function Documentation
countItems()
int countItems (char * line)
Definition at line 75 of file transpose.c.
References index, n, and SEPARATORS.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 137 of file transpose.c.
References countItems(), exit(), f, fclose(), i, index, numlines(), openFile(), outputTranspose(), readFile(), readItems(), and usage().
numlines()
int numlines (FILE * f, int * longestLine)
Definition at line 30 of file transpose.c.
References f, index, and length().
Referenced by main().
outputTranspose()
void outputTranspose (FILE * f, char *** items, int numLines, int numItems)
Definition at line 125 of file transpose.c.
References f, fprintf(), i, index, and j.
Referenced by main().
readFile()
void readFile (FILE * f, char ** lines, int maxLength)
Definition at line 62 of file transpose.c.
References f, i, and index.
Referenced by main().
readItems()
void readItems (char ** lines, char *** items, int numLines, int numItems)
Definition at line 100 of file transpose.c.
References exit(), i, index, j, and SEPARATORS.
Referenced by main().
usage()
void usage (char * progName)
Definition at line 18 of file transpose.c.
References index.
Referenced by main().