SIPNET: soilwetnessdn.m File Reference
soilwetnessdn.m File Reference
Functions
soilwetness(find(isfinite(soilwetness sort ()
the measured pts in this step if (length(measuredpts)>=1) % at least one measured point soilwetnessdns(i)
soilwetnessvaliddn (i)
else no measured pts soilwetnessdns (i)=0
Variables
Computes dn values for both soilwetness and soilwetnessvalid soilwetness =load('~/niwot/climate/soilwetness')
Computes dn values for both soilwetness and soilwetnessvalid take mean over measured values in that time step
Computes dn values for both soilwetness and soilwetnessvalid take mean over measured values in that time converted to fraction filled soilwetnessvalid
intervaldn =load('~/niwot/climate/intervaldn')
hours per step upperlimit = 0.95
maxsoilwetness
convert to fraction filled numsteps =length(intervaldn)
start =1
for i
multiply by since each point is hour measuredpts =find(isfinite(soilwetnessfrac(start:fin))) + (start - 1)
end soilwetnessdns = min(soilwetnessdns, 1)
soilwetnessvaliddn = soilwetnessvaliddn'
Function Documentation
if()
the measured pts in this step if (length(measuredpts)>= 1)
References length(), and mean().
soilwetnessdns()
else no measured pts soilwetnessdns (i) pure virtual
soilwetnessvaliddn()
soilwetnessvaliddn (i)
sort()
soilwetness(find(isfinite(soilwetness sort () virtual
Variable Documentation
i
for i
Initial value:
=1:numsteps
    fin=start + 2*intervaldn(i) - 1
Definition at line 17 of file soilwetnessdn.m.
intervaldn
intervaldn =load('~/niwot/climate/intervaldn')
Definition at line 7 of file soilwetnessdn.m.
maxsoilwetness
maxsoilwetness
Initial value:
= sorted(round(upperlimit*length(sorted)))
soilwetnessfrac=soilwetness/maxsoilwetness
Definition at line 11 of file soilwetnessdn.m.
measuredpts
multiply by since each point is hour measuredpts =find(isfinite(soilwetnessfrac(start:fin))) + (start - 1)
Definition at line 19 of file soilwetnessdn.m.
numsteps
convert to fraction filled numsteps =length(intervaldn)
Definition at line 14 of file soilwetnessdn.m.
soilwetness
Computes dn values for both soilwetness and soilwetnessvalid take mean over measured values in that time converted to fraction filled if NONE soilwetness =load('~/niwot/climate/soilwetness')
Definition at line 2 of file soilwetnessdn.m.
Referenced by main().
soilwetnessdns
don t let soilwetness go higher than soilwetnessdns = min(soilwetnessdns, 1)
Definition at line 31 of file soilwetnessdn.m.
soilwetnessvalid
Computes dn values for both soilwetness and soilwetnessvalid take mean over measured values in that time converted to fraction filled soilwetnessvalid
Definition at line 4 of file soilwetnessdn.m.
soilwetnessvaliddn
soilwetnessvaliddn = soilwetnessvaliddn'
Definition at line 33 of file soilwetnessdn.m.
start
end start =1
Definition at line 15 of file soilwetnessdn.m.
step
Computes dn values for both soilwetness and soilwetnessvalid take mean over measured values in that time step
Definition at line 3 of file soilwetnessdn.m.
Referenced by runModelNoOut().
upperlimit
hours per step upperlimit = 0.95
Definition at line 9 of file soilwetnessdn.m.