SIPNET: plotYears.m File Reference
plotYears.m File Reference
Functions
function plotYears (data, days, years, firstYear, lastYear, window, scaleFactor) % Given a vector of data
function and corresponding vector of years (where year(i) is the year of data(i)) % Plot data
function and corresponding vector of multiplied by for each year in a different vs fractional day of year ((JD - 1)+(hour/24))(given by days vector) %(value on x-axis gives fractional day at START of time step) % Plot only data between firstYear and lastYear(if firstYear
set up vector to assign colors to ea line if (firstYear==-1) firstYear
end if (lastYear==-1) lastYear
end figure create a new figure hold on compute sliding mean (if window=1, dataMean will equal data) dataMean
plot (daysYr, dataYr *scaleFactor, colors(yr - firstYear+1))
end legend (int2str((firstYear:lastYear)'))
Variables
function and corresponding vector of multiplied by scaleFactor
function and corresponding vector of multiplied by for each year in a different color
function and corresponding vector of multiplied by for each year in a different vs fractional day of start at first year in data
if lastYear = -1
if end at last year in vector If window
if end at last year in vector If use a sliding mean window for plotting NOTE
if end at last year in vector If use a sliding mean window for plotting can only handle years before we run out of colors !colors = ['b','g','r','c','m','k','y']
loop through years
loop through plotting each line for yr
dataYr = dataMean(i)
find subset of data and days array daysYr = days(i)
Function Documentation
if() [1/2]
set up vector to assign colors to ea line if (firstYear = =-1)
References firstYear.
if() [2/2]
end if (lastYear = =-1)
legend()
end legend (int2str((firstYear:lastYear)'))
mean()
end figure create a new figure hold on compute sliding mean (if window = 1, dataMean will equal data)
References mean().
Referenced by fprintf(), fprintf(), fprintf(), fprintf(), fprintf(), fprintf(), if(), if(), mean(), means:(), pptstep(), relerra(), relerrb(), stepLength(), tairdn(), tairstep(), tsoildn(), tsoilstep(), validptsdn(), vpddn(), vpdsoildn(), vpdstep(), vpressdn(), and wspddn().
plot()
plot (daysYr , dataYr * scaleFactor, colors(yr - firstYear+1))
plotYears()
function plotYears (data , days , years , firstYear , lastYear , window , scaleFactor)
year()
function and corresponding vector of multiplied by for each year in a different vs fractional day of year ((JD - 1)+(hour/24))
References and, day, firstYear, vector, and year.
years()
function and corresponding vector of years (where yeari) is the year of data(i)
References and, vector, where, and year.
Variable Documentation
!colors
if end at last year in vector If use a sliding mean window for plotting can only handle years before we run out of colors !colors = ['b','g','r','c','m','k','y']
Definition at line 10 of file plotYears.m.
References vector.
color
function and corresponding vector of multiplied by for each year in a different color
Definition at line 4 of file plotYears.m.
data
function and corresponding vector of multiplied by for each year in a different vs fractional day of start at first year in data
Definition at line 8 of file plotYears.m.
Referenced by ascii(), fprintf(), load(), split(), and years().
dataYr
dataYr = dataMean(i)
Definition at line 30 of file plotYears.m.
daysYr
find subset of data and days array daysYr = days(i)
Definition at line 31 of file plotYears.m.
lastYear
if lastYear = -1
Definition at line 8 of file plotYears.m.
Referenced by readClimData(), and updateTrackers().
NOTE
if end at last year in vector If use a sliding mean window for plotting NOTE
Definition at line 10 of file plotYears.m.
scaleFactor
function and corresponding vector of multiplied by scaleFactor
Definition at line 4 of file plotYears.m.
Referenced by main(), and metropolis().
window
if end at last year in vector If window
Definition at line 9 of file plotYears.m.
years
loop through years
Definition at line 27 of file plotYears.m.
Referenced by freeOutputInfo(), means:(), newOutputInfo(), writeHistFile(), writeHistFileBin(), and years().
yr
loop through plotting each line for yr
Initial value:
= firstYear:lastYear
    i = find(years == yr)
Definition at line 28 of file plotYears.m.