SIPNET: sipnet.h File Reference
sipnet.h File Reference
#include <stdio.h>
#include "spatialParams.h"
Macros
#define EXTRA_DATA_TYPES 0
#define MAX_DATA_TYPES 3
Functions
void printModelComponents (FILE *out)
char ** getDataTypeNames ()
int initModel (SpatialParams **spatialParams, int **steps, char *paramFile, char *climFile)
void cleanupModel (int numLocs)
void runModelNoOut (double **outArray, int numDataTypes, int dataTypeIndices[], SpatialParams *spatialParams, int loc)
void runModelOutput (FILE *out, int printHeader, SpatialParams *spatialParams, int loc)
void sensTest (FILE *out, int paramNum, double low, double high, int numRuns, SpatialParams *spatialParams, int loc)
Macro Definition Documentation
EXTRA_DATA_TYPES
#define EXTRA_DATA_TYPES 0
Definition at line 11 of file SIPNETparamsChange/sipnet.h.
MAX_DATA_TYPES
#define MAX_DATA_TYPES 3
Definition at line 20 of file SIPNETparamsChange/sipnet.h.
Function Documentation
cleanupModel()
void cleanupModel (int numLocs)
Definition at line 1916 of file sipnetvJan2007.c.
References deallocateMeanTracker(), freeClimateList(), meanFPAR, meanGPP, meanGPP, meanGPP, meanGPP, meanNPP, meanNPP, meanNPP, meanNPP, meanNPP, meanNPP, and numLocs.
Referenced by main().
getDataTypeNames()
char ** getDataTypeNames ()
Definition at line 1832 of file sipnetvJan2007.c.
References index, and MAX_DATA_TYPES.
Referenced by main(), printDataTypeIndices(), printDataTypeWeightIndices(), setDataTypeIndices(), and usage().
initModel()
int initModel (SpatialParams ** spatialParams, int ** steps, char * paramFile, char * climFile)
Definition at line 1894 of file sipnetvJan2007.c.
References index, MEAN_FPAR_DAYS, MEAN_FPAR_MAX_ENTRIES, MEAN_GPP_SOIL_DAYS, MEAN_GPP_SOIL_MAX_ENTRIES, MEAN_NPP_DAYS, MEAN_NPP_MAX_ENTRIES, meanFPAR, meanGPP, meanGPP, meanNPP, meanNPP, meanNPP, meanNPP, newMeanTracker(), numLocs, readClimData(), readParamData(), and setupOutputPointers().
Referenced by main().
printModelComponents()
void printModelComponents (FILE * out)
Definition at line 1802 of file sipnetvJan2007.c.
References ALTERNATIVE_TRANS, BALL_BERRY, COMPLEX_WATER, ModelOptionsStruct::COMPLEX_WATER, CSV_OUTPUT, DAYCENT_WATER_HRESP, ModelOptionsStruct::DAYCENT_WATER_HRESP, fprintf(), GDD, ModelOptionsStruct::GDD, GROWTH_RESP, ModelOptionsStruct::GROWTH_RESP, index, LITTER_POOL, ModelOptionsStruct::LITTER_POOL, LITTER_WATER, ModelOptionsStruct::LITTER_WATER, LITTER_WATER_DRAINAGE, ModelOptionsStruct::LITTER_WATER_DRAINAGE, LLOYD_TAYLOR, ModelOptionsStruct::LLOYD_TAYLOR, MEAN_FPAR_DAYS, MEAN_GPP_SOIL_DAYS, MEAN_NPP_DAYS, MICROBES, MODEL_WATER, ModelOptionsStruct::MODEL_WATER, NUMBER_SOIL_CARBON_POOLS, options, PENMAN_MONTEITH_TRANS, ROOTS, SEASONAL_R_SOIL, ModelOptionsStruct::SEASONAL_R_SOIL, SNOW, ModelOptionsStruct::SNOW, SOIL_MULTIPOOL, SOIL_PHENOL, ModelOptionsStruct::SOIL_PHENOL, SOIL_QUALITY, STOICHIOMETRY, WATER_HRESP, ModelOptionsStruct::WATER_HRESP, WATER_PSN, and ModelOptionsStruct::WATER_PSN.
Referenced by main().
runModelNoOut()
void runModelNoOut (double ** outArray, int numDataTypes, int dataTypeIndices[], SpatialParams * spatialParams, int loc)
Definition at line 1760 of file sipnetvJan2007.c.
References climate, climate, climate, climate, climate, climate, exit(), index, ClimateVars::nextClim, outputPtrs, outputPtrs, outputPtrs, outputPtrs, outputPtrs, outputPtrs, setupModel(), step, and updateState().
Referenced by main().
runModelOutput()
void runModelOutput (FILE * out, int printHeader, SpatialParams * spatialParams, int loc)
Definition at line 1726 of file sipnetvJan2007.c.
References climate, climate, climate, climate, climate, ClimateVars::day, index, ClimateVars::nextClim, SpatialParamsStruct::numLocs, outputHeader(), outputState(), setupModel(), ClimateVars::time, updateState(), and ClimateVars::year.
Referenced by main(), and sensTest().
sensTest()
void sensTest (FILE * out, int paramNum, double low, double high, int numRuns, SpatialParams * spatialParams, int loc)
Definition at line 1781 of file sipnetvJan2007.c.
References fprintf(), index, runModelOutput(), setSpatialParam(), and value.
Referenced by main().