SIPNET: cli.c File Reference
cli.c File Reference
#include "cli.h"
#include "common/exitCodes.h"
#include "common/logging.h"
#include "version.h"
Macros
#define DECLARE_FLAG(name)
#define DECLARE_ARG_FOR_MAP(x) #x, #x
Functions
void usage (char *progName)
void version (void)
void parseCommandLineArgs (int argc, char *argv[])
void checkCLINameMap (void)
Variables
static struct option long_options []
char * argNameMap []
Macro Definition Documentation
DECLARE_ARG_FOR_MAP
#define DECLARE_ARG_FOR_MAP (x) #x, #x
Definition at line 12 of file cli.c.
DECLARE_FLAG
#define DECLARE_FLAG (name)
Value:
  {#name, no_argument, &ctx.tmpFlag, 1},                                       \
      {"no-" #name, no_argument, &ctx.tmpFlag, 0}
Definition at line 8 of file cli.c.
Function Documentation
checkCLINameMap()
void checkCLINameMap (void)
Verify that the cli's arg-name map is valid
Verifies that everything in argNameMap maps to a valid context metadata. Does not verify that we failed to add a flag to the map. Call this after initContext()
Definition at line 161 of file cli.c.
References argNameMap, ctx, EXIT_CODE_INTERNAL_ERROR, getContextMetadata(), context_metadata::hh, context_metadata::isFlag, logInternalError, Context::metaMap, UT_hash_handle::next, and NUM_FLAG_OPTIONS.
Referenced by main().
parseCommandLineArgs()
void parseCommandLineArgs (int argc, char * argv[])
Definition at line 111 of file cli.c.
References argNameMap, ctx, CTX_COMMAND_LINE, EXIT_CODE_BAD_CLI_ARGUMENT, EXIT_CODE_SUCCESS, FILENAME_MAXLEN, long_options, Context::tmpFlag, updateCharContext(), updateIntContext(), usage(), and version().
Referenced by main().
usage()
void usage (char * progName)
Definition at line 67 of file cli.c.
Referenced by parseCommandLineArgs().
version()
void version (void)
Definition at line 108 of file cli.c.
References VERSION_STRING.
Referenced by parseCommandLineArgs().
Variable Documentation
argNameMap
char* argNameMap[]
Initial value:
= {
    DECLARE_ARG_FOR_MAP(events), DECLARE_ARG_FOR_MAP(gdd),
    DECLARE_ARG_FOR_MAP(growthResp), DECLARE_ARG_FOR_MAP(leafWater),
    DECLARE_ARG_FOR_MAP(litterPool), DECLARE_ARG_FOR_MAP(microbes),
    DECLARE_ARG_FOR_MAP(snow), DECLARE_ARG_FOR_MAP(soilPhenol),
    DECLARE_ARG_FOR_MAP(waterHResp),
    DECLARE_ARG_FOR_MAP(doMainOutput), DECLARE_ARG_FOR_MAP(doSingleOutputs),
    DECLARE_ARG_FOR_MAP(dumpConfig), DECLARE_ARG_FOR_MAP(printHeader),
    DECLARE_ARG_FOR_MAP(quiet)}
Definition at line 48 of file cli.c.
Referenced by checkCLINameMap(), and parseCommandLineArgs().
long_options
struct option long_options[] static
Initial value:
= {
    DECLARE_FLAG(events),
    DECLARE_FLAG(gdd),
    DECLARE_FLAG(growth-resp),
    DECLARE_FLAG(leaf-water),
    DECLARE_FLAG(litter-pool),
    DECLARE_FLAG(microbes),
    DECLARE_FLAG(snow),
    DECLARE_FLAG(soil-phenol),
    DECLARE_FLAG(water-hresp),
    DECLARE_FLAG(do-main-output),
    DECLARE_FLAG(do-single-outputs),
    DECLARE_FLAG(dump-config),
    DECLARE_FLAG(print-header),
    DECLARE_FLAG(quiet),
    {"input-file", required_argument, 0, 'i'},
    {"file-name", no_argument, 0, 'f'},
    {"help", no_argument, 0, 'h'},
    {"version", no_argument, 0, 'v'},
    {0, 0, 0, 0}}
Definition at line 17 of file cli.c.
Referenced by parseCommandLineArgs().