SIPNET: daysFromMonth.m File Reference
daysFromMonth.m File Reference
Functions
if (isLeapYear(year)) months
Variables
function [first, last]
leapMonths = [31,29,31,30,31,30,31,31,30,31,30,31]
else months = nonleapMonths
end first = sum(months(1:(month-1))) + 1
last = first + months(month) - 1
Function Documentation
if()
if (isLeapYear(year))
Variable Documentation
first
end first = sum(months(1:(month-1))) + 1
Definition at line 15 of file datstuff/daysFromMonth.m.
Referenced by fprintf(), frewind(), ones(), split(), while(), and years().
function
function[first, last]
Initial value:
= daysFromMonth(month, year)
    % for a given month (1..12) and year
    % return first and last days (julian days) of that year
    % number of days per month in non-leap years and leap years:
    nonleapMonths = [31,28,31,30,31,30,31,31,30,31,30,31]
Definition at line 1 of file datstuff/daysFromMonth.m.
last
last = first + months(month) - 1
Definition at line 16 of file datstuff/daysFromMonth.m.
leapMonths
leapMonths = [31,29,31,30,31,30,31,31,30,31,30,31]
Definition at line 7 of file datstuff/daysFromMonth.m.
months
else months = nonleapMonths
Definition at line 12 of file datstuff/daysFromMonth.m.