SIPNET: ml-metrorun.c File Reference
ml-metrorun.c File Reference
#include <signal.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "sipnet.h"
#include "ml-metro.h"
#include "paramchange.h"
#include "util.h"
#include "spatialParams.h"
#include "namelistInput.h"
Macros
#define FILE_MAXNAME 256
#define INPUT_MAXNAME 64
#define INPUT_FILE "estimate.in"
#define ADD_FRACTION 0.5
#define COMPARE_INDICES_EXT ""
#define AGGREGATION_EXT ""
#define UNAGGED_WEIGHT 0.0
#define NUM_CHAINS 10
#define ITER 375000
#define SCALE_FACTOR 1.0
#define LOC -1
#define NUM_RUNS 1
#define NUM_AT_ONCE 10000
#define PARAM_FILE ""
#define RANDOM_START 0
#define NUM_SPIN_UPS 125000
#define OPT_INDICES_EXT ""
#define VALID_FRAC
#define PARAM_WEIGHT 0.0
#define COST_FUNCTION 0
Functions
void usage (char *progName)
int initDataTypeIndices (int dataTypeIndices[])
void initDataTypeWeights (double dataTypeWeights[])
int parseDataTypeSwitches (int dataTypeIndices[], int dataTypeSwitches[])
void printDataTypeIndices (int dataTypeIndices[], int numDataTypes, FILE *filePtr)
void printDataTypeWeightIndices (int dataTypeIndices[], int numDataTypes, double dataTypeWeights[], FILE *filePtr)
int main (int argc, char *argv[])
Macro Definition Documentation
ADD_FRACTION
#define ADD_FRACTION 0.5
Definition at line 23 of file ml-metrorun.c.
AGGREGATION_EXT
#define AGGREGATION_EXT ""
Definition at line 25 of file ml-metrorun.c.
COMPARE_INDICES_EXT
#define COMPARE_INDICES_EXT ""
Definition at line 24 of file ml-metrorun.c.
COST_FUNCTION
#define COST_FUNCTION 0
Definition at line 39 of file ml-metrorun.c.
FILE_MAXNAME
#define FILE_MAXNAME 256
Definition at line 19 of file ml-metrorun.c.
INPUT_FILE
#define INPUT_FILE "estimate.in"
Definition at line 21 of file ml-metrorun.c.
INPUT_MAXNAME
#define INPUT_MAXNAME 64
Definition at line 20 of file ml-metrorun.c.
ITER
#define ITER 375000
Definition at line 28 of file ml-metrorun.c.
LOC
#define LOC -1
Definition at line 30 of file ml-metrorun.c.
NUM_AT_ONCE
#define NUM_AT_ONCE 10000
Definition at line 32 of file ml-metrorun.c.
NUM_CHAINS
#define NUM_CHAINS 10
Definition at line 27 of file ml-metrorun.c.
NUM_RUNS
#define NUM_RUNS 1
Definition at line 31 of file ml-metrorun.c.
NUM_SPIN_UPS
#define NUM_SPIN_UPS 125000
Definition at line 35 of file ml-metrorun.c.
OPT_INDICES_EXT
#define OPT_INDICES_EXT ""
Definition at line 36 of file ml-metrorun.c.
PARAM_FILE
#define PARAM_FILE ""
Definition at line 33 of file ml-metrorun.c.
PARAM_WEIGHT
#define PARAM_WEIGHT 0.0
Definition at line 38 of file ml-metrorun.c.
RANDOM_START
#define RANDOM_START 0
Definition at line 34 of file ml-metrorun.c.
SCALE_FACTOR
#define SCALE_FACTOR 1.0
Definition at line 29 of file ml-metrorun.c.
UNAGGED_WEIGHT
#define UNAGGED_WEIGHT 0.0
Definition at line 26 of file ml-metrorun.c.
VALID_FRAC
#define VALID_FRAC
Value:
                     0.5 /* fraction of data points which must be valid
                     to use data from a given time step */
Definition at line 37 of file ml-metrorun.c.
Function Documentation
initDataTypeIndices()
int initDataTypeIndices (int dataTypeIndices[])
Definition at line 51 of file ml-metrorun.c.
References i, and MAX_DATA_TYPES.
Referenced by main().
initDataTypeWeights()
void initDataTypeWeights (double dataTypeWeights[])
Definition at line 61 of file ml-metrorun.c.
References i, and MAX_DATA_TYPES.
main()
int main (int argc, char * argv[])
Definition at line 116 of file ml-metrorun.c.
References ADD_FRACTION, addNamelistInputItem(), aggedDifference(), AGGREGATION_EXT, buildFileName(), cleanupModel(), cleanupParamchange(), COMPARE_INDICES_EXT, deleteSpatialParams(), dieIfNotSet(), difference(), DOUBLE_TYPE, exit(), fclose(), FILE_MAXNAME, fprintf(), getDataTypeNames(), i, initDataTypeIndices(), initModel(), INPUT_FILE, INPUT_MAXNAME, INT_TYPE, ITER, LOC, LONG_TYPE, MAX_DATA_TYPES, metropolis(), NAMELIST_INPUT_MAXNAME, newNamelistInputs(), NUM_AT_ONCE, NUM_CHAINS, NUM_RUNS, NUM_SPIN_UPS, numLocs, openFile(), OPT_INDICES_EXT, PARAM_FILE, PARAM_WEIGHT, parseDataTypeSwitches(), printDataTypeIndices(), printDataTypeWeightIndices(), printModelComponents(), RANDOM_START, readData(), readFileForAgg(), readNamelistInputs(), runModelNoOut(), SCALE_FACTOR, scaleFactor, seedRand(), STRING_TYPE, UNAGGED_WEIGHT, unaggedWeight, usage(), VALID_FRAC, and writeBestSpatialParams().
parseDataTypeSwitches()
int parseDataTypeSwitches (int dataTypeIndices[], int dataTypeSwitches[])
Definition at line 77 of file ml-metrorun.c.
References i, and MAX_DATA_TYPES.
Referenced by main().
printDataTypeIndices()
void printDataTypeIndices (int dataTypeIndices[], int numDataTypes, FILE * filePtr)
Definition at line 94 of file ml-metrorun.c.
References fprintf(), getDataTypeNames(), and i.
Referenced by main().
printDataTypeWeightIndices()
void printDataTypeWeightIndices (int dataTypeIndices[], int numDataTypes, double dataTypeWeights[], FILE * filePtr)
Definition at line 106 of file ml-metrorun.c.
References fprintf(), getDataTypeNames(), and i.
Referenced by main().
usage()
void usage (char * progName)
Definition at line 41 of file ml-metrorun.c.
References INPUT_FILE.
Referenced by main().