SIPNET: splitdata.m File Reference
splitdata.m File Reference
Functions
'Error:data must have 2 dimensions\n' fprintf ()
split (i,:,:)
Variables
function split
return elseif(mod(length(data(:, 1)), len) ~=0) fprintf('Error return else n = length(data(:,1))/len
for i
fin = i*len
Function Documentation
fprintf()
'Error:data must have 2 dimensions\n' fprintf () virtual
References data, first, length(), and where.
Referenced by copySubset(), main(), metropolis(), outputHeader(), outputState(), outputStatecsv(), outputTranspose(), printDataTypeIndices(), printDataTypeWeightIndices(), printModelComponents(), readData(), reset(), seedRand(), sensTest(), sensTest(), terminateOutputItemLines(), writeBestSpatialParams(), writeChangeableParamInfo(), writeHistFile(), writeHistFileHeader(), writeOutputItemLabels(), and writeOutputItemValues().
split()
split (i , : , :)
References data.
Variable Documentation
fin
fin = i*len
Definition at line 17 of file splitdata.m.
i
for i
Initial value:
= 1:n
        start = 1 + (i-1)*len
Definition at line 15 of file splitdata.m.
n
return elseif (mod(length(data(:,1)), len) ~= 0) fprintf('Error return else n = length(data(:,1))/len
Definition at line 14 of file splitdata.m.
split
function split
Initial value:
= splitdata(data, len)
% PRE: data has 2 dimensions
Definition at line 1 of file splitdata.m.