SIPNET: exitHandler.c File Reference
exitHandler.c File Reference
#include <setjmp.h>
#include <unistd.h>
Macros
#define test_assert(x) (exit_result = exit_result && (x))
Functions
void exit (int code)
Variables
static int expected_code = 1
static int should_exit = 1
static int really_exit = 0
static jmp_buf jump_env
static int exit_result = 1
Macro Definition Documentation
test_assert
#define test_assert (x) (exit_result = exit_result && (x))
Definition at line 13 of file exitHandler.c.
Function Documentation
exit()
void exit (int code)
Definition at line 36 of file exitHandler.c.
References expected_code, index, jump_env, really_exit, should_exit, and test_assert.
Referenced by calcLightEff(), checkAllRead(), checkLocations(), checkStatus(), copySubset(), createEventNode(), dieIfNotRead(), dieIfNotSet(), gotoStart(), initializeOneSpatialParam(), main(), main(), newNamelistInputItem(), newSingleOutputItem(), openFile(), openFile(), openFile(), parseDataTypeIndices(), readClimData(), readData(), readEventData(), readFileForAgg(), readItems(), readNamelistInputs(), readOneSpatialParam(), readParamData(), readSpatialParams(), readSpatialValues(), runModelNoOut(), and updateState().
Variable Documentation
exit_result
int exit_result = 1 static
Definition at line 12 of file exitHandler.c.
Referenced by run().
expected_code
int expected_code = 1 static
Definition at line 6 of file exitHandler.c.
Referenced by exit(), and run().
jump_env
jmp_buf jump_env static
Definition at line 10 of file exitHandler.c.
Referenced by exit(), and run().
really_exit
int really_exit = 0 static
Definition at line 8 of file exitHandler.c.
Referenced by exit(), and run().
should_exit
int should_exit = 1 static
Definition at line 7 of file exitHandler.c.
Referenced by exit(), and run().