SIPNET: sipnetClimFixedSteps.c File Reference
sipnetClimFixedSteps.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
void usage (char *progName)
FILE * openFile (char *directory, char *name, char *mode)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 43 of file preprocess/sipnetClimFixedSteps.c.
References day, exit(), fclose(), fprintf(), index, leap, openFile(), par, parf, pptf, soilwetness, soilwetnessf, tair, tairf, time, tsoil, tsoilf, usage(), vpd, vpdf, vpress, vpressf, wspd, wspdf, and year.
openFile()
FILE * openFile (char * directory, char * name, char * mode)
Definition at line 23 of file preprocess/sipnetClimFixedSteps.c.
References exit(), f, index, and name.
Referenced by main().
usage()
void usage (char * progName)
Definition at line 12 of file preprocess/sipnetClimFixedSteps.c.
References index.
Referenced by main().