SIPNET: modelParams.h File Reference
modelParams.h File Reference
#include <stdio.h>
Data Structures
struct OneModelParamStruct
struct ModelParamsStruct
Macros
#define MODEL_PARAM_MAXNAME 64
#define OBSOLETE_PARAM (-1)
Typedefs
typedef struct OneModelParamStruct OneModelParam
typedef struct ModelParamsStruct ModelParams
Functions
ModelParams * newModelParams (int maxParameters)
void initializeOneModelParam (ModelParams *params, char *name, double *externalLoc, int isRequired)
void readModelParams (ModelParams *params, FILE *paramFile)
int getNumModelParams (ModelParams *params)
int getNumModelParamsRead (ModelParams *params)
int locateParam (ModelParams *params, char *name)
int valueSet (ModelParams *params, int i)
int checkParam (ModelParams *params, int i, double value)
double getParam (ModelParams *params, int i)
void deleteModelParams (ModelParams *params)
Macro Definition Documentation
MODEL_PARAM_MAXNAME
#define MODEL_PARAM_MAXNAME 64
Definition at line 6 of file modelParams.h.
OBSOLETE_PARAM
#define OBSOLETE_PARAM (-1)
Definition at line 7 of file modelParams.h.
Typedef Documentation
ModelParams
typedef struct ModelParamsStruct ModelParams
OneModelParam
typedef struct OneModelParamStruct OneModelParam
Function Documentation
checkParam()
int checkParam (ModelParams * params, int i, double value)
deleteModelParams()
void deleteModelParams (ModelParams * params)
Definition at line 269 of file modelParams.c.
References ModelParamsStruct::params, and ModelParamsStruct::readIndices.
Referenced by main().
getNumModelParams()
int getNumModelParams (ModelParams * params)
getNumModelParamsRead()
int getNumModelParamsRead (ModelParams * params)
getParam()
double getParam (ModelParams * params, int i)
initializeOneModelParam()
void initializeOneModelParam (ModelParams * modelParams, char * name, double * externalLoc, int isRequired)
Parameters
modelParams
name
externalLoc
isRequired
Definition at line 103 of file modelParams.c.
References allParamsInitialized(), OneModelParamStruct::isRead, OneModelParamStruct::isRequired, logError, ModelParamsStruct::maxParams, OneModelParamStruct::name, ModelParamsStruct::numParams, ModelParamsStruct::params, and OneModelParamStruct::value.
Referenced by readParamData().
locateParam()
int locateParam (ModelParams * params, char * name)
Definition at line 244 of file modelParams.c.
References OneModelParamStruct::name, and ModelParamsStruct::params.
Referenced by readModelParams().
newModelParams()
ModelParams * newModelParams (int maxParameters)
Definition at line 80 of file modelParams.c.
References ModelParamsStruct::maxParams, ModelParamsStruct::numParams, ModelParamsStruct::numParamsRead, ModelParamsStruct::params, and ModelParamsStruct::readIndices.
Referenced by readParamData().
readModelParams()
void readModelParams (ModelParams * params, FILE * paramFile)
Definition at line 139 of file modelParams.c.
References checkAllRead(), checkParamFormat(), EXIT_CODE_BAD_PARAMETER_VALUE, EXIT_CODE_INPUT_FILE_ERROR, OneModelParamStruct::isRead, locateParam(), logError, logWarning, MODEL_PARAM_MAXNAME, ModelParamsStruct::numParamsRead, ModelParamsStruct::params, ModelParamsStruct::readIndices, stripComment(), OneModelParamStruct::value, and valueSet().
Referenced by readParamData().
valueSet()
int valueSet (ModelParams * params, int i)
Definition at line 265 of file modelParams.c.
References OneModelParamStruct::isRead, and ModelParamsStruct::params.
Referenced by readModelParams().