SIPNET: sipnet.h File Reference
sipnet.h File Reference
#include <stdio.h>
#include "common/spatialParams.h"
#include "outputItems.h"
Macros
#define EXTRA_DATA_TYPES 0
#define MAX_DATA_TYPES 5
Functions
void printModelComponents (FILE *out)
char ** getDataTypeNames (void)
int initModel (SpatialParams **spatialParams, int **steps, char *paramFile, char *climFile)
void initEvents (char *eventFile, int numLocs, int printHeader)
void cleanupModel (int numLocs)
void runModelNoOut (double **outArray, int numDataTypes, int dataTypeIndices[], SpatialParams *spatialParams, int loc)
void runModelOutput (FILE *out, OutputItems *outputItems, int printHeader, SpatialParams *spatialParams, int loc)
void sensTest (FILE *out, OutputItems *outputItems, int paramNum, double low, double high, int numRuns, SpatialParams *spatialParams, int loc)
void setupOutputItems (OutputItems *outputItems)
Macro Definition Documentation
EXTRA_DATA_TYPES
#define EXTRA_DATA_TYPES 0
Definition at line 10 of file sipnet.h.
MAX_DATA_TYPES
#define MAX_DATA_TYPES 5
Definition at line 22 of file sipnet.h.
Function Documentation
cleanupModel()
void cleanupModel (int numLocs)
Definition at line 3251 of file sipnet.c.
References closeEventOutFile(), deallocateMeanTracker(), eventOutFile, freeClimateList(), freeEventList(), meanFPAR, meanGPP, meanNPP, and numLocs.
Referenced by main().
getDataTypeNames()
char ** getDataTypeNames (void)
Definition at line 3094 of file sipnet.c.
References MAX_DATA_TYPES.
Referenced by main(), printDataTypeIndices(), and printDataTypeWeightIndices().
initEvents()
void initEvents (char * eventFile, int numLocs, int printHeader)
Definition at line 3242 of file sipnet.c.
References eventOutFile, events, numLocs, openEventOutFile(), and readEventData().
Referenced by main().
initModel()
int initModel (SpatialParams ** spatialParams, int ** steps, char * paramFile, char * climFile)
Definition at line 3218 of file sipnet.c.
References MEAN_FPAR_DAYS, MEAN_FPAR_MAX_ENTRIES, MEAN_GPP_SOIL_DAYS, MEAN_GPP_SOIL_MAX_ENTRIES, MEAN_NPP_DAYS, MEAN_NPP_MAX_ENTRIES, meanFPAR, meanGPP, meanNPP, newMeanTracker(), numLocs, readClimData(), readParamData(), and setupOutputPointers().
Referenced by main().
printModelComponents()
void printModelComponents (FILE * out)
Definition at line 3039 of file sipnet.c.
References ALTERNATIVE_TRANS, BALL_BERRY, COMPLEX_WATER, CSV_OUTPUT, DAYCENT_WATER_HRESP, GDD, GROWTH_RESP, LITTER_POOL, LITTER_WATER, LITTER_WATER_DRAINAGE, LLOYD_TAYLOR, MEAN_FPAR_DAYS, MEAN_GPP_SOIL_DAYS, MEAN_NPP_DAYS, MICROBES, MODEL_WATER, NUMBER_SOIL_CARBON_POOLS, PENMAN_MONTEITH_TRANS, ROOTS, SEASONAL_R_SOIL, SNOW, SOIL_MULTIPOOL, SOIL_PHENOL, SOIL_QUALITY, STOICHIOMETRY, WATER_HRESP, and WATER_PSN.
Referenced by main().
runModelNoOut()
void runModelNoOut (double ** outArray, int numDataTypes, int dataTypeIndices[], SpatialParams * spatialParams, int loc)
Definition at line 2973 of file sipnet.c.
References climate, ClimateVars::nextClim, outputPtrs, setupModel(), and updateState().
Referenced by main().
runModelOutput()
void runModelOutput (FILE * out, OutputItems * outputItems, int printHeader, SpatialParams * spatialParams, int loc)
Definition at line 2920 of file sipnet.c.
References climate, ClimateVars::day, ClimateVars::nextClim, SpatialParamsStruct::numLocs, outputHeader(), outputState(), setupEvents(), setupModel(), terminateOutputItemLines(), ClimateVars::time, updateState(), writeOutputItemLabels(), writeOutputItemValues(), and ClimateVars::year.
Referenced by main(), and sensTest().
sensTest()
void sensTest (FILE * out, OutputItems * outputItems, int paramNum, double low, double high, int numRuns, SpatialParams * spatialParams, int loc)
Definition at line 3009 of file sipnet.c.
References runModelOutput(), setSpatialParam(), and writeOutputItemLabels().
Referenced by main().
setupOutputItems()
void setupOutputItems (OutputItems * outputItems)
Definition at line 3193 of file sipnet.c.
References addOutputItem(), TrackerVars::gpp, TrackerVars::nee, TrackerVars::totGpp, TrackerVars::totNee, and trackers.
Referenced by main().