SIPNET: outputItems.c File Reference
outputItems.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "outputItems.h"
#include "common/util.h"
Functions
SingleOutputItem * newSingleOutputItem (char *name, double *ptr)
void openOutputItemFile (SingleOutputItem *singleOutputItem, char *filenameBase)
void closeOutputItemFile (SingleOutputItem *singleOutputItem)
OutputItems * newOutputItems (char *filenameBase, char separator)
void addOutputItem (OutputItems *outputItems, char *name, double *ptr)
void writeOutputItemLabels (OutputItems *outputItems, char *label)
void writeOutputItemValues (OutputItems *outputItems)
void terminateOutputItemLines (OutputItems *outputItems)
void deleteOutputItems (OutputItems *outputItems)
Function Documentation
addOutputItem()
void addOutputItem (OutputItems * outputItems, char * name, double * ptr)
Definition at line 98 of file outputItems.c.
References OutputItemsStruct::count, OutputItemsStruct::filenameBase, newSingleOutputItem(), SingleOutputItemStruct::nextItem, openOutputItemFile(), and OutputItemsStruct::tail.
Referenced by setupOutputItems().
closeOutputItemFile()
void closeOutputItemFile (SingleOutputItem * singleOutputItem)
Definition at line 57 of file outputItems.c.
References SingleOutputItemStruct::f.
Referenced by deleteOutputItems().
deleteOutputItems()
void deleteOutputItems (OutputItems * outputItems)
Definition at line 152 of file outputItems.c.
References closeOutputItemFile(), SingleOutputItemStruct::f, OutputItemsStruct::filenameBase, OutputItemsStruct::head, and SingleOutputItemStruct::nextItem.
Referenced by main().
newOutputItems()
OutputItems * newOutputItems (char * filenameBase, char separator)
Definition at line 72 of file outputItems.c.
References OutputItemsStruct::count, OutputItemsStruct::filenameBase, OutputItemsStruct::head, newSingleOutputItem(), OutputItemsStruct::separator, and OutputItemsStruct::tail.
Referenced by main().
newSingleOutputItem()
SingleOutputItem * newSingleOutputItem (char * name, double * ptr)
Definition at line 18 of file outputItems.c.
References SingleOutputItemStruct::f, SingleOutputItemStruct::name, SingleOutputItemStruct::nextItem, OUTPUT_ITEMS_MAXNAME, and SingleOutputItemStruct::ptr.
Referenced by addOutputItem(), and newOutputItems().
openOutputItemFile()
void openOutputItemFile (SingleOutputItem * singleOutputItem, char * filenameBase)
Definition at line 41 of file outputItems.c.
References SingleOutputItemStruct::f, SingleOutputItemStruct::name, and openFile().
Referenced by addOutputItem().
terminateOutputItemLines()
void terminateOutputItemLines (OutputItems * outputItems)
Definition at line 139 of file outputItems.c.
References SingleOutputItemStruct::f, OutputItemsStruct::head, and SingleOutputItemStruct::nextItem.
Referenced by runModelOutput().
writeOutputItemLabels()
void writeOutputItemLabels (OutputItems * outputItems, char * label)
Definition at line 114 of file outputItems.c.
References SingleOutputItemStruct::f, OutputItemsStruct::head, SingleOutputItemStruct::nextItem, and OutputItemsStruct::separator.
Referenced by runModelOutput(), and sensTest().
writeOutputItemValues()
void writeOutputItemValues (OutputItems * outputItems)
Definition at line 125 of file outputItems.c.
References SingleOutputItemStruct::f, OutputItemsStruct::head, SingleOutputItemStruct::nextItem, SingleOutputItemStruct::ptr, and OutputItemsStruct::separator.
Referenced by runModelOutput().