SIPNET: sipnetvJan2007.c File Reference
sipnetvJan2007.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include "sipnet.h"
#include "runmean.h"
#include "util.h"
#include "spatialParams.h"
Data Structures
struct ClimateVars
struct Parameters
struct Environment
struct FluxVars
struct TrackerVars
struct PhenologyTrackersStruct
Macros
#define GROWTH_RESP 0
#define ALTERNATIVE_TRANS 0
#define BALL_BERRY 0
#define PENMAN_MONTEITH_TRANS 0
#define G 0
#define LITTER_POOL 0
#define LLOYD_TAYLOR 0
#define SEASONAL_R_SOIL 0 && !LLOYD_TAYLOR
#define WATER_PSN 1
#define WATER_HRESP 1
#define DAYCENT_WATER_HRESP 0 && WATER_HRESP
#define MODEL_WATER 1
#define COMPLEX_WATER 1 && MODEL_WATER
#define LITTER_WATER 0 && (COMPLEX_WATER)
#define LITTER_WATER_DRAINAGE 1 && (LITTER_WATER)
#define SNOW (1 || (COMPLEX_WATER)) && MODEL_WATER
#define GDD 0
#define SOIL_PHENOL 0 && !GDD
#define C_WEIGHT 12.0
#define TEN_6 1000000.0
#define TEN_9 1000000000.0
#define SEC_PER_DAY 86400.0
#define MEAN_NPP_DAYS 5
#define MEAN_NPP_MAX_ENTRIES MEAN_NPP_DAYS * 96
#define LAMBDA 2501000.
#define LAMBDA_S 2835000.
#define RHO 1.3
#define CP 1005.
#define GAMMA 66.
#define E_STAR_SNOW
#define M 3.89
#define DELTA 0.2
#define TINY 0.000001
#define NUM_PARAMS 55
Typedefs
typedef struct ClimateVars ClimateNode
typedef struct Parameters Params
typedef struct Environment Envi
typedef struct FluxVars Fluxes
typedef struct TrackerVars Trackers
typedef struct PhenologyTrackersStruct PhenologyTrackers
Functions
int * readClimData (char *climFile, int numLocs)
int readParamData (SpatialParams **spatialParamsPtr, char *paramFile, char *spatialParamFile)
void outputHeader (FILE *out)
void outputState (FILE *out, int loc, int year, int day, double time)
void freeClimateList (int numLocs)
void calcLightEff2 (double *lightEff, double lai, double par)
void calcLightEff3 (double *lightEff, double lai, double par)
void potPsn (double *potGrossPsn, double *baseFolResp, double lai, double tair, double vpd, double par, int day)
void moisture_bwb (double *trans, double *dWater, double potGrossPsn, double vpd, double vPress, double plantLeafC, double leafCSpWt, double soilWater)
void moisture_pm (double *trans, double *dWater, double potGrossPsn, double vpd, double soilWater)
void moisture (double *trans, double *dWater, double potGrossPsn, double vpd, double soilWater)
int pastLeafGrowth ()
int pastLeafFall ()
void leafFluxes (double *leafCreation, double *leafLitter, double plantLeafC)
void simpleWaterFlow (double *rain, double *snowFall, double *immedEvap, double *snowMelt, double *sublimation, double *fastFlow, double *evaporation, double *topDrainage, double *bottomDrainage, double water, double snow, double precip, double temp, double length, double trans)
void calcPrecip (double *rain, double *snowFall, double *immedEvap)
void snowPack (double *snowMelt, double *sublimation, double snowFall)
void evapSoilFluxes (double *fastFlow, double *evaporation, double *drainage, double water, double whc, double netRain, double snowMelt, double fluxesOut)
void transSoilDrainage (double *bottomDrainage, double topDrainage, double trans, double soilWater)
void soilWaterFluxes (double *fastFlow, double *evaporation, double *topDrainage, double *bottomDrainage, double netRain, double snowMelt, double trans, double litterWater, double soilWater)
void getGpp (double *gpp, double potGrossPsn, double dWater)
void vegResp (double *folResp, double *woodResp, double baseFolResp)
void vegResp2 (double *folResp, double *woodResp, double *growthResp, double baseFolResp, double gpp)
double soilBreakdown (double poolC, double baseRate, double water, double whc, double tsoil, double Q10)
double woodLitterF (double plantWoodC)
void calculateFluxes ()
void initTrackers (void)
void updateTrackers (double oldSoilWater)
void ensureNonNegative (double *var, double minVal)
void ensureNonNegativeStocks ()
void updateState ()
void initPhenologyTrackers ()
void setupModel (SpatialParams *spatialParams, int loc)
void runModelOutput (FILE *out, int printHeader, SpatialParams *spatialParams, int loc)
void runModelNoOut (double **outArray, int numDataTypes, int dataTypeIndices[], SpatialParams *spatialParams, int loc)
void sensTest (FILE *out, int paramNum, double low, double high, int numRuns, SpatialParams *spatialParams, int loc)
void printModelComponents (FILE *out)
char ** getDataTypeNames ()
void setupOutputPointers (void)
int initModel (SpatialParams **spatialParams, int **steps, char *paramFile, char *climFile)
void cleanupModel (int numLocs)
Variables
static ClimateNode ** firstClimates
static Params params
static Envi envi
static Trackers trackers
static PhenologyTrackers phenologyTrackers
static MeanTracker * meanNPP
static ClimateNode * climate
static Fluxes fluxes
static double * outputPtrs [MAX_DATA_TYPES]
Macro Definition Documentation
ALTERNATIVE_TRANS
#define ALTERNATIVE_TRANS 0
Definition at line 27 of file sipnetvJan2007.c.
BALL_BERRY
#define BALL_BERRY 0
Definition at line 30 of file sipnetvJan2007.c.
C_WEIGHT
#define C_WEIGHT 12.0
Definition at line 94 of file sipnetvJan2007.c.
COMPLEX_WATER
#define COMPLEX_WATER 1 && MODEL_WATER
Definition at line 66 of file sipnetvJan2007.c.
CP
#define CP 1005.
Definition at line 107 of file sipnetvJan2007.c.
DAYCENT_WATER_HRESP
#define DAYCENT_WATER_HRESP 0 && WATER_HRESP
Definition at line 59 of file sipnetvJan2007.c.
DELTA
#define DELTA 0.2
Definition at line 113 of file sipnetvJan2007.c.
E_STAR_SNOW
#define E_STAR_SNOW
Value:
                           0.6 /* approximate saturation vapor pressure at 0 degrees C (kPa)
                           (we assume snow temperature is 0 degrees C or slightly lower) */
Definition at line 109 of file sipnetvJan2007.c.
G
#define G 0
Definition at line 37 of file sipnetvJan2007.c.
GAMMA
#define GAMMA 66.
Definition at line 108 of file sipnetvJan2007.c.
GDD
#define GDD 0
Definition at line 84 of file sipnetvJan2007.c.
GROWTH_RESP
#define GROWTH_RESP 0
Definition at line 24 of file sipnetvJan2007.c.
LAMBDA
#define LAMBDA 2501000.
Definition at line 104 of file sipnetvJan2007.c.
LAMBDA_S
#define LAMBDA_S 2835000.
Definition at line 105 of file sipnetvJan2007.c.
LITTER_POOL
#define LITTER_POOL 0
Definition at line 40 of file sipnetvJan2007.c.
LITTER_WATER
#define LITTER_WATER 0 && (COMPLEX_WATER)
Definition at line 71 of file sipnetvJan2007.c.
LITTER_WATER_DRAINAGE
#define LITTER_WATER_DRAINAGE 1 && (LITTER_WATER)
Definition at line 75 of file sipnetvJan2007.c.
LLOYD_TAYLOR
#define LLOYD_TAYLOR 0
Definition at line 43 of file sipnetvJan2007.c.
M
#define M 3.89
Definition at line 112 of file sipnetvJan2007.c.
MEAN_NPP_DAYS
#define MEAN_NPP_DAYS 5
Definition at line 100 of file sipnetvJan2007.c.
MEAN_NPP_MAX_ENTRIES
#define MEAN_NPP_MAX_ENTRIES MEAN_NPP_DAYS * 96
Definition at line 101 of file sipnetvJan2007.c.
MODEL_WATER
#define MODEL_WATER 1
Definition at line 62 of file sipnetvJan2007.c.
NUM_PARAMS
#define NUM_PARAMS 55
Definition at line 254 of file sipnetvJan2007.c.
PENMAN_MONTEITH_TRANS
#define PENMAN_MONTEITH_TRANS 0
Definition at line 34 of file sipnetvJan2007.c.
RHO
#define RHO 1.3
Definition at line 106 of file sipnetvJan2007.c.
SEASONAL_R_SOIL
#define SEASONAL_R_SOIL 0 && !LLOYD_TAYLOR
Definition at line 48 of file sipnetvJan2007.c.
SEC_PER_DAY
#define SEC_PER_DAY 86400.0
Definition at line 97 of file sipnetvJan2007.c.
SNOW
#define SNOW (1 || (COMPLEX_WATER)) && MODEL_WATER
Definition at line 79 of file sipnetvJan2007.c.
SOIL_PHENOL
#define SOIL_PHENOL 0 && !GDD
Definition at line 87 of file sipnetvJan2007.c.
TEN_6
#define TEN_6 1000000.0
Definition at line 95 of file sipnetvJan2007.c.
TEN_9
#define TEN_9 1000000000.0
Definition at line 96 of file sipnetvJan2007.c.
TINY
#define TINY 0.000001
Definition at line 115 of file sipnetvJan2007.c.
WATER_HRESP
#define WATER_HRESP 1
Definition at line 56 of file sipnetvJan2007.c.
WATER_PSN
#define WATER_PSN 1
Definition at line 53 of file sipnetvJan2007.c.
Typedef Documentation
ClimateNode
typedef struct ClimateVars ClimateNode
Definition at line 123 of file sipnetvJan2007.c.
Envi
typedef struct Environment Envi
Fluxes
typedef struct FluxVars Fluxes
Params
typedef struct Parameters Params
PhenologyTrackers
typedef struct PhenologyTrackersStruct PhenologyTrackers
Trackers
typedef struct TrackerVars Trackers
Function Documentation
calcLightEff2()
void calcLightEff2 (double * lightEff, double lai, double par)
Definition at line 624 of file sipnetvJan2007.c.
References Parameters::attenuation, Parameters::halfSatPar, par, and params.
calcLightEff3()
void calcLightEff3 (double * lightEff, double lai, double par)
Definition at line 650 of file sipnetvJan2007.c.
References Parameters::attenuation, Parameters::halfSatPar, par, and params.
Referenced by potPsn().
calcPrecip()
void calcPrecip (double * rain, double * snowFall, double * immedEvap)
Definition at line 1043 of file sipnetvJan2007.c.
References climate, Parameters::immedEvapFrac, ClimateVars::length, params, ClimateVars::precip, and ClimateVars::tair.
Referenced by calculateFluxes().
calculateFluxes()
void calculateFluxes ()
Definition at line 1335 of file sipnetvJan2007.c.
References Parameters::baseSoilResp, Parameters::baseSoilRespCold, FluxVars::bottomDrainage, calcPrecip(), climate, Parameters::coldSoilThreshold, ClimateVars::day, envi, FluxVars::evaporation, FluxVars::fastFlow, fluxes, Parameters::fracLitterRespired, getGpp(), FluxVars::immedEvap, FluxVars::leafCreation, Parameters::leafCSpWt, leafFluxes(), FluxVars::leafLitter, ClimateVars::length, Environment::litter, Parameters::litterBreakdownRate, FluxVars::litterToSoil, Environment::litterWater, Parameters::litterWHC, moisture(), moisture_bwb(), moisture_pm(), ClimateVars::par, params, FluxVars::photosynthesis, Environment::plantLeafC, Environment::plantWoodC, potPsn(), ClimateVars::precip, FluxVars::rain, FluxVars::rLitter, FluxVars::rSoil, FluxVars::rVeg, simpleWaterFlow(), Environment::snow, FluxVars::snowFall, FluxVars::snowMelt, snowPack(), Environment::soil, soilBreakdown(), Parameters::soilRespQ10, Parameters::soilRespQ10Cold, Environment::soilWater, soilWaterFluxes(), ClimateVars::soilWetness, Parameters::soilWHC, FluxVars::sublimation, ClimateVars::tair, FluxVars::topDrainage, FluxVars::transpiration, ClimateVars::tsoil, vegResp(), vegResp2(), ClimateVars::vpd, ClimateVars::vPress, FluxVars::woodLitter, and woodLitterF().
Referenced by updateState().
cleanupModel()
void cleanupModel (int numLocs)
Definition at line 1916 of file sipnetvJan2007.c.
References deallocateMeanTracker(), freeClimateList(), meanNPP, and numLocs.
Referenced by main().
ensureNonNegative()
void ensureNonNegative (double * var, double minVal)
Definition at line 1549 of file sipnetvJan2007.c.
Referenced by ensureNonNegativeStocks().
ensureNonNegativeStocks()
void ensureNonNegativeStocks ()
Definition at line 1561 of file sipnetvJan2007.c.
References ensureNonNegative(), envi, Environment::litter, Environment::litterWater, Environment::plantLeafC, Environment::plantWoodC, Environment::snow, Environment::soil, Environment::soilWater, and TINY.
Referenced by updateState().
evapSoilFluxes()
void evapSoilFluxes (double * fastFlow, double * evaporation, double * drainage, double water, double whc, double netRain, double snowMelt, double fluxesOut)
Definition at line 1146 of file sipnetvJan2007.c.
References climate, CP, envi, Parameters::fastFlowFrac, GAMMA, LAMBDA, ClimateVars::length, Parameters::litWaterDrainRate, params, Parameters::rdConst, RHO, Parameters::rSoilConst1, Parameters::rSoilConst2, SEC_PER_DAY, Environment::snow, ClimateVars::vpdSoil, and ClimateVars::wspd.
Referenced by soilWaterFluxes().
freeClimateList()
void freeClimateList (int numLocs)
Definition at line 598 of file sipnetvJan2007.c.
References firstClimates, ClimateVars::nextClim, and numLocs.
Referenced by cleanupModel().
getDataTypeNames()
char ** getDataTypeNames ()
Definition at line 1832 of file sipnetvJan2007.c.
References MAX_DATA_TYPES.
Referenced by main(), printDataTypeIndices(), printDataTypeWeightIndices(), setDataTypeIndices(), and usage().
getGpp()
void getGpp (double * gpp, double potGrossPsn, double dWater)
Definition at line 1250 of file sipnetvJan2007.c.
Referenced by calculateFluxes().
initModel()
int initModel (SpatialParams ** spatialParams, int ** steps, char * paramFile, char * climFile)
Definition at line 1894 of file sipnetvJan2007.c.
References MEAN_NPP_DAYS, MEAN_NPP_MAX_ENTRIES, meanNPP, newMeanTracker(), numLocs, readClimData(), readParamData(), and setupOutputPointers().
Referenced by main().
initPhenologyTrackers()
void initPhenologyTrackers ()
Definition at line 1650 of file sipnetvJan2007.c.
References climate, PhenologyTrackersStruct::didLeafFall, PhenologyTrackersStruct::didLeafGrowth, PhenologyTrackersStruct::lastYear, pastLeafFall(), pastLeafGrowth(), phenologyTrackers, and ClimateVars::year.
Referenced by setupModel().
initTrackers()
void initTrackers (void)
Definition at line 1464 of file sipnetvJan2007.c.
References envi, TrackerVars::evapotranspiration, TrackerVars::gpp, TrackerVars::nee, TrackerVars::npp, params, TrackerVars::ra, TrackerVars::rh, TrackerVars::rtot, Environment::soilWater, TrackerVars::soilWetnessFrac, Parameters::soilWHC, TrackerVars::totGpp, TrackerVars::totNee, TrackerVars::totNpp, TrackerVars::totRa, TrackerVars::totRh, TrackerVars::totRtot, trackers, TrackerVars::yearlyGpp, TrackerVars::yearlyNee, TrackerVars::yearlyNpp, TrackerVars::yearlyRa, TrackerVars::yearlyRh, and TrackerVars::yearlyRtot.
Referenced by setupModel().
leafFluxes()
void leafFluxes (double * leafCreation, double * leafLitter, double plantLeafC)
Definition at line 959 of file sipnetvJan2007.c.
References climate, PhenologyTrackersStruct::didLeafFall, PhenologyTrackersStruct::didLeafGrowth, Parameters::fracLeafFall, getMeanTrackerMean(), PhenologyTrackersStruct::lastYear, Parameters::leafAllocation, Parameters::leafGrowth, Parameters::leafTurnoverRate, ClimateVars::length, meanNPP, params, pastLeafFall(), pastLeafGrowth(), phenologyTrackers, and ClimateVars::year.
Referenced by calculateFluxes().
moisture()
void moisture (double * trans, double * dWater, double potGrossPsn, double vpd, double soilWater)
Definition at line 892 of file sipnetvJan2007.c.
References climate, Parameters::frozenSoilEff, Parameters::frozenSoilThreshold, params, TINY, ClimateVars::tsoil, vpd, Parameters::waterRemoveFrac, and Parameters::wueConst.
Referenced by calculateFluxes().
moisture_bwb()
void moisture_bwb (double * trans, double * dWater, double potGrossPsn, double vpd, double vPress, double plantLeafC, double leafCSpWt, double soilWater)
Definition at line 732 of file sipnetvJan2007.c.
References climate, envi, Parameters::frozenSoilEff, Parameters::frozenSoilThreshold, Parameters::leafCSpWt, Parameters::m_ballBerry, params, Environment::plantLeafC, TINY, ClimateVars::tsoil, ClimateVars::vpd, ClimateVars::vPress, and Parameters::waterRemoveFrac.
Referenced by calculateFluxes().
moisture_pm()
void moisture_pm (double * trans, double * dWater, double potGrossPsn, double vpd, double soilWater)
Definition at line 819 of file sipnetvJan2007.c.
References climate, CP, DELTA, Parameters::frozenSoilEff, Parameters::frozenSoilThreshold, GAMMA, ClimateVars::netrad, params, Parameters::rdConst, RHO, ClimateVars::soilheat, TINY, ClimateVars::tsoil, vpd, Parameters::waterRemoveFrac, and ClimateVars::wspd.
Referenced by calculateFluxes().
outputHeader()
void outputHeader (FILE * out)
Definition at line 580 of file sipnetvJan2007.c.
References fprintf().
Referenced by runModelOutput().
outputState()
void outputState (FILE * out, int loc, int year, int day, double time)
Definition at line 589 of file sipnetvJan2007.c.
References day, envi, TrackerVars::evapotranspiration, fluxes, fprintf(), TrackerVars::gpp, Environment::litter, Environment::litterWater, TrackerVars::nee, TrackerVars::npp, Environment::plantLeafC, Environment::plantWoodC, Environment::snow, Environment::soil, Environment::soilWater, TrackerVars::soilWetnessFrac, time, TrackerVars::totNee, trackers, FluxVars::transpiration, year, and TrackerVars::yearlyNpp.
Referenced by runModelOutput().
pastLeafFall()
int pastLeafFall ()
Definition at line 951 of file sipnetvJan2007.c.
References climate, ClimateVars::day, Parameters::leafOffDay, params, and ClimateVars::time.
Referenced by initPhenologyTrackers(), and leafFluxes().
pastLeafGrowth()
int pastLeafGrowth ()
Definition at line 939 of file sipnetvJan2007.c.
References climate, ClimateVars::day, ClimateVars::gdd, Parameters::gddLeafOn, Parameters::leafOnDay, params, Parameters::soilTempLeafOn, ClimateVars::time, and ClimateVars::tsoil.
Referenced by initPhenologyTrackers(), and leafFluxes().
potPsn()
void potPsn (double * potGrossPsn, double * baseFolResp, double lai, double tair, double vpd, double par, int day)
Definition at line 703 of file sipnetvJan2007.c.
References Parameters::aMax, Parameters::aMaxFrac, Parameters::baseFolRespFrac, C_WEIGHT, calcLightEff3(), Parameters::cFracLeaf, Parameters::dVpdExp, Parameters::dVpdSlope, Parameters::leafCSpWt, par, params, Parameters::psnTMax, Parameters::psnTMin, SEC_PER_DAY, tair, TEN_9, and vpd.
Referenced by calculateFluxes().
printModelComponents()
void printModelComponents (FILE * out)
Definition at line 1802 of file sipnetvJan2007.c.
References COMPLEX_WATER, DAYCENT_WATER_HRESP, fprintf(), GDD, GROWTH_RESP, LITTER_POOL, LITTER_WATER, LITTER_WATER_DRAINAGE, LLOYD_TAYLOR, MODEL_WATER, SEASONAL_R_SOIL, SNOW, SOIL_PHENOL, WATER_HRESP, and WATER_PSN.
Referenced by main().
readClimData()
int * readClimData (char * climFile, int numLocs)
Definition at line 361 of file sipnetvJan2007.c.
References count, ClimateVars::day, day, exit(), fclose(), firstClimates, ClimateVars::gdd, i, lastYear, ClimateVars::length, length(), ClimateVars::netrad, ClimateVars::nextClim, numLocs, openFile(), ClimateVars::par, par, ClimateVars::precip, ClimateVars::soilheat, ClimateVars::soilWetness, ClimateVars::tair, tair, ClimateVars::time, time, TINY, ClimateVars::tsoil, tsoil, ClimateVars::vpd, vpd, ClimateVars::vpdSoil, ClimateVars::vPress, ClimateVars::wspd, wspd, ClimateVars::year, and year.
Referenced by initModel().
readParamData()
int readParamData (SpatialParams ** spatialParamsPtr, char * paramFile, char * spatialParamFile)
Definition at line 496 of file sipnetvJan2007.c.
References allParamsRead(), Parameters::aMax, Parameters::aMaxFrac, Parameters::attenuation, Parameters::baseFolRespFrac, Parameters::baseSoilResp, Parameters::baseSoilRespCold, Parameters::baseVegResp, Parameters::cFracLeaf, Parameters::coldSoilThreshold, Parameters::dVpdExp, Parameters::dVpdSlope, Parameters::E0, exit(), Parameters::fastFlowFrac, fclose(), Parameters::fracLeafFall, Parameters::fracLitterRespired, Parameters::frozenSoilEff, Parameters::frozenSoilFolREff, Parameters::frozenSoilThreshold, Parameters::gddLeafOn, Parameters::growthRespFrac, Parameters::halfSatPar, Parameters::immedEvapFrac, Parameters::laiInit, Parameters::leafAllocation, Parameters::leafCSpWt, Parameters::leafGrowth, Parameters::leafOffDay, Parameters::leafOnDay, Parameters::leafTurnoverRate, Parameters::litterBreakdownRate, Parameters::litterInit, Parameters::litterWFracInit, Parameters::litterWHC, Parameters::litWaterDrainRate, Parameters::m_ballBerry, newSpatialParams(), NUM_PARAMS, numLocs, openFile(), params, Parameters::plantWoodInit, Parameters::psnTMin, Parameters::psnTOpt, Parameters::rdConst, readOneSpatialParam(), Parameters::rSoilConst1, Parameters::rSoilConst2, Parameters::snowInit, Parameters::snowMelt, Parameters::soilInit, Parameters::soilRespMoistEffect, Parameters::soilRespQ10, Parameters::soilRespQ10Cold, Parameters::soilTempLeafOn, Parameters::soilWFracInit, Parameters::soilWHC, Parameters::T0, Parameters::turnoverRate, Parameters::vegRespQ10, Parameters::waterRemoveFrac, and Parameters::wueConst.
Referenced by initModel().
runModelNoOut()
void runModelNoOut (double ** outArray, int numDataTypes, int dataTypeIndices[], SpatialParams * spatialParams, int loc)
Definition at line 1760 of file sipnetvJan2007.c.
References climate, ClimateVars::nextClim, outputPtrs, setupModel(), step, and updateState().
Referenced by main().
runModelOutput()
void runModelOutput (FILE * out, int printHeader, SpatialParams * spatialParams, int loc)
Definition at line 1726 of file sipnetvJan2007.c.
References climate, ClimateVars::day, ClimateVars::nextClim, SpatialParamsStruct::numLocs, outputHeader(), outputState(), setupModel(), ClimateVars::time, updateState(), and ClimateVars::year.
Referenced by main(), and sensTest().
sensTest()
void sensTest (FILE * out, int paramNum, double low, double high, int numRuns, SpatialParams * spatialParams, int loc)
Definition at line 1781 of file sipnetvJan2007.c.
References fprintf(), runModelOutput(), setSpatialParam(), and value.
Referenced by main().
setupModel()
void setupModel (SpatialParams * spatialParams, int loc)
Definition at line 1672 of file sipnetvJan2007.c.
References Parameters::baseSoilResp, Parameters::baseSoilRespCold, Parameters::baseVegResp, climate, envi, firstClimates, initPhenologyTrackers(), initTrackers(), Parameters::laiInit, Parameters::leafCSpWt, Parameters::leafTurnoverRate, Environment::litter, Parameters::litterBreakdownRate, Parameters::litterInit, Environment::litterWater, Parameters::litterWFracInit, Parameters::litterWHC, loadSpatialParams(), meanNPP, params, Environment::plantLeafC, Environment::plantWoodC, Parameters::plantWoodInit, Parameters::psnTMax, Parameters::psnTMin, Parameters::psnTOpt, resetMeanTracker(), Environment::snow, Parameters::snowInit, Environment::soil, Parameters::soilInit, Environment::soilWater, Parameters::soilWFracInit, Parameters::soilWHC, and Parameters::turnoverRate.
Referenced by runModelNoOut(), and runModelOutput().
setupOutputPointers()
void setupOutputPointers (void)
Definition at line 1846 of file sipnetvJan2007.c.
References TrackerVars::evapotranspiration, TrackerVars::gpp, i, TrackerVars::nee, TrackerVars::npp, outputPtrs, TrackerVars::ra, TrackerVars::rh, TrackerVars::rtot, TrackerVars::soilWetnessFrac, TrackerVars::totGpp, TrackerVars::totNee, TrackerVars::totNpp, TrackerVars::totRa, TrackerVars::totRh, TrackerVars::totRtot, trackers, TrackerVars::yearlyGpp, TrackerVars::yearlyNee, TrackerVars::yearlyNpp, TrackerVars::yearlyRa, TrackerVars::yearlyRh, and TrackerVars::yearlyRtot.
Referenced by initModel().
simpleWaterFlow()
void simpleWaterFlow (double * rain, double * snowFall, double * immedEvap, double * snowMelt, double * sublimation, double * fastFlow, double * evaporation, double * topDrainage, double * bottomDrainage, double water, double snow, double precip, double temp, double length, double trans)
Definition at line 999 of file sipnetvJan2007.c.
References length(), params, Parameters::snowMelt, and Parameters::soilWHC.
Referenced by calculateFluxes().
snowPack()
void snowPack (double * snowMelt, double * sublimation, double snowFall)
Definition at line 1070 of file sipnetvJan2007.c.
References climate, CP, E_STAR_SNOW, envi, GAMMA, LAMBDA_S, ClimateVars::length, params, Parameters::rdConst, RHO, SEC_PER_DAY, Environment::snow, Parameters::snowMelt, ClimateVars::tair, ClimateVars::vPress, and ClimateVars::wspd.
Referenced by calculateFluxes().
soilBreakdown()
double soilBreakdown (double poolC, double baseRate, double water, double whc, double tsoil, double Q10)
Definition at line 1290 of file sipnetvJan2007.c.
References Parameters::E0, params, Parameters::soilRespMoistEffect, Parameters::T0, and tsoil.
Referenced by calculateFluxes().
soilWaterFluxes()
void soilWaterFluxes (double * fastFlow, double * evaporation, double * topDrainage, double * bottomDrainage, double netRain, double snowMelt, double trans, double litterWater, double soilWater)
Definition at line 1233 of file sipnetvJan2007.c.
References evapSoilFluxes(), Parameters::litterWHC, params, Parameters::soilWHC, and transSoilDrainage().
Referenced by calculateFluxes().
transSoilDrainage()
void transSoilDrainage (double * bottomDrainage, double topDrainage, double trans, double soilWater)
Definition at line 1216 of file sipnetvJan2007.c.
References climate, ClimateVars::length, params, and Parameters::soilWHC.
Referenced by soilWaterFluxes().
updateState()
void updateState ()
Definition at line 1593 of file sipnetvJan2007.c.
References addValueToMeanTracker(), FluxVars::bottomDrainage, calculateFluxes(), climate, ensureNonNegativeStocks(), envi, err, FluxVars::evaporation, exit(), FluxVars::fastFlow, fluxes, FluxVars::immedEvap, FluxVars::leafCreation, FluxVars::leafLitter, ClimateVars::length, Environment::litter, FluxVars::litterToSoil, Environment::litterWater, meanNPP, FluxVars::photosynthesis, Environment::plantLeafC, Environment::plantWoodC, FluxVars::rain, FluxVars::rLitter, FluxVars::rSoil, FluxVars::rVeg, Environment::snow, FluxVars::snowFall, FluxVars::snowMelt, Environment::soil, Environment::soilWater, FluxVars::sublimation, FluxVars::topDrainage, FluxVars::transpiration, updateTrackers(), and FluxVars::woodLitter.
Referenced by runModelNoOut(), and runModelOutput().
updateTrackers()
void updateTrackers (double oldSoilWater)
Definition at line 1489 of file sipnetvJan2007.c.
References climate, envi, FluxVars::evaporation, TrackerVars::evapotranspiration, fluxes, TrackerVars::gpp, FluxVars::immedEvap, lastYear, ClimateVars::length, TrackerVars::nee, TrackerVars::npp, params, FluxVars::photosynthesis, TrackerVars::ra, TrackerVars::rh, FluxVars::rLitter, FluxVars::rSoil, TrackerVars::rtot, FluxVars::rVeg, Environment::soilWater, TrackerVars::soilWetnessFrac, Parameters::soilWHC, FluxVars::sublimation, TrackerVars::totGpp, TrackerVars::totNee, TrackerVars::totNpp, TrackerVars::totRa, TrackerVars::totRh, TrackerVars::totRtot, trackers, FluxVars::transpiration, ClimateVars::year, TrackerVars::yearlyGpp, TrackerVars::yearlyNee, TrackerVars::yearlyNpp, TrackerVars::yearlyRa, TrackerVars::yearlyRh, and TrackerVars::yearlyRtot.
Referenced by updateState().
vegResp()
void vegResp (double * folResp, double * woodResp, double baseFolResp)
Definition at line 1257 of file sipnetvJan2007.c.
References Parameters::baseVegResp, climate, envi, Parameters::frozenSoilFolREff, Parameters::frozenSoilThreshold, params, Environment::plantWoodC, Parameters::psnTOpt, ClimateVars::tair, ClimateVars::tsoil, and Parameters::vegRespQ10.
Referenced by calculateFluxes().
vegResp2()
void vegResp2 (double * folResp, double * woodResp, double * growthResp, double baseFolResp, double gpp)
Definition at line 1268 of file sipnetvJan2007.c.
References Parameters::baseVegResp, climate, envi, Parameters::frozenSoilFolREff, Parameters::frozenSoilThreshold, getMeanTrackerMean(), Parameters::growthRespFrac, meanNPP, params, Environment::plantWoodC, Parameters::psnTOpt, ClimateVars::tair, ClimateVars::tsoil, and Parameters::vegRespQ10.
Referenced by calculateFluxes().
woodLitterF()
double woodLitterF (double plantWoodC)
Definition at line 1330 of file sipnetvJan2007.c.
References params, and Parameters::turnoverRate.
Referenced by calculateFluxes().
Variable Documentation
climate
ClimateNode* climate static
Definition at line 339 of file sipnetvJan2007.c.
Referenced by calcPrecip(), calculateFluxes(), evapSoilFluxes(), initPhenologyTrackers(), leafFluxes(), moisture(), moisture_bwb(), moisture_pm(), pastLeafFall(), pastLeafGrowth(), run(), runModelNoOut(), runModelOutput(), setupModel(), snowPack(), transSoilDrainage(), updateState(), updateTrackers(), vegResp(), and vegResp2().
envi
Envi envi static
Definition at line 335 of file sipnetvJan2007.c.
Referenced by calculateFluxes(), checkOutput(), ensureNonNegativeStocks(), evapSoilFluxes(), initTrackers(), moisture_bwb(), outputState(), run(), setupModel(), snowPack(), updateState(), updateTrackers(), vegResp(), and vegResp2().
firstClimates
ClimateNode** firstClimates static
Definition at line 329 of file sipnetvJan2007.c.
Referenced by freeClimateList(), readClimData(), and setupModel().
fluxes
Fluxes fluxes static
Definition at line 340 of file sipnetvJan2007.c.
Referenced by calculateFluxes(), checkOutput(), outputState(), run(), updateState(), and updateTrackers().
meanNPP
MeanTracker* meanNPP static
Definition at line 338 of file sipnetvJan2007.c.
Referenced by cleanupModel(), initModel(), leafFluxes(), setupModel(), updateState(), and vegResp2().
outputPtrs
double* outputPtrs[MAX_DATA_TYPES] static
Definition at line 341 of file sipnetvJan2007.c.
Referenced by runModelNoOut(), and setupOutputPointers().
params
Params params static
Definition at line 334 of file sipnetvJan2007.c.
Referenced by calcLightEff2(), calcLightEff3(), calcPrecip(), calculateFluxes(), checkFertilizationParams(), checkHarvestParams(), checkIrrigationParams(), checkPlantingParams(), checkTillageParams(), createEventNode(), evapSoilFluxes(), initTrackers(), leafFluxes(), moisture(), moisture_bwb(), moisture_pm(), pastLeafFall(), pastLeafGrowth(), potPsn(), readParamData(), run(), setupModel(), simpleWaterFlow(), snowPack(), soilBreakdown(), soilWaterFluxes(), transSoilDrainage(), updateTrackers(), vegResp(), vegResp2(), and woodLitterF().
phenologyTrackers
PhenologyTrackers phenologyTrackers static
Definition at line 337 of file sipnetvJan2007.c.
Referenced by initPhenologyTrackers(), and leafFluxes().
trackers
Trackers trackers static
Definition at line 336 of file sipnetvJan2007.c.
Referenced by initTrackers(), outputState(), setupOutputPointers(), and updateTrackers().