SIPNET: paramchange.c File Reference
paramchange.c File Reference
#include <math.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "paramchange.h"
#include "util.h"
Data Structures
struct AggregateInfoStruct
Typedefs
typedef struct AggregateInfoStruct AggregateInfo
Functions
double difference (double *sigma, OutputInfo *outputInfo, int loc, SpatialParams *spatialParams, double paramWeight, void(*modelF)(double **, int, int *, SpatialParams *, int), int dataTypeIndices[], int numDataTypes, int costFunction, double dataTypeWeights[])
void computeAggedData (double **theAggedData, double **origArray, int myNumAggSteps, int *myAggSteps, int myStartOpt, int numDataTypes)
double aggedDifference (double *sigma, OutputInfo *outputInfo, int loc, SpatialParams *spatialParams, double paramWeight, void(*modelF)(double **, int, int *, SpatialParams *, int), int dataTypeIndices[], int numDataTypes, int costFunction, double dataTypeWeights[])
void aggregates (OutputInfo *outputInfo, double **model, int loc, int dataNum)
void readDataLine (FILE *in, double *arr, int numDataTypes)
int countLines (char *fileName)
int parseSpdValue (char *spdString, int *spd, int *count)
void readIndicesFile (char *fileName, int *startIndices, int *endIndices, int numLocs, int *steps)
void readData (char *fileName, int dataTypeIndices[], int numDataTypes, int totNumDataTypes, int myNumLocs, int *steps, double validFrac, char *optIndicesFile, char *compareIndicesFile, FILE *outFile)
void readFileForAgg (char *fileForAgg, int numDataTypes, double myUnaggedWeight)
OutputInfo * newOutputInfo (int numDataTypes, int loc)
void copyOutputInfo (OutputInfo *out, OutputInfo *in)
void freeOutputInfo (OutputInfo *outputInfo, int numDataTypes)
void cleanupParamchange ()
Variables
static double numLocs
static double *** data
static double *** sigmas
static double ** model
static int * startOpt
static int * endOpt
static int *** valid
static int * numAggSteps = NULL
static int ** aggSteps = NULL
static double *** aggedData = NULL
static double ** aggedModel = NULL
static double unaggedWeight = 0.0
static AggregateInfo * aggInfo
Typedef Documentation
AggregateInfo
typedef struct AggregateInfoStruct AggregateInfo
Function Documentation
aggedDifference()
double aggedDifference (double * sigma, OutputInfo * outputInfo, int loc, SpatialParams * spatialParams, double paramWeight, void(*)(double **, int, int *, SpatialParams *, int) modelF, int dataTypeIndices[], int numDataTypes, int costFunction, double dataTypeWeights[])
Definition at line 352 of file paramchange.c.
References aggedData, aggedModel, aggregates(), aggSteps, computeAggedData(), copyOutputInfo(), data, endOpt, i, index, makeArray(), model, n, numAggSteps, startOpt, unaggedWeight, and valid.
Referenced by main().
aggregates()
void aggregates (OutputInfo * outputInfo, double ** model, int loc, int dataNum)
Definition at line 438 of file paramchange.c.
References aggInfo, data, day, AggregateInfoStruct::endPt, i, index, j, makeArray(), model, AggregateInfoStruct::numDays, AggregateInfoStruct::spd, AggregateInfoStruct::startDay, AggregateInfoStruct::startPt, AggregateInfoStruct::startYear, sum(), and year.
Referenced by aggedDifference(), and difference().
cleanupParamchange()
void cleanupParamchange ()
Definition at line 968 of file paramchange.c.
References aggedData, aggedModel, aggInfo, aggSteps, data, endOpt, free2DArray(), index, model, numAggSteps, numLocs, sigmas, startOpt, and valid.
Referenced by main().
computeAggedData()
void computeAggedData (double ** theAggedData, double ** origArray, int myNumAggSteps, int * myAggSteps, int myStartOpt, int numDataTypes)
Definition at line 304 of file paramchange.c.
References i, index, and j.
Referenced by aggedDifference(), and readFileForAgg().
copyOutputInfo()
void copyOutputInfo (OutputInfo * out, OutputInfo * in)
Definition at line 945 of file paramchange.c.
References OutputInfoStruct::daysError, i, index, OutputInfoStruct::meanError, OutputInfoStruct::numYears, and OutputInfoStruct::years.
Referenced by aggedDifference().
countLines()
int countLines (char * fileName)
Definition at line 530 of file paramchange.c.
References f, fclose(), fileName, index, and openFile().
Referenced by readData().
difference()
double difference (double * sigma, OutputInfo * outputInfo, int loc, SpatialParams * spatialParams, double paramWeight, void(*)(double **, int, int *, SpatialParams *, int) modelF, int dataTypeIndices[], int numDataTypes, int costFunction, double dataTypeWeights[])
Definition at line 74 of file paramchange.c.
References aggregates(), data, endOpt, i, index, makeArray(), model, n, sigmas, startOpt, and valid.
Referenced by main().
freeOutputInfo()
void freeOutputInfo (OutputInfo * outputInfo, int numDataTypes)
Definition at line 957 of file paramchange.c.
References i, index, and years.
Referenced by main(), and metropolis().
newOutputInfo()
OutputInfo * newOutputInfo (int numDataTypes, int loc)
Definition at line 929 of file paramchange.c.
References aggInfo, i, index, makeArray(), AggregateInfoStruct::numDays, and years.
Referenced by main(), and metropolis().
parseSpdValue()
int parseSpdValue (char * spdString, int * spd, int * count)
Definition at line 553 of file paramchange.c.
References count, and index.
Referenced by readData().
readData()
void readData (char * fileName, int dataTypeIndices[], int numDataTypes, int totNumDataTypes, int myNumLocs, int * steps, double validFrac, char * optIndicesFile, char * compareIndicesFile, FILE * outFile)
Definition at line 627 of file paramchange.c.
References aggInfo, count, countLines(), data, endOpt, AggregateInfoStruct::endPt, exit(), fclose(), fileName, fprintf(), i, index, make2DArray(), make2DIntArray(), makeArray(), model, AggregateInfoStruct::numDays, numLocs, openFile(), parseSpdValue(), readDataLine(), readIndicesFile(), sigmas, AggregateInfoStruct::spd, AggregateInfoStruct::startDay, startOpt, AggregateInfoStruct::startPt, AggregateInfoStruct::startYear, valid, and year.
Referenced by main().
readDataLine()
void readDataLine (FILE * in, double * arr, int numDataTypes)
Definition at line 512 of file paramchange.c.
References i, and index.
Referenced by readData().
readFileForAgg()
void readFileForAgg (char * fileForAgg, int numDataTypes, double myUnaggedWeight)
Definition at line 873 of file paramchange.c.
References aggedData, aggedModel, aggSteps, computeAggedData(), count, data, endOpt, exit(), f, fclose(), i, index, make2DArray(), numAggSteps, numLocs, openFile(), startOpt, sum(), and unaggedWeight.
Referenced by main().
readIndicesFile()
void readIndicesFile (char * fileName, int * startIndices, int * endIndices, int numLocs, int * steps)
Definition at line 578 of file paramchange.c.
References fclose(), fileName, index, numLocs, and openFile().
Referenced by readData().
Variable Documentation
aggedData
double*** aggedData = NULL static
Definition at line 34 of file paramchange.c.
Referenced by aggedDifference(), cleanupParamchange(), and readFileForAgg().
aggedModel
double** aggedModel = NULL static
Definition at line 36 of file paramchange.c.
Referenced by aggedDifference(), cleanupParamchange(), and readFileForAgg().
aggInfo
AggregateInfo* aggInfo static
Definition at line 50 of file paramchange.c.
Referenced by aggregates(), cleanupParamchange(), newOutputInfo(), and readData().
aggSteps
int** aggSteps = NULL static
Definition at line 31 of file paramchange.c.
Referenced by aggedDifference(), cleanupParamchange(), and readFileForAgg().
data
double*** data static
Definition at line 18 of file paramchange.c.
Referenced by aggedDifference(), aggregates(), cleanupParamchange(), difference(), readData(), and readFileForAgg().
endOpt
int * endOpt static
Definition at line 25 of file paramchange.c.
Referenced by aggedDifference(), cleanupParamchange(), difference(), readData(), and readFileForAgg().
model
double** model static
Definition at line 24 of file paramchange.c.
Referenced by aggedDifference(), aggregates(), cleanupParamchange(), difference(), main(), metropolis(), readData(), and reset().
numAggSteps
int* numAggSteps = NULL static
Definition at line 29 of file paramchange.c.
Referenced by aggedDifference(), cleanupParamchange(), and readFileForAgg().
numLocs
double numLocs static
Definition at line 16 of file paramchange.c.
Referenced by cleanupModel(), cleanupParamchange(), freeClimateList(), initEvents(), initModel(), initModel(), initModel(), main(), metropolis(), newSpatialParams(), newSpatialParams(), readClimData(), readData(), readEventData(), readFileForAgg(), readIndicesFile(), readOneSpatialParam(), readParamData(), readSpatialParams(), readSpatialValues(), resetSpatialParams(), run(), runTestMulti(), runTestSimple(), and writeBestSpatialParams().
sigmas
double*** sigmas static
Definition at line 21 of file paramchange.c.
Referenced by cleanupParamchange(), difference(), and readData().
startOpt
int* startOpt static
Definition at line 25 of file paramchange.c.
Referenced by aggedDifference(), cleanupParamchange(), difference(), readData(), and readFileForAgg().
unaggedWeight
double unaggedWeight = 0.0 static
Definition at line 39 of file paramchange.c.
Referenced by aggedDifference(), main(), and readFileForAgg().
valid
int*** valid static
Definition at line 26 of file paramchange.c.
Referenced by aggedDifference(), cleanupParamchange(), difference(), and readData().