SIPNET: spatialParams.h File Reference
spatialParams.h File Reference
#include <stdio.h>
Data Structures
struct OneSpatialParamStruct
struct SpatialParamsStruct
Macros
#define PARAM_MAXNAME 64
Typedefs
typedef struct OneSpatialParamStruct OneSpatialParam
typedef struct SpatialParamsStruct SpatialParams
Functions
SpatialParams * newSpatialParams (int maxParameters, int numLocs)
void initializeOneSpatialParam (SpatialParams *spatialParams, char *name, double *externalLoc, int isRequired)
void readSpatialParams (SpatialParams *spatialParams, FILE *paramFile, FILE *spatialParamFile)
int getNumParameters (SpatialParams *spatialParams)
int getNumParamsRead (SpatialParams *spatialParams)
int locateParam (SpatialParams *spatialParams, char *name)
int valueSet (SpatialParams *spatialParams, int i)
int isSpatial (SpatialParams *spatialParams, int i)
int isChangeable (SpatialParams *spatialParams, int i)
int checkSpatialParam (SpatialParams *spatialParams, int i, double value)
double getSpatialParam (SpatialParams *spatialParams, int i, int loc)
void setSpatialParam (SpatialParams *spatialParams, int i, int loc, double value)
double getSpatialParamGuess (SpatialParams *spatialParams, int i, int loc)
double getSpatialParamMin (SpatialParams *spatialParams, int i)
double getSpatialParamMax (SpatialParams *spatialParams, int i)
double getSpatialParamSigma (SpatialParams *spatialParams, int i)
double getSpatialParamKnob (SpatialParams *spatialParams, int i, int loc)
void setSpatialParamKnob (SpatialParams *spatialParams, int i, int loc, double value)
double getSpatialParamBest (SpatialParams *spatialParams, int i, int loc)
void setSpatialParamBest (SpatialParams *spatialParams, int i, int loc, double value)
void setAllSpatialParamBests (SpatialParams *spatialParams, int loc)
int randomChangeableSpatialParam (SpatialParams *spatialParams)
void loadSpatialParams (SpatialParams *spatialParams, int loc)
void resetSpatialParams (SpatialParams *spatialParams, double knob, int randomReset)
void writeBestSpatialParams (SpatialParams *spatialParams, char *paramFile, char *spatialParamFile)
void writeChangeableParamInfo (SpatialParams *spatialParams, int loc, FILE *outF)
void deleteSpatialParams (SpatialParams *spatialParams)
Macro Definition Documentation
PARAM_MAXNAME
#define PARAM_MAXNAME 64
Definition at line 9 of file spatialParams.h.
Typedef Documentation
OneSpatialParam
typedef struct OneSpatialParamStruct OneSpatialParam
SpatialParams
typedef struct SpatialParamsStruct SpatialParams
Function Documentation
checkSpatialParam()
int checkSpatialParam (SpatialParams * spatialParams, int i, double value)
Definition at line 419 of file spatialParams.c.
References getSpatialParamMax(), and getSpatialParamMin().
Referenced by metropolis().
deleteSpatialParams()
void deleteSpatialParams (SpatialParams * spatialParams)
Definition at line 754 of file spatialParams.c.
References OneSpatialParamStruct::best, SpatialParamsStruct::changeableParamIndices, OneSpatialParamStruct::guess, OneSpatialParamStruct::knob, SpatialParamsStruct::numParameters, SpatialParamsStruct::parameters, SpatialParamsStruct::readIndices, and OneSpatialParamStruct::value.
Referenced by main().
getNumParameters()
int getNumParameters (SpatialParams * spatialParams)
Definition at line 366 of file spatialParams.c.
References SpatialParamsStruct::numParameters.
getNumParamsRead()
int getNumParamsRead (SpatialParams * spatialParams)
Definition at line 371 of file spatialParams.c.
References SpatialParamsStruct::numParamsRead.
Referenced by writeBestSpatialParams(), and writeChangeableParamInfo().
getSpatialParam()
double getSpatialParam (SpatialParams * spatialParams, int i, int loc)
Definition at line 428 of file spatialParams.c.
References getPossiblySpatial(), isSpatial(), SpatialParamsStruct::parameters, and OneSpatialParamStruct::value.
Referenced by loadSpatialParams(), metropolis(), setAllSpatialParamBests(), writeChainInfo(), writeChangeableParamInfo(), writeHistFile(), and writeHistFileBin().
getSpatialParamBest()
double getSpatialParamBest (SpatialParams * spatialParams, int i, int loc)
Definition at line 500 of file spatialParams.c.
References OneSpatialParamStruct::best, getPossiblySpatial(), isSpatial(), and SpatialParamsStruct::parameters.
Referenced by writeBestSpatialParams(), writeChainInfo(), and writeChangeableParamInfo().
getSpatialParamGuess()
double getSpatialParamGuess (SpatialParams * spatialParams, int i, int loc)
Definition at line 449 of file spatialParams.c.
References getPossiblySpatial(), OneSpatialParamStruct::guess, isSpatial(), and SpatialParamsStruct::parameters.
Referenced by resetSpatialParams(), and writeChangeableParamInfo().
getSpatialParamKnob()
double getSpatialParamKnob (SpatialParams * spatialParams, int i, int loc)
Definition at line 479 of file spatialParams.c.
References getPossiblySpatial(), isSpatial(), OneSpatialParamStruct::knob, and SpatialParamsStruct::parameters.
Referenced by metropolis(), writeChainInfo(), and writeChangeableParamInfo().
getSpatialParamMax()
double getSpatialParamMax (SpatialParams * spatialParams, int i)
Definition at line 464 of file spatialParams.c.
References OneSpatialParamStruct::max, and SpatialParamsStruct::parameters.
Referenced by checkSpatialParam(), metropolis(), resetSpatialParams(), writeBestSpatialParams(), and writeChangeableParamInfo().
getSpatialParamMin()
double getSpatialParamMin (SpatialParams * spatialParams, int i)
Definition at line 457 of file spatialParams.c.
References OneSpatialParamStruct::min, and SpatialParamsStruct::parameters.
Referenced by checkSpatialParam(), metropolis(), resetSpatialParams(), writeBestSpatialParams(), and writeChangeableParamInfo().
getSpatialParamSigma()
double getSpatialParamSigma (SpatialParams * spatialParams, int i)
Definition at line 471 of file spatialParams.c.
References SpatialParamsStruct::parameters, and OneSpatialParamStruct::sigma.
Referenced by writeBestSpatialParams().
initializeOneSpatialParam()
void initializeOneSpatialParam (SpatialParams * spatialParams, char * name, double * externalLoc, int isRequired)
Definition at line 168 of file spatialParams.c.
References allParamsInitialized(), OneSpatialParamStruct::externalLoc, OneSpatialParamStruct::isRequired, SpatialParamsStruct::maxParameters, OneSpatialParamStruct::name, SpatialParamsStruct::numParameters, SpatialParamsStruct::parameters, and OneSpatialParamStruct::value.
Referenced by readParamData().
isChangeable()
int isChangeable (SpatialParams * spatialParams, int i)
Definition at line 412 of file spatialParams.c.
References OneSpatialParamStruct::isChangeable, and SpatialParamsStruct::parameters.
Referenced by resetSpatialParams(), writeBestSpatialParams(), and writeChangeableParamInfo().
isSpatial()
int isSpatial (SpatialParams * spatialParams, int i)
Definition at line 405 of file spatialParams.c.
References OneSpatialParamStruct::numLocs, and SpatialParamsStruct::parameters.
Referenced by getPossiblySpatial(), getSpatialParam(), getSpatialParamBest(), getSpatialParamGuess(), getSpatialParamKnob(), metropolis(), readChainInfo(), resetSpatialParams(), setAllSpatialParamBests(), setPossiblySpatial(), setSpatialParam(), setSpatialParamBest(), setSpatialParamKnob(), writeBestSpatialParams(), writeChainInfo(), and writeChangeableParamInfo().
loadSpatialParams()
void loadSpatialParams (SpatialParams * spatialParams, int loc)
Definition at line 577 of file spatialParams.c.
References OneSpatialParamStruct::externalLoc, getSpatialParam(), SpatialParamsStruct::numParameters, SpatialParamsStruct::parameters, and valueSet().
Referenced by setupModel().
locateParam()
int locateParam (SpatialParams * spatialParams, char * name)
Definition at line 377 of file spatialParams.c.
References OneSpatialParamStruct::name, SpatialParamsStruct::parameters, and strcmpIgnoreCase().
Referenced by main(), and readSpatialParams().
newSpatialParams()
SpatialParams * newSpatialParams (int maxParameters, int numLocs)
Definition at line 137 of file spatialParams.c.
References SpatialParamsStruct::changeableParamIndices, SpatialParamsStruct::maxParameters, SpatialParamsStruct::numChangeableParams, numLocs, SpatialParamsStruct::numLocs, SpatialParamsStruct::numParameters, SpatialParamsStruct::numParamsRead, SpatialParamsStruct::parameters, and SpatialParamsStruct::readIndices.
Referenced by readParamData().
randomChangeableSpatialParam()
int randomChangeableSpatialParam (SpatialParams * spatialParams)
Definition at line 557 of file spatialParams.c.
References SpatialParamsStruct::changeableParamIndices, and SpatialParamsStruct::numChangeableParams.
Referenced by metropolis().
readSpatialParams()
void readSpatialParams (SpatialParams * spatialParams, FILE * paramFile, FILE * spatialParamFile)
Definition at line 221 of file spatialParams.c.
References OneSpatialParamStruct::best, SpatialParamsStruct::changeableParamIndices, checkAllRead(), OneSpatialParamStruct::guess, OneSpatialParamStruct::isChangeable, OneSpatialParamStruct::knob, locateParam(), OneSpatialParamStruct::max, OneSpatialParamStruct::min, SpatialParamsStruct::numChangeableParams, numLocs, OneSpatialParamStruct::numLocs, SpatialParamsStruct::numLocs, SpatialParamsStruct::numParamsRead, PARAM_MAXNAME, SpatialParamsStruct::parameters, SpatialParamsStruct::readIndices, readSpatialValues(), SEPARATORS, OneSpatialParamStruct::sigma, stripComment(), OneSpatialParamStruct::value, and valueSet().
Referenced by readParamData().
resetSpatialParams()
void resetSpatialParams (SpatialParams * spatialParams, double knob, int randomReset)
Definition at line 603 of file spatialParams.c.
References getSpatialParamGuess(), getSpatialParamMax(), getSpatialParamMin(), isChangeable(), isSpatial(), numLocs, SpatialParamsStruct::numLocs, SpatialParamsStruct::numParameters, setSpatialParam(), setSpatialParamBest(), setSpatialParamKnob(), and valueSet().
Referenced by reset().
setAllSpatialParamBests()
void setAllSpatialParamBests (SpatialParams * spatialParams, int loc)
Definition at line 522 of file spatialParams.c.
References getSpatialParam(), isSpatial(), SpatialParamsStruct::numLocs, SpatialParamsStruct::numParameters, setSpatialParamBest(), and valueSet().
Referenced by metropolis().
setSpatialParam()
void setSpatialParam (SpatialParams * spatialParams, int i, int loc, double value)
Definition at line 439 of file spatialParams.c.
References isSpatial(), SpatialParamsStruct::numLocs, SpatialParamsStruct::parameters, setPossiblySpatial(), and OneSpatialParamStruct::value.
Referenced by main(), metropolis(), readChainInfo(), resetSpatialParams(), and sensTest().
setSpatialParamBest()
void setSpatialParamBest (SpatialParams * spatialParams, int i, int loc, double value)
Definition at line 511 of file spatialParams.c.
References OneSpatialParamStruct::best, isSpatial(), SpatialParamsStruct::numLocs, SpatialParamsStruct::parameters, and setPossiblySpatial().
Referenced by readChainInfo(), resetSpatialParams(), and setAllSpatialParamBests().
setSpatialParamKnob()
void setSpatialParamKnob (SpatialParams * spatialParams, int i, int loc, double value)
Definition at line 490 of file spatialParams.c.
References isSpatial(), OneSpatialParamStruct::knob, SpatialParamsStruct::numLocs, SpatialParamsStruct::parameters, and setPossiblySpatial().
Referenced by metropolis(), readChainInfo(), and resetSpatialParams().
valueSet()
int valueSet (SpatialParams * spatialParams, int i)
Definition at line 398 of file spatialParams.c.
References SpatialParamsStruct::parameters, and OneSpatialParamStruct::value.
Referenced by loadSpatialParams(), readSpatialParams(), resetSpatialParams(), and setAllSpatialParamBests().
writeBestSpatialParams()
void writeBestSpatialParams (SpatialParams * spatialParams, char * paramFile, char * spatialParamFile)
Definition at line 657 of file spatialParams.c.
References getNumParamsRead(), getSpatialParamBest(), getSpatialParamMax(), getSpatialParamMin(), getSpatialParamSigma(), isChangeable(), isSpatial(), OneSpatialParamStruct::name, numLocs, SpatialParamsStruct::numLocs, openFile(), SpatialParamsStruct::parameters, and SpatialParamsStruct::readIndices.
Referenced by main().
writeChangeableParamInfo()
void writeChangeableParamInfo (SpatialParams * spatialParams, int loc, FILE * outF)
Definition at line 708 of file spatialParams.c.
References getNumParamsRead(), getSpatialParam(), getSpatialParamBest(), getSpatialParamGuess(), getSpatialParamKnob(), getSpatialParamMax(), getSpatialParamMin(), isChangeable(), isSpatial(), OneSpatialParamStruct::name, SpatialParamsStruct::parameters, and SpatialParamsStruct::readIndices.
Referenced by metropolis(), and reset().