SIPNET: climsteps.m File Reference
climsteps.m File Reference
Functions
Bill Sacks Modified function climsteps (stepLength, obsStepLength, directory_clim, directory_fluxes) % for each of tair
Bill Sacks Modified function and take hourly (or half-hourly) data and % aggregate up to timesteps of given stepLength(in % observational time steps) %(by just taking the mean across a timestep) % Also determine valid fraction for nee
Bill Sacks Modified function and take and soilwetness Assumes that (total # observational time steps)/stepLength is an integer %(if not
Bill Sacks Modified function and take and soilwetness Assumes throws out last fraction of a time step obsStepLength gives the length of each observational time step (in % seconds)(e.g. 3600 for harvard
[directory_clim '/tairfill'] load ()
disp ('loaded tair')
disp ('loaded vpd')
disp ('loaded vpdsoil')
disp ('loaded vpress')
disp ('loaded par')
disp ('loaded tsoil')
disp ('loaded wspd')
disp ('loaded ppt')
disp ('loaded nee')
disp ('loaded fh2o')
disp ('loaded soilwetness')
or for each point disp ('loaded neevalid')
or for each point disp ('loaded fh2ovalid')
disp ('starting loop')
Note we print to file as we rather than saving to vectors and then just printing at the to save memory (it % gets slow to do the latter with large vectors) for i
indices counts[1, 2, 3] etc fprintf (tairf, '%.7e\n', mean(tair(indices)))
fprintf (vpdf, '%.7e\n', mean(vpd(indices)))
fprintf (vpdsoilf, '%.7e\n', mean(vpdsoil(indices)))
fprintf (vpressf, '%.7e\n', mean(vpress(indices)))
fprintf (parf, '%.7e\n', sum(par(indices) *obsStepLength./1.E6))
par is input as sum over entire timestep fprintf (tsoilf, '%.7e\n', mean(tsoil(indices)))
fprintf (wspdf, '%.7e\n', mean(wspd(indices)))
pptstep (i)
OLD sum (ppt(indices)))
ppt is input as sum over entire timestep fprintf (neef, '%.7e\n', sum(nee(indices)))
nee is input as sum over entire timestep fprintf (fh2of, '%.7e\n', sum(fh2o(indices)))
fh2o is input as sum over entire timestep fprintf (neevalidf, '%.7e\n', mean(neevalid(indices)))
fraction of valid pts in this step fprintf (fh2ovalidf, '%.7e\n', mean(fh2ovalid(indices)))
the measured points in this step if (length(soilwetness_measuredpts >=1)) % at least one measured % point fprintf(soilwetnessf
the measured points in this step min (mean(soilwetnessfrac(soilwetness_measuredpts)), 1))
don t let soilwetness go higher than fprintf (soilwetnessvalidf, '%.7e\n', 1)
else no measured points fprintf (soilwetnessf, '%.7e\n', 0)
arbitrary fprintf (soilwetnessvalidf, '%.7e\n', 0)
end end fclose (tairf)
fclose (vpdf)
fclose (vpdsoilf)
fclose (vpressf)
fclose (parf)
fclose (tsoilf)
fclose (wspdf)
fclose (pptf)
fclose (neef)
fclose (fh2of)
fclose (soilwetnessf)
fclose (neevalidf)
fclose (fh2ovalidf)
fclose (soilwetnessvalidf)
Variables
Bill Sacks Modified function vpd = load([directory_clim '/vpdfill'])
Bill Sacks Modified function vpdsoil = load([directory_clim '/vpdsoilfill'])
Bill Sacks Modified function vpress = load([directory_clim '/vpressfill'])
Bill Sacks Modified function par = load([directory_clim '/parfill'])
Bill Sacks Modified function tsoil = load([directory_clim '/tsoilfill'])
Bill Sacks Modified function wspd = load([directory_clim '/wspdfill'])
Bill Sacks Modified function ppt = load([directory_clim '/precipfill'])
Bill Sacks Modified function nee = load([directory_fluxes '/neefill'])
Bill Sacks Modified function fh2o = load([directory_fluxes '/fh2ofill'])
Bill Sacks Modified function and soilwetness = load([directory_clim '/soilwetness'])
Bill Sacks Modified function and take and soilwetness Assumes throws out last fraction of a time step obsStepLength gives the length of each observational time for niwot Input and output are from the given directories soilwetness_upperlimit = 0.95
neevalid = load([directory_fluxes '/neevalid'])
fh2ovalid = load([directory_fluxes '/fh2ovalid'])
soilwetness_sorted
maxsoilwetness
soilwetnessfrac = soilwetness/maxsoilwetness
nobssteps = length(nee)
nsteps = nobssteps/stepLength
tairf = fopen([directory_clim '/tairstep'], 'w')
vpdf = fopen([directory_clim '/vpdstep'], 'w')
vpdsoilf = fopen([directory_clim '/vpdsoilstep'], 'w')
vpressf = fopen([directory_clim '/vpressstep'], 'w')
parf = fopen([directory_clim '/parstep'], 'w')
tsoilf = fopen([directory_clim '/tsoilstep'], 'w')
wspdf = fopen([directory_clim '/wspdstep'], 'w')
pptf = fopen([directory_clim '/pptstep'], 'w')
neef = fopen([directory_fluxes '/neestep'], 'w')
fh2of = fopen([directory_fluxes '/fh2ostep'], 'w')
soilwetnessf = fopen([directory_clim, '/soilwetnessstep'], 'w')
neevalidf = fopen([directory_fluxes '/neevalidstep'], 'w')
fh2ovalidf = fopen([directory_fluxes '/fh2ovalidstep'], 'w')
soilwetnessvalidf = fopen([directory_clim, '/soilwetnessvalidstep'], 'w')
Note __pad0__
Note we print to file as we go
Note we print to file as we rather than saving to vectors and then just printing at the end
end indices = ((i-1)*stepLength + 1):(i*stepLength)
indices counts[1, 2, 3] then [4, 5, 6]
OLD __pad1__
OLD n
soilwetness __pad2__
Function Documentation
climsteps()
Bill Sacks Modified function climsteps (stepLength , obsStepLength , directory_clim , directory_fluxes)
disp() [1/14]
disp ('loaded fh2o')
disp() [2/14]
or for each point disp ('loaded fh2ovalid')
disp() [3/14]
disp ('loaded nee')
disp() [4/14]
or for each point disp ('loaded neevalid')
disp() [5/14]
disp ('loaded par')
disp() [6/14]
disp ('loaded ppt')
disp() [7/14]
disp ('loaded soilwetness')
disp() [8/14]
disp ('loaded tair')
disp() [9/14]
disp ('loaded tsoil')
disp() [10/14]
disp ('loaded vpd')
disp() [11/14]
disp ('loaded vpdsoil')
disp() [12/14]
disp ('loaded vpress')
disp() [13/14]
disp ('loaded wspd')
disp() [14/14]
disp ('starting loop')
fclose() [1/14]
fclose (fh2of)
fclose() [2/14]
fclose (fh2ovalidf)
fclose() [3/14]
fclose (neef)
fclose() [4/14]
fclose (neevalidf)
fclose() [5/14]
fclose (parf)
fclose() [6/14]
fclose (pptf)
fclose() [7/14]
fclose (soilwetnessf)
fclose() [8/14]
fclose (soilwetnessvalidf)
fclose() [9/14]
end end fclose (tairf)
Referenced by closeOutputItemFile(), copyFile(), copyFile(), countLines(), main(), metropolis(), readChainInfo(), readClimData(), readData(), readEventData(), readFileForAgg(), readGirdlingData(), readIndicesFile(), readNamelistInputs(), readOptions(), readParamData(), writeBestSpatialParams(), and writeChainInfo().
fclose() [10/14]
fclose (tsoilf)
fclose() [11/14]
fclose (vpdf)
fclose() [12/14]
fclose (vpdsoilf)
fclose() [13/14]
fclose (vpressf)
fclose() [14/14]
fclose (wspdf)
fprintf() [1/14]
nee is input as sum over entire timestep fprintf (fh2of , '%.7e\n' , sum(fh2o(indices)))
fprintf() [2/14]
fraction of valid pts in this step fprintf (fh2ovalidf , '%.7e\n' , mean(fh2ovalid(indices)))
fprintf() [3/14]
ppt is input as sum over entire timestep fprintf (neef , '%.7e\n' , sum(nee(indices)))
fprintf() [4/14]
fh2o is input as sum over entire timestep fprintf (neevalidf , '%.7e\n' , mean(neevalid(indices)))
fprintf() [5/14]
fprintf (parf , '%.7e\n' , sum(par(indices) *obsStepLength./1.E6))
fprintf() [6/14]
else no measured points fprintf (soilwetnessf , '%.7e\n' , 0)
fprintf() [7/14]
arbitrary fprintf (soilwetnessvalidf , '%.7e\n' , 0)
fprintf() [8/14]
don t let soilwetness go higher than fprintf (soilwetnessvalidf , '%.7e\n' , 1)
fprintf() [9/14]
indices counts[1, 2, 3] etc fprintf (tairf , '%.7e\n' , mean(tair(indices)))
References mean().
fprintf() [10/14]
par is input as sum over entire timestep fprintf (tsoilf , '%.7e\n' , mean(tsoil(indices)))
References mean().
fprintf() [11/14]
fprintf (vpdf , '%.7e\n' , mean(vpd(indices)))
References mean().
fprintf() [12/14]
fprintf (vpdsoilf , '%.7e\n' , mean(vpdsoil(indices)))
References mean().
fprintf() [13/14]
fprintf (vpressf , '%.7e\n' , mean(vpress(indices)))
References mean().
fprintf() [14/14]
fprintf (wspdf , '%.7e\n' , mean(wspd(indices)))
References mean().
hourly()
Bill Sacks Modified function and take hourly (or half- hourly)
if()
the measured points in this step if (length(soilwetness_measuredpts >=1))
load()
[directory_clim '/tairfill'] load () virtual
memory()
Note we print to file as we rather than saving to vectors and then just printing at the to save memory (it % gets slow to do the latter with large vectors)
min()
the measured points in this step min (mean(soilwetnessfrac(soilwetness_measuredpts)) , 1)
Referenced by readOneSpatialParam(), and readSpatialParams().
pptstep()
pptstep (i)
step()
Bill Sacks Modified function and take and soilwetness Assumes throws out last fraction of a time step obsStepLength gives the length of each observational time step (in % seconds)
sum()
OLD sum (ppt(indices))
Referenced by aggregates(), readFileForAgg(), and sumArray().
that()
Bill Sacks Modified function and take and soilwetness Assumes that (total # observational time steps)
Variable Documentation
__pad0__
Note __pad0__
Definition at line 80 of file preprocess/climsteps.m.
__pad1__
OLD __pad1__
Definition at line 97 of file preprocess/climsteps.m.
__pad2__
soilwetness __pad2__
Definition at line 108 of file preprocess/climsteps.m.
end
Note we print to file as we rather than saving to vectors and then just printing at the end
Definition at line 81 of file preprocess/climsteps.m.
fh2o
fh2o = load([directory_fluxes '/fh2ofill'])
Definition at line 7 of file preprocess/climsteps.m.
fh2of
fh2of = fopen([directory_fluxes '/fh2ostep'], 'w')
Definition at line 72 of file preprocess/climsteps.m.
fh2ovalid
fh2ovalid = load([directory_fluxes '/fh2ovalid'])
Definition at line 50 of file preprocess/climsteps.m.
fh2ovalidf
fh2ovalidf = fopen([directory_fluxes '/fh2ovalidstep'], 'w')
Definition at line 75 of file preprocess/climsteps.m.
go
Note we print to file as we go
Definition at line 80 of file preprocess/climsteps.m.
indices
end indices = ((i-1)*stepLength + 1):(i*stepLength)
Definition at line 87 of file preprocess/climsteps.m.
Referenced by main().
maxsoilwetness
maxsoilwetness
Initial value:
= soilwetness_sorted(round(soilwetness_upperlimit* ...
                                            length(soilwetness_sorted)))
Definition at line 56 of file preprocess/climsteps.m.
n
the measured points in this step n
Definition at line 98 of file preprocess/climsteps.m.
nee
nee = load([directory_fluxes '/neefill'])
Definition at line 6 of file preprocess/climsteps.m.
neef
neef = fopen([directory_fluxes '/neestep'], 'w')
Definition at line 71 of file preprocess/climsteps.m.
neevalid
neevalid = load([directory_fluxes '/neevalid'])
Definition at line 47 of file preprocess/climsteps.m.
neevalidf
neevalidf = fopen([directory_fluxes '/neevalidstep'], 'w')
Definition at line 74 of file preprocess/climsteps.m.
nobssteps
nobssteps = length(nee)
Definition at line 60 of file preprocess/climsteps.m.
nsteps
nsteps = nobssteps/stepLength
Definition at line 61 of file preprocess/climsteps.m.
par
par = load([directory_clim '/parfill'])
Definition at line 6 of file preprocess/climsteps.m.
parf
parf = fopen([directory_clim '/parstep'], 'w')
Definition at line 67 of file preprocess/climsteps.m.
Referenced by main().
ppt
ppt = load([directory_clim '/precipfill'])
Definition at line 6 of file preprocess/climsteps.m.
pptf
pptf = fopen([directory_clim '/pptstep'], 'w')
Definition at line 70 of file preprocess/climsteps.m.
Referenced by main().
soilwetness
soilwetness = load([directory_clim '/soilwetness'])
Definition at line 7 of file preprocess/climsteps.m.
soilwetness_sorted
soilwetness_sorted
Initial value:
= ...
      sort(soilwetness(find(isfinite(soilwetness))))
Definition at line 54 of file preprocess/climsteps.m.
soilwetness_upperlimit
Bill Sacks Modified function and take and soilwetness Assumes throws out last fraction of a time step obsStepLength gives the length of each observational time for niwot Input and output are from the given directories soilwetness_upperlimit = 0.95
Definition at line 22 of file preprocess/climsteps.m.
soilwetnessf
soilwetnessf = fopen([directory_clim, '/soilwetnessstep'], 'w')
Definition at line 73 of file preprocess/climsteps.m.
Referenced by main().
soilwetnessfrac
soilwetnessfrac = soilwetness/maxsoilwetness
Definition at line 58 of file preprocess/climsteps.m.
soilwetnessvalidf
soilwetnessvalidf = fopen([directory_clim, '/soilwetnessvalidstep'], 'w')
Definition at line 76 of file preprocess/climsteps.m.
tairf
tairf = fopen([directory_clim '/tairstep'], 'w')
Definition at line 63 of file preprocess/climsteps.m.
Referenced by main().
then
indices counts [1,2,3] then[4, 5, 6]
Definition at line 88 of file preprocess/climsteps.m.
tsoil
tsoil = load([directory_clim '/tsoilfill'])
Definition at line 6 of file preprocess/climsteps.m.
tsoilf
tsoilf = fopen([directory_clim '/tsoilstep'], 'w')
Definition at line 68 of file preprocess/climsteps.m.
Referenced by main().
vpd
vpd = load([directory_clim '/vpdfill'])
Definition at line 6 of file preprocess/climsteps.m.
vpdf
vpdf = fopen([directory_clim '/vpdstep'], 'w')
Definition at line 64 of file preprocess/climsteps.m.
Referenced by main().
vpdsoil
vpdsoil = load([directory_clim '/vpdsoilfill'])
Definition at line 6 of file preprocess/climsteps.m.
vpdsoilf
vpdsoilf = fopen([directory_clim '/vpdsoilstep'], 'w')
Definition at line 65 of file preprocess/climsteps.m.
vpress
vpress = load([directory_clim '/vpressfill'])
Definition at line 6 of file preprocess/climsteps.m.
vpressf
vpressf = fopen([directory_clim '/vpressstep'], 'w')
Definition at line 66 of file preprocess/climsteps.m.
Referenced by main().
wspd
wspd = load([directory_clim '/wspdfill'])
Definition at line 6 of file preprocess/climsteps.m.
wspdf
wspdf = fopen([directory_clim '/wspdstep'], 'w')
Definition at line 69 of file preprocess/climsteps.m.
Referenced by main().