SIPNET: testEventInfra.c File Reference
testEventInfra.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "modelStructures.h"
#include "../utils.h"
#include "../../../events.c"
Functions
int checkEvent (EventNode *event, int loc, int year, int day, enum EventType type)
int checkHarvestParams (HarvestParams *params, double fracRemAbove, double fracRemBelow, double fracTransAbove, double fracTransBelow)
int checkIrrigationParams (IrrigationParams *params, double amountAdded, int method)
int checkFertilizationParams (FertilizationParams *params, double orgN, double orgC, double minN)
int checkPlantingParams (PlantingParams *params, int emergenceLag, double addedC, double addedN)
int checkTillageParams (TillageParams *params, double fracLitterTransferred, double somDecompModifier, double litterDecompModifier)
int init ()
int runTestSimple ()
int runTestMulti ()
int run ()
void cleanup ()
int main ()
Function Documentation
checkEvent()
int checkEvent (EventNode * event, int loc, int year, int day, enum EventType type)
Definition at line 9 of file testEventInfra.c.
References day, index, printEvent(), and year.
Referenced by runTestMulti(), and runTestSimple().
checkFertilizationParams()
int checkFertilizationParams (FertilizationParams * params, double orgN, double orgC, double minN)
Definition at line 48 of file testEventInfra.c.
References compareDoubles(), and params.
Referenced by runTestMulti(), and runTestSimple().
checkHarvestParams()
int checkHarvestParams (HarvestParams * params, double fracRemAbove, double fracRemBelow, double fracTransAbove, double fracTransBelow)
Definition at line 23 of file testEventInfra.c.
References compareDoubles(), index, and params.
Referenced by runTestMulti(), and runTestSimple().
checkIrrigationParams()
int checkIrrigationParams (IrrigationParams * params, double amountAdded, int method)
Definition at line 37 of file testEventInfra.c.
References compareDoubles(), and params.
Referenced by runTestMulti(), and runTestSimple().
checkPlantingParams()
int checkPlantingParams (PlantingParams * params, int emergenceLag, double addedC, double addedN)
Definition at line 61 of file testEventInfra.c.
References compareDoubles(), and params.
Referenced by runTestMulti(), and runTestSimple().
checkTillageParams()
int checkTillageParams (TillageParams * params, double fracLitterTransferred, double somDecompModifier, double litterDecompModifier)
Definition at line 71 of file testEventInfra.c.
References compareDoubles(), index, and params.
Referenced by runTestMulti(), and runTestSimple().
cleanup()
void cleanup ()
Definition at line 206 of file testEventInfra.c.
Referenced by main().
init()
int init ()
Definition at line 84 of file testEventInfra.c.
Referenced by main().
main()
int main ()
Definition at line 211 of file testEventInfra.c.
References cleanup(), exit(), index, init(), and run().
run()
int run ()
Definition at line 189 of file testEventInfra.c.
References index, runTestMulti(), and runTestSimple().
Referenced by main().
runTestMulti()
int runTestMulti ()
Definition at line 124 of file testEventInfra.c.
References checkEvent(), checkFertilizationParams(), checkHarvestParams(), checkIrrigationParams(), checkPlantingParams(), checkTillageParams(), FERTILIZATION, HARVEST, index, IRRIGATION, numLocs, PLANTING, readEventData(), and TILLAGE.
Referenced by run().
runTestSimple()
int runTestSimple ()
Definition at line 94 of file testEventInfra.c.
References checkEvent(), checkFertilizationParams(), checkHarvestParams(), checkIrrigationParams(), checkPlantingParams(), checkTillageParams(), FERTILIZATION, HARVEST, index, IRRIGATION, numLocs, PLANTING, readEventData(), and TILLAGE.
Referenced by run().