SIPNET: util.c File Reference
util.c File Reference
#include <time.h>
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <ctype.h>
#include "util.h"
Functions
void buildFileName (char *filename, const char *base, const char *ext)
FILE * openFile (const char *name, const char *mode)
FILE * openFileExt (const char *name, const char *ext, const char *mode)
void seedRand (unsigned int seed, FILE *outF)
double randm (void)
double * makeArray (int size)
double ** make2DArray (int nrows, int ncols)
int ** make2DIntArray (int nrows, int ncols)
void free2DArray (void **arr)
void assignArray (double *out, double *in, int n)
double sumArray (double *array, int length)
int strcmpIgnoreCase (const char *s1, const char *s2)
int stripComment (char *line, const char *commentChars)
Function Documentation
assignArray()
void assignArray (double * out, double * in, int n)
Definition at line 134 of file util.c.
buildFileName()
void buildFileName (char * filename, const char * base, const char * ext)
Definition at line 18 of file util.c.
Referenced by main(), and openFileExt().
free2DArray()
void free2DArray (void ** arr)
Definition at line 128 of file util.c.
Referenced by cleanupParamchange(), main(), and metropolis().
make2DArray()
double ** make2DArray (int nrows, int ncols)
Definition at line 95 of file util.c.
Referenced by main(), metropolis(), readData(), and readFileForAgg().
make2DIntArray()
int ** make2DIntArray (int nrows, int ncols)
Definition at line 111 of file util.c.
Referenced by readData().
makeArray()
double * makeArray (int size)
Definition at line 82 of file util.c.
Referenced by aggedDifference(), aggregates(), difference(), metropolis(), newOutputInfo(), and readData().
openFile()
FILE * openFile (const char * name, const char * mode)
Definition at line 25 of file util.c.
Referenced by copyFile(), countLines(), main(), metropolis(), openFileExt(), openOutputItemFile(), readChainInfo(), readClimData(), readData(), readEventData(), readFileForAgg(), readIndicesFile(), readNamelistInputs(), readParamData(), writeBestSpatialParams(), and writeChainInfo().
openFileExt()
FILE * openFileExt (const char * name, const char * ext, const char * mode)
Definition at line 37 of file util.c.
References buildFileName(), and openFile().
Referenced by main().
randm()
double randm (void)
Definition at line 71 of file util.c.
Referenced by metropolis().
seedRand()
void seedRand (unsigned int seed, FILE * outF)
Definition at line 52 of file util.c.
Referenced by main().
strcmpIgnoreCase()
int strcmpIgnoreCase (const char * s1, const char * s2)
Definition at line 157 of file util.c.
Referenced by locateNamelistInputItem(), locateParam(), main(), and readSpatialValues().
stripComment()
int stripComment (char * line, const char * commentChars)
Definition at line 188 of file util.c.
Referenced by readNamelistInputs(), and readSpatialParams().
sumArray()
double sumArray (double * array, int length)
Definition at line 143 of file util.c.
Referenced by metropolis(), and reset().