SIPNET: sipnet.h File Reference
sipnet.h File Reference
#include <stdio.h>
#include "spatialParams.h"
Macros
#define EXTRA_DATA_TYPES 0
#define MAX_DATA_TYPES 3
Functions
void printModelComponents (FILE *out)
char ** getDataTypeNames ()
int initModel (SpatialParams **spatialParams, int **steps, char *paramFile, char *climFile, char *optionsFile)
void cleanupModel (int numLocs)
void runModelNoOut (double **outArray, int numDataTypes, int dataTypeIndices[], SpatialParams *spatialParams, int loc)
void runModelOutput (FILE *out, int printHeader, SpatialParams *spatialParams, int loc)
void sensTest (FILE *out, int paramNum, double low, double high, int numRuns, SpatialParams *spatialParams, int loc)
Macro Definition Documentation
EXTRA_DATA_TYPES
#define EXTRA_DATA_TYPES 0
Definition at line 11 of file SIPNEToptsIn/sipnet.h.
MAX_DATA_TYPES
#define MAX_DATA_TYPES 3
Definition at line 20 of file SIPNEToptsIn/sipnet.h.
Function Documentation
cleanupModel()
void cleanupModel (int numLocs)
Definition at line 1916 of file sipnetvJan2007.c.
getDataTypeNames()
char ** getDataTypeNames ()
Definition at line 1832 of file sipnetvJan2007.c.
initModel()
int initModel (SpatialParams ** spatialParams, int ** steps, char * paramFile, char * climFile, char * optionsFile)
Definition at line 2585 of file sipnetGirdle.c.
References index, MEAN_GPP_SOIL_DAYS, MEAN_GPP_SOIL_MAX_ENTRIES, MEAN_NPP_DAYS, MEAN_NPP_MAX_ENTRIES, meanGPP, meanGPP, meanNPP, meanNPP, newMeanTracker(), numLocs, readClimData(), readGirdlingData(), readOptions(), readParamData(), and setupOutputPointers().
printModelComponents()
void printModelComponents (FILE * out)
Definition at line 1802 of file sipnetvJan2007.c.
runModelNoOut()
void runModelNoOut (double ** outArray, int numDataTypes, int dataTypeIndices[], SpatialParams * spatialParams, int loc)
Definition at line 1760 of file sipnetvJan2007.c.
runModelOutput()
void runModelOutput (FILE * out, int printHeader, SpatialParams * spatialParams, int loc)
Definition at line 1726 of file sipnetvJan2007.c.
sensTest()
void sensTest (FILE * out, int paramNum, double low, double high, int numRuns, SpatialParams * spatialParams, int loc)
Definition at line 1781 of file sipnetvJan2007.c.