SIPNET: nnregress.m File Reference
nnregress.m File Reference
Typedefs
using beta. state = ones(1, 4)
Functions
if (nargin< 3|isempty(nhidden)) nhidden
Default options vector options (2)
Absolute precision for weights options (3)
Precision for error function options (14)
Number of cycles in inner loop options (1)
if (diag==1) fprintf(1
fprintf (1, 'nweights=%d\n\n', nweights)
warning ('off')
if (~isempty(warnstate)|isnan(net.alpha)|isnan(net.beta)) y
fprintf ('Warning:no evidence\n')
warning ('backtrace')
if (~isempty(warnstate)|isnan(net.alpha)|isnan(net.beta)|isnan(gamma)|net.alpha >900.) y
fprintf (1, 'alpha=%f ', net.alpha)
fprintf (1, 'gamma=%f ', gamma)
fprintf (1, 'error=%f ', err(end))
fprintf (1, 'satisfy=%d %d %d %d\n', satisfy)
end if (sum(satisfy)==4) break
end end if (k==nouter) fprintf(1
Evaluate error bars if (nargout > 2) hess
sig (n, k)
y (:, i)
rsq (i)
Variables
function [y, net, sig] = nnregress(x,t,nhidden,nstd,diag)
end whether to print all the info alpha_init = 0.005
Initial prior hyperparameter beta_init = 100.
Initial noise hyperparameter nouter = 500
Max number of outer loops ninner = 3
Number of inner loops toler = [.005 .005 .005 .005]
When to exit outer loop options = zeros(1,18)
Suppress warning messages [nx nin] = size(x)
if(nt ~=nx) error('Incompatible inputs end meanx =mean(x)
stdx =std(x)
meant =mean(t)
stdt =std(t)
for i =1:nin x(:,i) = (x(:,i)-meanx(i))./(nstd*stdx(i))
end Create and initialize network weight vector net = mlp(nin, nhidden, nout, 'linear', alpha_init, beta_init)
nweights = nhidden*(nin+1) + nout*(nhidden+1)
s n
s date
for k
warnstate =lastwarn
sig =0
net r2 =0
return
end [net, gamma] = evidence(net, x, t, ninner)
end state = [state
satisfy = abs(state(end,:)-state(end-1,:))./mean(state) < toler
err =err./nx
Cycle d
end end Warning
end Forward estimation y = mlpfwd(net, x)
invhess = inv(hess)
g = mlpderiv(net, x)
if(nargout > 2) sig(end end tout =t
R __pad0__
end end Save the configuration of this regression net opt nstd =nstd
net opt ninner_evi =ninner
net opt ninner_opt =options(14)
net opt minx =min(x)
net opt maxx =max(x)
Typedef Documentation
beta. state
using beta. state = ones(1,4)
Definition at line 46 of file nnregress.m.
Function Documentation
fprintf() [1/6]
fprintf ('Warning:no evidence\n')
fprintf() [2/6]
fprintf (1 , ' alpha = %f ', net. alpha)
References net.
fprintf() [3/6]
fprintf (1 , ' error = %f ', err(end))
fprintf() [4/6]
fprintf (1 , ' gamma = %f ', gamma)
fprintf() [5/6]
fprintf (1 , ' nweights = %d\n\n', nweights)
References and.
fprintf() [6/6]
fprintf (1 , ' satisfy = %d %d %d %d\n', satisfy)
if() [1/7]
if (diag = = 1)
Initial value:
=1:nout
                r=corrcoef(t(:,i),y(:,i))
if() [2/7]
end end if (k = = nouter)
if() [3/7]
if ()
if() [4/7]
Evaluate error bars if (nargout , 2)
if() [5/7]
end if (sum(satisfy) = =4)
if() [6/7]
if (~ isemptywarnstate)|isnan(net.alpha)|isnan(net.beta)
References net.
if() [7/7]
if (~isempty(warnstate)|isnan(net.alpha)|isnan(net.beta)|isnan(gamma)|net. alpha, 900.)
References net.
options() [1/4]
Number of cycles in inner loop options (1)
options() [2/4]
Precision for error function options (14)
options() [3/4]
Default options vector options (2)
options() [4/4]
Absolute precision for weights options (3)
rsq()
rsq (i)
sig()
sig (n , k)
warning() [1/2]
warning ('backtrace')
warning() [2/2]
warning ('off')
y()
y (: , i)
Variable Documentation
__pad0__
R __pad0__
Definition at line 118 of file nnregress.m.
alpha_init
net opt alpha_init = 0.005
Definition at line 13 of file nnregress.m.
beta_init
net opt beta_init = 100.
Definition at line 14 of file nnregress.m.
d
Cycle d
Definition at line 72 of file nnregress.m.
date
s date
Definition at line 41 of file nnregress.m.
end
end[net, gamma] = evidence(net, x, t, ninner)
Definition at line 58 of file nnregress.m.
err
err =err./nx
Definition at line 70 of file nnregress.m.
function
function[y, net, sig] = nnregress(x,t,nhidden,nstd,diag)
Definition at line 1 of file nnregress.m.
g
g = mlpderiv(net, x)
Definition at line 91 of file nnregress.m.
i
end Return to original units for i =1:nin x(:,i) = (x(:,i)-meanx(i))./(nstd*stdx(i))
Definition at line 33 of file nnregress.m.
invhess
net invhess = inv(hess)
Definition at line 90 of file nnregress.m.
k
for k
Initial value:
= 1:nouter
  lastwarn('')
Definition at line 48 of file nnregress.m.
maxx
net opt maxx =max(x)
Definition at line 133 of file nnregress.m.
meant
net opt meant =mean(t)
Definition at line 30 of file nnregress.m.
meanx
net opt meanx =mean(x)
Definition at line 28 of file nnregress.m.
messages
Suppress warning messages[nx nin] = size(x)
Definition at line 22 of file nnregress.m.
minx
net opt minx =min(x)
Definition at line 132 of file nnregress.m.
n
s n
Definition at line 41 of file nnregress.m.
net
net = mlp(nin, nhidden, nout, 'linear', alpha_init, beta_init)
Definition at line 37 of file nnregress.m.
Referenced by fprintf(), if(), if(), r2a(), and r2b().
ninner
Max number of outer loops ninner = 3
Definition at line 16 of file nnregress.m.
ninner_evi
net opt ninner_evi =ninner
Definition at line 126 of file nnregress.m.
ninner_opt
net opt ninner_opt =options(14)
Definition at line 127 of file nnregress.m.
nouter
net opt nouter = 500
Definition at line 15 of file nnregress.m.
nstd
end end Save the configuration of this regression net opt nstd =nstd
Definition at line 122 of file nnregress.m.
nweights
nweights = nhidden*(nin+1) + nout*(nhidden+1)
Definition at line 39 of file nnregress.m.
options
When to exit outer loop options = zeros(1,18)
Definition at line 18 of file nnregress.m.
r2
end net r2 =0
Definition at line 54 of file nnregress.m.
return
return
Definition at line 57 of file nnregress.m.
satisfy
satisfy = abs(state(end,:)-state(end-1,:))./mean(state) < toler
Definition at line 69 of file nnregress.m.
sig
end end sig =0
Definition at line 53 of file nnregress.m.
state
end state = [state
Definition at line 68 of file nnregress.m.
stdt
net opt stdt =std(t)
Definition at line 31 of file nnregress.m.
stdx
net opt stdx =std(x)
Definition at line 29 of file nnregress.m.
toler
Number of inner loops toler = [.005 .005 .005 .005]
Definition at line 17 of file nnregress.m.
tout
if (nargout > 2) sig(end end tout =t
Definition at line 110 of file nnregress.m.
Warning
end end Warning
Definition at line 81 of file nnregress.m.
warnstate
warnstate =lastwarn
Definition at line 51 of file nnregress.m.
y
end Forward estimation y = mlpfwd(net, x)
Definition at line 85 of file nnregress.m.