name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  # Debug environment
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      # Install debugger
      - name: Install Doxygen
        run: sudo apt install gdb


  # Build and Integration Test
  build:
    strategy:
      fail-fast: false
      matrix:
        OS:
          - macos-latest
          - ubuntu-latest
          - ubuntu-24.04
          - ubuntu-22.04
    runs-on: ${{ matrix.OS }}

    steps:
      # checkout source code
      - uses: actions/checkout@v2

      # install doxygen
      - name: Install Doxygen
        run:  |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get install doxygen -y
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install --formula doxygen
          fi

      # compile SIPNET
      - name: compile sipnet
        run: make

      # run smoke tests
      - name: Run SIPNET smoke tests
        shell: bash
        run: tests/smoke/run_smoke.sh

  # Run Unit Tests
  test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        OS:
          - macos-latest
          - ubuntu-latest
          - ubuntu-24.04
          - ubuntu-22.04
    runs-on: ${{ matrix.OS }}

    steps:
      # checkout source code
      - uses: actions/checkout@v2

      # compile unit tests
      - name: compile tests
        run: make test

      # run tests
      - name: Run Unit Tests
        run: make testrun
