name: PR docs preview
on:
  pull_request:
    types: [opened, reopened, synchronize]
permissions:
  contents: write
  pull-requests: write

concurrency: preview-${{ github.ref }}

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz
          python3 -m pip install --upgrade pip
          python3 -m pip install mkdocs mkdocs-material pymdown-extensions

      - name: Build docs
        run: make clean document

      - name: Deploy PR preview (replace subdir)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: site
          target-folder: pr-preview/pr-${{ github.event.number }}
          clean: true
          clean-exclude: |
            .nojekyll

      - name: Comment preview URL on PR
        uses: actions/github-script@v7
        env:
          PREVIEW_URL: https://pecanproject.github.io/sipnet/pr-preview/pr-${{ github.event.number }}/
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pr_number = context.payload.pull_request.number;
            const url = process.env.PREVIEW_URL;
            const body = `Preview: ${url}`;
            await github.rest.issues.createComment({ owner, repo, issue_number: pr_number, body });
