SIPNET: util.h File Reference
util.h File Reference
#include <stdio.h>
Functions
void buildFileName (char *filename, const char *base, const char *ext)
FILE * openFile (const char *name, const char *mode)
FILE * openFileExt (const char *name, const char *ext, const char *mode)
void seedRand (unsigned int seed, FILE *outF)
double randm ()
double * makeArray (int size)
double ** make2DArray (int nrows, int ncols)
int ** make2DIntArray (int nrows, int ncols)
void free2DArray (void **arr)
void assignArray (double *out, double *in, int n)
double sumArray (double *array, int length)
int strcmpIgnoreCase (const char *s1, const char *s2)
int stripComment (char *line, const char *commentChars)
Function Documentation
assignArray()
void assignArray (double * out, double * in, int n)
Definition at line 111 of file SIPNEToptsIn/util.c.
References i, index, and n.
buildFileName()
void buildFileName (char * filename, const char * base, const char * ext)
Definition at line 19 of file util.c.
References index.
Referenced by main(), and openFileExt().
free2DArray()
void free2DArray (void ** arr)
Definition at line 104 of file SIPNEToptsIn/util.c.
References index.
Referenced by cleanupParamchange(), main(), and metropolis().
make2DArray()
double ** make2DArray (int nrows, int ncols)
Definition at line 72 of file SIPNEToptsIn/util.c.
References i, and index.
Referenced by main(), metropolis(), readData(), and readFileForAgg().
make2DIntArray()
int ** make2DIntArray (int nrows, int ncols)
Definition at line 87 of file SIPNEToptsIn/util.c.
References i, and index.
Referenced by readData().
makeArray()
double * makeArray (int size)
Definition at line 58 of file SIPNEToptsIn/util.c.
References index.
Referenced by aggedDifference(), aggregates(), difference(), main(), metropolis(), newOutputInfo(), and readData().
openFile()
FILE * openFile (const char * name, const char * mode)
Definition at line 27 of file util.c.
References exit(), f, index, and name.
Referenced by openFileExt().
openFileExt()
FILE * openFileExt (const char * name, const char * ext, const char * mode)
Definition at line 40 of file util.c.
References buildFileName(), f, index, name, and openFile().
Referenced by main().
randm()
double randm ()
Definition at line 47 of file SIPNEToptsIn/util.c.
References index.
Referenced by metropolis().
seedRand()
void seedRand (unsigned int seed, FILE * outF)
Definition at line 29 of file SIPNEToptsIn/util.c.
References fprintf(), index, t, and time.
Referenced by main().
strcmpIgnoreCase()
int strcmpIgnoreCase (const char * s1, const char * s2)
Definition at line 161 of file util.c.
References i, index, and result.
Referenced by locateNamelistInputItem(), locateParam(), main(), and readSpatialValues().
stripComment()
int stripComment (char * line, const char * commentChars)
Definition at line 189 of file util.c.
References index.
Referenced by readNamelistInputs(), and readSpatialParams().
sumArray()
double sumArray (double * array, int length)
Definition at line 120 of file SIPNEToptsIn/util.c.
References i, index, length(), and sum().
Referenced by metropolis(), and reset().